openwallet-foundation/multipaz

appholder/src/main/java/com/android/mdl/app/fragment/SettingsFragment.kt
appholder/src/main/java/com/android/mdl/app/fragment/TransferDocumentFragment.kt
appholder/src/main/java/com/android/mdl/app/util/PreferencesHelper.kt
appholder/src/main/res/values/strings.xml
appholder/src/main/res/xml/root_preferences.xml
appverifier/src/main/java/com/android/mdl/appreader/readercertgen/ReaderCertificateGenerator.java

- Renamed common name from reader certificate used by verifier to "Google mDoc Reader""
- Removed option on holder to use reader authetication using ACP when provsioning the documents

Adjust reader authentication

---

appholder/src/main/AndroidManifest.xml
appholder/src/main/java/com/android/mdl/app/fragment/SelectDocumentFragment.kt
appverifier/src/main/AndroidManifest.xml
appverifier/src/main/java/com/android/mdl/appreader/fragment/DeviceEngagementFragment.kt
identity/src/main/AndroidManifest.xml

It turns out we need this permission for WiFi Aware. The requirement was
dropped for BLE, and I mistakenly thought we no longer needed it for anything.

Add fine location permission back

---

README.md
settings.gradle

The project is now available at https://github.com/google/identity-credential.
Also update README.md to express that the project is now also used as
the upstream for the code that was previously in AndroidX and released
as the Identity Credential Jetpack.

Rename project and update README.md

---

build.gradle
identity/src/androidTest/java/com/android/identity/UtilTests.java
identity/src/main/java/com/android/identity/Util.java
identity/src/main/java/com/android/identity/Utility.java

The helper Util.issuerSignedItemBytesSetValue() takes a the bytes of
|IssuerSignedItemBytes| and replaces the value (usually NULL) for the
"elementValue" key with a given value. It then returns the bytes of
|IssuerSignedItemBytes|.
Because |IssuerSignedItemBytes| originates from the issuer (as part of
|staticAuthData|, see Utility.encodeStaticAuthData() for the CDDL) and
|IssuerSignedItem| is a map, it's not well-defined what the encoding
is. The issuer could choose whatever order they want.
This change fixes Util.issuerSignedItemBytesSetValue() so the order is
preserved. This is done by upgrade cbor-java to 0.9 and using the
non-canonical encoder. Also add unit test for this.
Test: Manually tested holder and verifier.

Preserve order when replacing NULL in IssuerSignedItemBytes CBOR.

---

identity/src/androidTest/java/com/android/identity/HardwareIdentityCredentialTest.java
identity/src/main/java/com/android/identity/HardwareIdentityCredential.java

This silences a lint warning which can break compilation in some environments.
Since our status codes are defined consistently (same values) with those in the Android platform, no actual conversion is necessary. To check that this assumption holds, I've added a test case covering the constant values currently defined in the Android platform.
Tested: Unit tests still pass.

Map Android platform ResultData.Status codes to our own.

---

identity/src/main/java/com/android/identity/Util.java

Some but not all SimpleDateFormat invocations in Util.java specified a Locale; these particular formats probably don't contain Locale-dependent fields, but this is more definitely correct if we specify a Locale.
I chose Locale.US for consistency with existing use in the file. Locale.ROOT would probably also have worked.
This will fix compilation in setups that enforce Locale-aware code.
I've checked that the code still compiles in Android Studio.

Util.java: Specify a Locale for SimpleDateFormat instances.

---

identity/src/main/java/com/android/identity/DataTransportBleCentralClientMode.java
identity/src/main/java/com/android/identity/DataTransportBlePeripheralServerMode.java
identity/src/main/java/com/android/identity/SoftwarePresentationSession.java

Lint rules at compile time enforce log TAGs <= 23chars in some environments. I suspect that the Lint rule's existence means that log tags are truncated or similar to 23chars anyway, so having longer TAGs gives the wrong impression that the whole TAG is used.
This commit shortens the overlong TAGs to <= 23chars by removing some suffixes from camelCased words; this way, copy&pasting the TAG into IntelliJ will still find the right class.

Limit log TAGs to 23chars.

---

identity/src/androidTest/java/com/android/identity/DeviceResponseGeneratorTest.java
identity/src/main/java/com/android/identity/DataTransport.java
identity/src/main/java/com/android/identity/DataTransportBle.java
identity/src/main/java/com/android/identity/DataTransportNfc.java
identity/src/main/java/com/android/identity/DataTransportTcp.java
identity/src/main/java/com/android/identity/DataTransportWifiAware.java
identity/src/main/java/com/android/identity/SessionEncryptionDevice.java
identity/src/main/java/com/android/identity/SessionEncryptionReader.java
identity/src/main/java/com/android/identity/Utility.java
identity/src/main/java/com/android/identity/VerificationHelper.java

This is shorter but just as clear, thus more readable, and addresses a family of lint warnings.
This commit is a pure refactoring. I've added static imports via IntelliJ's corresponding refactoring feature.

static import StandardCharsets.UTF_8.

---

identity/src/main/java/com/android/identity/DataTransportTcp.java

Reintroduce a ; accidentally removed in commit 13db9829a9bc6b82d28b8579bcd13189d95133b7 (woops!).
Tested that tests pass now.

Fix compilation.

---

identity/src/main/java/com/android/identity/CredentialData.java
identity/src/main/java/com/android/identity/DataTransportBle.java
identity/src/main/java/com/android/identity/DataTransportTcp.java
identity/src/main/java/com/android/identity/DataTransportWifiAware.java
identity/src/main/java/com/android/identity/Util.java

Formatting of decimal integers ("%d") can be Locale dependent - I believe they are formatted differently for some Indian Locale.
To enforce a consistent representation, this commit explicitly uses Locale.US for formatting of integers via String.format("%d", ...) outside of log statements. Potentially in a future commit we can consider specifying a Locale when formatting for logs, too.
I also fixed one occurrence of String.toLowerCase(), which is also Locale dependent.

Avoid default Locale for String.format("%d", ...).

---

identity/src/main/java/com/android/identity/AccessControlProfile.java
identity/src/main/java/com/android/identity/CredentialData.java

Before this CL, CredentialData.createCredentialData() called ensureAcpTimoutKeyForProfile(..., timeoutSeconds) but that method expects a timeout in milliseconds.
Upon further inspection, timeoutSeconds came from profile.getUserAuthenticationTimeout(); that method did not document its time unit, but the corresponding Builder method is clear about it being milliseconds. Therefore it appears that the logic is correct but the name 'timeoutSeconds' was wrong.
This commit renames the misnamed variable and adds documentation to AccessControlProfile.getUserAuthenticationTimeout() noting that the returned time value is in milliseconds.
This commit is a pure refactoring with no behavior change.

CredentialData: Fix misnamed variable confusing time units.

---

identity/src/main/java/com/android/identity/DataTransportBle.java
identity/src/main/java/com/android/identity/DeviceResponseParser.java

I think there should also be a space between [] and {, but leaving that for now.

Move variable declarations to where they're initialized.

---

identity/src/main/java/com/android/identity/HardwareIdentityCredentialStore.java

Set already supports toArray(), no need for us to implement it ourselves.

Simplify HardwareIdentityCredentialStore.getSupportedDocTypes().

---

identity/src/main/java/com/android/identity/CredentialData.java

It was previously saying @{link }.

Fix malformed javadoc {@link }.

---

identity/src/main/java/com/android/identity/SessionEncryptionDevice.java
identity/src/main/java/com/android/identity/Util.java

1. foo instanceof Foo implies foo != null, so there is no need to check for null separately.
2. Numerous places in Util.java duplicate the type that one was casting to across three places (instanceof check, typecast, and error message string literal), and the expression being cast across the first two; this commit introduces a helper method castTo() that de-duplicates this.
3. One of the string literals was quoting the wrong type; this commit fixes that.
This commit is a refactoring with no behavior change except that it unifies the exception message, which sometimes means one needs the line number to find exactly the right place but is more consistent and saves bytes because it avoids a ton of near-duplicate string literals.
In a follow up commit, we could optionally consider changing …

De-duplicate repetitive boiler plate code around type casting.

---

identity/src/androidTest/java/com/android/identity/IdentityCredentialTest.java

For now, the test covers storing of static authentication data of varying size for varying numbers of authKeys. The reason this is worth testing is that storing this breaks a subsequent getCredentialByName() specifically for large data (100 KBytes+ across keys), apparently on API <= 28. For now this test is disabled via Assume.assumeTrue() on API versions where it is known to break, but this might be tweaked in a future commit if/when we better understand the exact root cause and conditions that trigger it.
I've confirmed that without the Assume.assumeTrue(), the test would break on the following emulated device / API combinations:
- Pixel 2 API 24
- Pixel 2 API 26
- Pixel 3 API 28
It passes on:
- Pixel 3 API 29
- Pixel 5 API 31
The test is parameterized to cover all …

Add IdentityCredentialTest.

---

appholder/src/main/java/com/android/mdl/app/document/DocumentManager.kt
identity/src/androidTest/java/com/android/identity/IdentityCredentialTest.java
identity/src/main/java/com/android/identity/IdentityCredentialStore.java

To give client time to migrate, keep a @deprecated method under the old name that delegates to the new one. I've added a TODO to get rid of the deprecated method in the longer term.
Also expand documentation of the method.

Rename IdentityCredentialStore.getInstance() -> getDefaultInstance.

---

identity/src/androidTest/java/com/android/identity/UtilTest.java

The name of this class was not idiomatic. This commit fixes it.
I only noticed that the misnamed test class existed after I had already uploaded https://github.com/google/identity-credential/pull/68 :-(
If you merge this pull request, I can redo the commits from that pull request.
Alternatively (easier for me but slightly messier git history), if you merge that pull request, then I'll create a follow-up pull request that merges the two test classes. Up to you.

Rename UtilTests -> UtilTest.

---

identity/src/androidTest/java/com/android/identity/UtilTest.java
identity/src/main/java/com/android/identity/Util.java

This pull request consists of three commits:
1. Add test coverage for Util methods, including a commented-out test that demonstrates https://github.com/google/identity-credential/issues/67
2. Fix https://github.com/google/identity-credential/issues/67
3. Simplify implementation of Util methods under test.

Tweak and fix Util methods around hex/base16 encoding/decoding

---

identity/src/androidTest/java/com/android/identity/UtilTest.java

For consistency, this commit adds test coverage that already exists for toHex() / fromHex().

Assert that Util.base16(null) throws NullPointerException.

---

.github/workflows/unit-test.yml

The gradle setup script tries to download from gradle.org, but this
was being blocked by the harden-security action.

Add services.gradle.org to the host allow list

---

.github/workflows/unit-test.yml

The unit test workflow was being blocked by the harden-runner action as
some domains were not allow-listed, and packages couldn't be resolved.

Allow actions to access more domains

---

.github/workflows/unit-test.yml

One of the endpoints we need is part of a Microsoft-hosted CDN, and we
get bounced to different servers in this domain depending on the whims
of the load balancer. Thus, we cannot allow-list the exact server,
but harden-runner also doesn't support wildcards. Just use audit mode
for now so we can at least see what's being accessed in the logs.

Switch egress hardening to audit mode

---

identity/src/androidTest/java/com/android/identity/SessionEncryptionDeviceTest.java
identity/src/main/java/com/android/identity/Constants.java
identity/src/main/java/com/android/identity/DataTransportNfc.java
identity/src/main/java/com/android/identity/DataTransportTcp.java
identity/src/main/java/com/android/identity/DataTransportWifiAware.java
identity/src/main/java/com/android/identity/DeviceResponseGenerator.java
identity/src/main/java/com/android/identity/DeviceResponseParser.java
identity/src/main/java/com/android/identity/PresentationHelper.java
identity/src/main/java/com/android/identity/SessionEncryptionDevice.java
identity/src/main/java/com/android/identity/SessionEncryptionReader.java
identity/src/main/java/com/android/identity/Util.java

CBOR uses 64 bit signed integers by default, so we should also
use a 64 bit type so that we don't run into any odd behaviors in
case of integers with very large magnitudes.

Switch all CBOR integer handling to use long

---

identity/src/main/java/com/android/identity/PresentationHelper.java
identity/src/main/java/com/android/identity/VerificationHelper.java

This can happen If the PresentationHelper instance is used from thread
A and callbacks happen in thread B.
Bug: 226351967
Test: Unit tests + manual testing with reference apps.

identity: Add locking around counter used for setting up transports.

---

identity/src/androidTest/java/com/android/identity/DeviceResponseParserTest.java
identity/src/androidTest/java/com/android/identity/UtilTest.java
identity/src/main/java/com/android/identity/DeviceResponseParser.java
identity/src/main/java/com/android/identity/PersonalizationData.java
identity/src/main/java/com/android/identity/ResultData.java
identity/src/main/java/com/android/identity/Timestamp.java
identity/src/main/java/com/android/identity/Util.java
identity/src/main/java/com/android/identity/Utility.java
identity/src/test/java/com/android/identity/TimestampTest.java

We want to allow this code to run on the JVM as well as in Android. This means
we need to avoid dependencies on Android-only classes like the android.icu.*
namespace.
The main use of android.icu is the Calendar class. Replace all internal uses with
a new Timestamp class. Public APIs still use Calendar for now, as we don't want
to break API compatibility just yet.

Partially break dependency on android.icu

---

appverifier/src/main/java/com/android/mdl/appreader/fragment/ShowDocumentFragment.kt

The previous Calendar -> Timestamp change forgot to cater for the case
where instances are passed directly to SimpleTextFormat.

reader: Fix crash when presenting received mDL.

---

appholder/src/main/java/com/android/mdl/app/transfer/TransferManager.kt
identity/src/main/java/com/android/identity/PresentationHelper.java

The current PresentationHelper design requires the caller to pass an
instance of android.nfc.cardemulation.HostApduService which makes it
tricky to unit test and also use in a multi-process application.
This change introduces a simple NfcResponse interface which does the
same thing.
Bug: None
Test: Manually tested, NFC device engagement still works.

Introduce interface for sending NFC response back to mdoc reader.

---

identity/src/androidTest/java/com/android/identity/IdentityCredentialTest.java
identity/src/main/java/com/android/identity/CredentialData.java

Older versions of Android Keystore have problems with decrypting large
cipher texts. Work around this by chopping the cleartext into 16 KiB
chunks and encrypt each separately. This changes the on-disk format
for how credential data is stored.
Change the unit test recently added to check for this.
Bug: 234563696
Test: Manually tested that old credential data files can be loaded.

Chunk credential data before encrypting.

---

identity/src/androidTest/java/com/android/identity/UtilTest.java
identity/src/main/java/com/android/identity/Util.java
identity/src/main/java/com/android/identity/Utility.java

18013-5 says: "The timestamps in the ValidityInfo structure shall not
use fractions of seconds"
Additionally, OpenJDK and Android differ on how they deal with decimal
seconds values that are not three digits. Instead of dealing with possible
inconsistency, just ignore fractions of a second.

Ignore milliseconds on timestamps

---

identity/src/androidTest/java/com/android/identity/StaticAuthDataTest.java
identity/src/androidTest/java/com/android/identity/UtilTest.java
identity/src/main/java/com/android/identity/DeviceResponseGenerator.java
identity/src/main/java/com/android/identity/Util.java
identity/src/main/java/com/android/identity/Utility.java

The root problem is that both encodeStaticAuthData() and
decodeStaticAuthData() has a bug where IssuerSignedItem is wrapped in
a #6.24-tagged bstr twice.
For self-signed credentials provisioned on the device via
Utility.provisionSelfSignedCredential() this wasn't a problem because
those two bugs cancels each other out. However for applications where
the StatisAuthData (e.g. MSO and digest-id mapping) is generated
outside the device (the usual case for production-level mDLs) this was
a problem because the generated StaticAuthData CBOR failed to decode
because of the bug in decodeStaticAuthData().
Fix this by slightly reworking the API so IssuerSignedItem blobs are
passed around, not IssuedSignedItemBytes. Specifically this affects
the following public APIs:
- Utility.mergeIssuerSigned()
- …

Fix double-wrapping of IssuerSignedItem.

---

.github/workflows/unit-test.yml
identity/build.gradle
identity/src/main/java/com/android/identity/CredentialData.java
identity/src/main/java/com/android/identity/SessionEncryptionDevice.java
identity/src/main/java/com/android/identity/SessionEncryptionReader.java
identity/src/main/java/com/android/identity/Util.java
identity/src/test/java/com/android/identity/TestUtilities.java
identity/src/test/java/com/android/identity/UtilTest.java

Two commits here (which shouldn't be squashed into one):
The first enables unit tests, converting `UtilTest` into the first test that may be run outside of an Android device.
The second commit adds type coercion helpers for string and integer `DataItem`s

Include unit tests and add CBOR type helpers

---

appholder/src/main/java/com/android/mdl/app/util/PreferencesHelper.kt
appverifier/src/main/java/com/android/mdl/appreader/fragment/DeviceEngagementFragment.kt
appverifier/src/main/java/com/android/mdl/appreader/transfer/TransferManager.kt
identity/src/main/java/com/android/identity/PresentationHelper.java
identity/src/main/java/com/android/identity/VerificationHelper.java

- For the reader, we only need to poll for Nfc-A and Nfc-B technology.
- For the capability file, we incorrectly conveyed that max NDEF file
size is 0xfffe but the standard says it can be no bigger than 0x7fff
and values 0x8000 through 0xffff are RFU.
- Use the right navigation link values in reader for error conditions.
- In both PresentationHelper and VerificationHelper, change semantics
of methods related to session-termination so they are always safe to
call and never will throw exceptions.
- In holder, the preference UI indicates that mdoc BLE central client
mode is the only available transport but the preference object
indicates that both mdoc BLE central client mode and mdoc BLE
peripheral server mode is available. Fix the latter so only mdoc BLE
central client mode is available. …

Minor fixes related to NFC engagement.

---

identity/src/main/java/com/android/identity/PresentationHelper.java

Starting with Android 12, the NFC tag reader code will use extended
length encoding if the host says it supports it. We didn't properly
handle this when processing a READ_BINARY command so NFC engagement
didn't work if the mDL reader was running on Android 12 or later.
Bug: 240261780
Test: Manually tested, NFC engagement with mDL reader on Android 12 now works.

NFC: Handle extended length encoding for READ_BINARY command

---

identity/src/main/java/com/android/identity/GattClient.java

Without this, the stack will also try to connect to Bluetooth Classic
devices which includes a bit of complexity and is a source of
potential bugs.

BLE: Specify that GATT connections are expected to only be to LE devices

---

identity/src/main/java/com/android/identity/CredentialData.java
identity/src/main/java/com/android/identity/SoftwareWritableIdentityCredential.java
identity/src/main/java/com/android/identity/Utility.java

Android KeyStore StrongBox - see Android CDD section 9.11.2 - allows
app developers to store cryptographic keys in a dedicated secure
processor.  Since this provides some additional protections of keys,
use it when available for CredentialKey and AuthKeys.
Also modify Utility.provisionSelfSignedCredential() to log the
certificate chain for inspection.
Bug: None
Test: Manually tested on Pixel devices.

Use StrongBox implementation of Android KeyStore when available.

---

identity/src/main/java/com/android/identity/HardwareIdentityCredentialStore.java

On Android 11 there is no feature flag so if the API is available, return
feature version 202009.
Bug: None
Test: Manually tested holder app on Android 11

Fix crash on Android 11.

---

identity/src/main/java/com/android/identity/GattClient.java
identity/src/main/java/com/android/identity/GattServer.java

Android supports MTUs up to 517 which we usually will get if the
communication is between two Android devices. However this means that
the chunks being written to Client2Server and Server2Client
characteristics are 514 bytes long which is in violation of the
Bluetooth spec which says they cannot be bigger than 512 bytes
(Bluetooth Core specification section Part F 3.2.9 Long attribute
values).
Starting with Android 13, it seems like this 512 limit is enforced
which means that our mDL app stopped working when either the mDL or
the mDL reader is on Android 13.
The problem is fixed by simply requesting an MTU of size 515 instead
of 517.
Also add better debug/logging to help catch this and similar problems
and add code to report an error if a non-final chunk isn't the MTU
size less 3, as …

BLE: Change requested MTU to 515 and add better debug for chunking.

---

appholder/src/main/java/com/android/mdl/app/document/DocumentManager.kt
appholder/src/main/java/com/android/mdl/app/transfer/TransferManager.kt
identity/src/main/java/com/android/identity/IdentityCredentialStore.java
identity/src/main/java/com/android/identity/Util.java

It's confusing to have both getHardwareInstance() and
getHardwareKeystoreInstance() so rename the latter to be just
getKeystoreInstance().
Bug: None
Test: Manually tested presentation.

IdentityCredentialStore: Rename getHardwareKeystoreInstance() to getKeystoreInstance()

---

identity/src/main/java/com/android/identity/DataTransportBle.java
identity/src/main/java/com/android/identity/GattClient.java
identity/src/main/java/com/android/identity/GattServer.java
identity/src/main/java/com/android/identity/L2CAPClient.java
identity/src/main/java/com/android/identity/L2CAPServer.java
identity/src/main/java/com/android/identity/PresentationHelper.java
identity/src/main/java/com/android/identity/Util.java
identity/src/test/java/com/android/identity/UtilTest.java

- Both accept() and connect() are blocking so need to be called
in worker threads
- Avoid extraneous thread for reading messages.
- When reading, Don't look at isConnected() since may need to
empty the socket before handling end-of-stream.
- Add a 100ms sleep in writing threads after each write to give the
data a chance to be sent before we're closing the socket (close
joins on the writing thread). This is to work around a suspected bug
in BluetoothSocket. Real world impact should be zero since apps
rarely send two messages right after each other.
- Implement progress callbacks
Also to get some more testing of L2CAP, turn this on by default.
Test: Manually tested incl. session termination on both sides.
Bug: None

L2CAP: Fix threading issues, progress callbacks, and enable L2CAP by default

---

appholder/src/main/java/com/android/mdl/app/fragment/SettingsFragment.kt
appholder/src/main/java/com/android/mdl/app/transfer/TransferManager.kt
appholder/src/main/java/com/android/mdl/app/util/PreferencesHelper.kt
appholder/src/main/res/xml/root_preferences.xml
appverifier/src/main/java/com/android/mdl/appreader/transfer/TransferManager.kt
appverifier/src/main/java/com/android/mdl/appreader/util/PreferencesHelper.kt
appverifier/src/main/res/xml/root_preferences.xml
identity/src/main/java/com/android/identity/Constants.java
identity/src/main/java/com/android/identity/DataTransportBle.java
identity/src/main/java/com/android/identity/DataTransportBleCentralClientMode.java
identity/src/main/java/com/android/identity/DataTransportBlePeripheralServerMode.java
identity/src/main/java/com/android/identity/GattClient.java
identity/src/main/java/com/android/identity/PresentationHelper.java
identity/src/main/java/com/android/identity/VerificationHelper.java

We have reports that when using BLE mdoc central client mode with a
particular reader things will work better if we force Android to clear
its internal BLE Service Cache before we initiate service
discovery. This is possible using only unsupported API and
introspection. The function in question is the refresh() method on the
BluetoothGatt class.
To better debug and investigate this, add API to enable this behavior
and surface this setting in both the holder and reader reference
apps. The default value for this setting is off.
Bug: None

BLE: Add a setting to clear BLE Service Cache just before service discovery

---

appholder/build.gradle
appholder/src/main/java/com/android/mdl/app/document/DocumentManager.kt
appverifier/build.gradle
build.gradle
identity/build.gradle
identity/src/main/java/com/android/identity/CredentialDataRequest.java
identity/src/main/java/com/android/identity/HardwareIdentityCredentialStore.java
identity/src/main/java/com/android/identity/HardwarePresentationSession.java
identity/src/main/java/com/android/identity/PlatformCredentialDataResult.java

This requires updating to the latest version of the biometric Jetpack with support for platform android.security.identity.PresentationSession. Also requires depending on an SDK for API 33.
Bug: None
Test: Verified that Pixel 4a running Android 13 is using HW-backed Identity Credential.

Add support for HW-backed Identity Credential feature version 202201.

---

appholder/src/main/AndroidManifest.xml
appholder/src/main/java/com/android/mdl/app/fragment/ShareDocumentFragment.kt
appholder/src/main/java/com/android/mdl/app/fragment/TransferDocumentFragment.kt
appholder/src/main/java/com/android/mdl/app/transfer/TransferManager.kt
appholder/src/main/java/com/android/mdl/app/util/NfcDataTransferHandler.kt
appholder/src/main/java/com/android/mdl/app/util/NfcEngagementHandler.kt
appholder/src/main/java/com/android/mdl/app/util/TransferStatus.kt
appholder/src/main/java/com/android/mdl/app/viewmodel/ShareDocumentViewModel.kt
appholder/src/main/res/layout-land/fragment_share_document.xml
appholder/src/main/res/layout/fragment_share_document.xml
appholder/src/main/res/values/strings.xml
appholder/src/main/res/xml/nfc_data_transfer_apdu_service.xml
identity/src/androidTest/java/com/android/identity/DataTransportTcpTest.java
identity/src/androidTest/java/com/android/identity/PresentationHelperTest.java
identity/src/androidTest/java/com/android/identity/StoreStaticAuthenticationDataTest.java
identity/src/main/java/com/android/identity/DataTransport.java
identity/src/main/java/com/android/identity/DataTransportNfc.java
identity/src/main/java/com/android/identity/NfcApduRouter.java
identity/src/main/java/com/android/identity/NfcEngagementHelper.java
identity/src/main/java/com/android/identity/NfcUtil.java
identity/src/main/java/com/android/identity/PresentationHelper.java
identity/src/main/java/com/android/identity/QrEngagementHelper.java
identity/src/main/java/com/android/identity/VerificationHelper.java

This introduces two new classes QrEngagementHelper and NfcEngagementHelper which implements QR engagement and NFC engagement (static handover) as per 18013-5. Introduce a new class NfcApduRouter to help facilitate the application delivering APDUs to now various distinct pieces of functionality.
Also change reference application to not show QR code by default. Implementation-wise this means that we only spin up BLE radios when either the QR code is shown or when handling NFC engagement. This helps save battery and reduce attack surface.
This is prep work for both 18013-7 mdoc:// support (upcoming ReaderEngagement{Parser, Generator}, DataTransportHttp types) and also NFC negotiated handover support.
It also lays the groundwork for alternative forms of engagement, in a future change concrete …

Move device engagement out of PresentationHelper.

---

identity/src/androidTest/java/com/android/identity/ConnectionMethodTest.java
identity/src/androidTest/java/com/android/identity/EngagementGeneratorTest.java
identity/src/androidTest/java/com/android/identity/EngagementParserTest.java
identity/src/androidTest/java/com/android/identity/OriginInfoTest.java
identity/src/androidTest/java/com/android/identity/ReaderAuthTest.java
identity/src/androidTest/java/com/android/identity/TestVectors.java
identity/src/main/java/com/android/identity/ConnectionMethod.java
identity/src/main/java/com/android/identity/ConnectionMethodBle.java
identity/src/main/java/com/android/identity/ConnectionMethodNfc.java
identity/src/main/java/com/android/identity/ConnectionMethodRestApi.java
identity/src/main/java/com/android/identity/ConnectionMethodWifiAware.java
identity/src/main/java/com/android/identity/DataTransportBle.java
identity/src/main/java/com/android/identity/EngagementGenerator.java
identity/src/main/java/com/android/identity/EngagementParser.java
identity/src/main/java/com/android/identity/OriginInfo.java
identity/src/main/java/com/android/identity/OriginInfoNfc.java
identity/src/main/java/com/android/identity/OriginInfoQr.java
identity/src/main/java/com/android/identity/OriginInfoWebsite.java
identity/src/main/java/com/android/identity/Util.java

This is mostly just refactoring existing code into Engagement{Parser, Genenerator} except for newly added support for OriginInfo which is used in upcoming ISO 18013-7 and ISO 23220-4 standards. This work will be used in mdoc:// support for over-the-Internet mdoc presentations according to 18013-7.
Existing QrEngagementHelper and NfcEngagementHelper haven't been wired up to use this yet as that will include migrating DataRetrievalAddress classes to the new ConnectionMethod classes. This will happen in an upcoming change.
Test: New unit tests and all unit tests pass
Bug: None

Add EngagementGenerator and EngagementParser.

---

appholder/src/main/java/com/android/mdl/app/document/DocumentManager.kt
appholder/src/main/java/com/android/mdl/app/fragment/AddSelfSignedFragment.kt
appholder/src/main/java/com/android/mdl/app/fragment/ProvisioningFragment.kt
appholder/src/main/java/com/android/mdl/app/fragment/TransferDocumentFragment.kt
appholder/src/main/java/com/android/mdl/app/transfer/TransferManager.kt
appholder/src/main/java/com/android/mdl/app/util/DocumentData.kt
appholder/src/main/java/com/android/mdl/app/util/SelfSignedDocumentData.kt
appholder/src/main/java/com/android/mdl/app/viewmodel/SelfSignedViewModel.kt
appholder/src/main/java/com/android/mdl/app/viewmodel/TransferDocumentViewModel.kt
appholder/src/main/res/layout/fragment_add_self_signed.xml
appholder/src/main/res/values/arrays.xml
appholder/src/main/res/values/strings.xml

- No documents are automatically created once we install the app.
- It is possible to add more than one document for the same docType
- It is possible to provision documents using different store implementation
- User can choose which document to transfer if there are multiples for the same docType
- Document transfer can only transfer documents provisioned in Keystore implementation
* Needs to be fixed transfer multiple documents from multiple store implementations

Add multiple documents with the same docType

---

appholder/src/main/java/com/android/mdl/app/transfer/TransferManager.kt
identity/src/main/java/com/android/identity/KeystorePresentationSession.java

This is not needed and setting an empty session transcript won't work with the HW-backed Identity Credential. This was here because KS-Backed PresentationSession didn't work with an unset SessionTranscript. Fix that.

Don't set session transcript when viewing data elements.

---

appholder/src/main/java/com/android/mdl/app/authprompt/UserAuthPromptBuilder.kt

This is unnecessary because we already have a consent dialog which requires the user to press a button to send the data. As a result, the consent dialog looks a lot more delightful in this mode, see https://www.youtube.com/watch?v=hziY3kp2YE4 for a quick video.
Test: Manually tested on Pixel 4 XL

Don't require user confirmation when using BiometricPrompt.

---

appholder/src/main/java/com/android/mdl/app/document/DocumentManager.kt
appholder/src/main/java/com/android/mdl/app/util/DocumentData.kt
appholder/src/main/java/com/android/mdl/app/viewmodel/SelfSignedViewModel.kt
appverifier/src/main/java/com/android/mdl/appreader/document/RequestMdlUsTransportation.kt
appverifier/src/main/java/com/android/mdl/appreader/fragment/RequestOptionsFragment.kt
appverifier/src/main/res/layout/fragment_request_options.xml
appverifier/src/main/res/values/strings.xml

Also add a couple of mandatory AAMVA data elements in the default self-signed mDL. The new reader option is called "mDL for US transportion" and will request an asssorted set of data elements in both the org.iso.18013.5.1 and org.iso.18013.5.1.aamva namespace.
This actually uncovered a bug in our holder app insofar that two documents are included in the response, one for each namespace. A subsequent change will fix this to be just one document.

Use correct AAMVA namespace and add new reader option for US transportation.

---

identity/src/main/java/com/android/identity/EngagementParser.java
identity/src/main/java/com/android/identity/GattServer.java
identity/src/main/java/com/android/identity/Util.java
identity/src/test/java/com/android/identity/UtilTest.java

There is an mDL app which sends a DeviceEngagement via QR with version set to "1.0" and includes a value for key 5 despite ISO 18013-5 section 8.2.1.1 Device engagement structure being quite clear that positive key values are RFU. The value which said mDL included in key 5 was an array with a single string set to "org.iso.18013.5.1.mDL".
This uncovered an issue with our new EngagementParser used in our mdoc reader which is looking for key 5 since it's defined in 18013-7/23220-4 to contain an array of OriginInfo. Fix the issue by making the parser only look for key 5 if version is set to "1.1" or later. Also print a warning that if an mDL / mdoc uses this key for version "1.0" that it is not compliant to the standard.
Additionally, once the DeviceEngagement problem was resolved another …

Work around broken mDL app using key 5 in DeviceEngagement 1.0.

---

identity/src/androidTest/java/com/android/identity/DeviceResponseGeneratorTest.java
identity/src/main/java/com/android/identity/CredentialData.java
identity/src/main/java/com/android/identity/DeviceResponseGenerator.java
identity/src/main/java/com/android/identity/DeviceResponseParser.java
identity/src/main/java/com/android/identity/KeystoreWritableIdentityCredential.java
identity/src/main/java/com/android/identity/Utility.java
identity/src/test/java/com/android/identity/DeviceResponseParserTest.java

In a couple of places we were reencoding CBOR and canonicalizing it leading to digest mismatch problems at presentation time when a canonicalized version was sent to the mdoc reader. This only affected data element values with non-trivial CBOR encodings for example driving_privileges from the mDL namespace.
Fix this by adding unit tests in all places where we return data elements including credential storage, proof of provisioning, and response generation / parsing.
Test: All unit tests pass (both with Keystore and IC APIs)

Fix canonicalization problems.

---

appholder/src/main/java/com/android/mdl/app/MainActivity.kt
identity/src/main/java/com/android/identity/EngagementGenerator.java
identity/src/main/java/com/android/identity/PresentationHelper.java
identity/src/main/java/com/android/identity/QrEngagementHelper.java
identity/src/main/java/com/android/identity/VerificationHelper.java
identity/src/test/java/com/android/identity/EngagementGeneratorTest.java

Some mobile web browsers (Firefox on Android) do not convey the referrer URL which makes our application bail. Instead, just attempt the request and convey an empty OriginInfos array and let the mdoc reader website deal with an empty OriginInfos.
To implement this, we need to change the API on EngagementGenerator so it's possible to set an empty OriginInfos because 18013-7 says that this must be present (even if empty).

Support referrer not being set for 18013-7 transactions.

---

appholder/src/main/java/com/android/mdl/app/util/NfcEngagementHandler.kt
appverifier/src/main/java/com/android/mdl/appreader/transfer/TransferManager.kt
identity/src/androidTest/java/com/android/identity/NfcEnagementHelperTest.java
identity/src/main/java/com/android/identity/ConnectionMethod.java
identity/src/main/java/com/android/identity/ConnectionMethodBle.java
identity/src/main/java/com/android/identity/ConnectionMethodHttp.java
identity/src/main/java/com/android/identity/ConnectionMethodNfc.java
identity/src/main/java/com/android/identity/ConnectionMethodWifiAware.java
identity/src/main/java/com/android/identity/NfcEngagementHelper.java
identity/src/main/java/com/android/identity/NfcUtil.java
identity/src/main/java/com/android/identity/VerificationHelper.java

This works as-is but needs a bit of cleanup and also UI settings elements before we can land it. It currently defaults to NFC static handover meaning there are no functional changes.
Unit tests cover both NFC static handover and negotiated handover.

Implement NFC Negotiated Handover and add unit test for NFC engagement.

---

appholder/src/main/java/com/android/mdl/app/document/DocumentManager.kt
appholder/src/main/java/com/android/mdl/app/util/PreferencesHelper.kt

Avoid crash at presentation where the wrong PresentationSession is created (HW-backed session for Keystore-backed credentials).
Also change the default fot "Auto-close connection" to false since this needs a little bit of work on the identity library side to work reliably.

Two small holder fixes.

---

appholder/src/main/java/com/android/mdl/app/util/NfcEngagementHandler.kt

This makes it possible in the holder to select whether to use negotiated or static handover. The default is static handover.

Wire up setting for NFC handover.

---

appholder/src/main/java/com/android/mdl/app/MainActivity.kt

Fixes the bug that the holder draws over the lock screen when that's not expected.
Supporting an engagement and a transfer from the lock screen should be done differently.

Prevent drawing over lock screen

---

identity/src/main/java/com/android/identity/Util.java
identity/src/test/java/com/android/identity/UtilTest.java

RFC 8152 section 13.1.1.  Double Coordinate Curves says to use [SEC1] for converting X coordinates to bstr (and to preserve leading zero octects) which implies the octet string for each coordinate is always 32 bytes (for curve P-256).
This was discovered when testing against an implementation that wasn't as tolerants as other implementations.
Also add a warning if receiving/decoding a COSE_Key where this requirement isn't met.
Test: New unit test
Test: Manually performed a presentation

Fix COSE_Key encoding.

---

identity/src/androidTest/java/com/android/identity/NfcEnagementHelperTest.java
identity/src/main/java/com/android/identity/NfcUtil.java
identity/src/main/java/com/android/identity/VerificationHelper.java

NFC Forum Type 4 Tag Technical Specification Version 1.2 section 5.3.1 says to use a short READ_BINARY for the CC file (b/c the CC File contains the value for MLe). Also we already know the lenght of the CC file (at least the parts we're interested in), so hardcode the length to 15 instead of getting the length and then all the payload.
Unify APDU generation routines (instead of having multiple copies) and have the READ_BINARY one use short length if the request length fits in a byte.
The root cause for this problem is that when we landed the NFC Negotiated Handover we starting using NfcAdapter.FLAG_READER_SKIP_NDEF_CHECK which means the OS won't do anything and we do all the NDEF detection ourselves via IsoDep. Here are the APDUs received by the holder device before we started using …

mdoc reader: Fix CC file handling.

---

identity/src/main/java/com/android/identity/GattClient.java
identity/src/main/java/com/android/identity/GattServer.java
identity/src/main/java/com/android/identity/Util.java

On Server2Client and Client2Server attributes accept writes that are shorter than what ISO 18013-5 currently calls for. Previously we would fail the transaction if this were to happen.
Manually tested this by modifying sendMessage() to chop the data into smaller chunks than what we usually use.
Also slightly rework the nomenclature (in particular avoid the made up word "chunk") and introduce a generic utility function which calculates what the characterstic value size to use should be.
Test: Manually tested with BLE central client mode
Test: Manually tested with BLE peripheral server mode

BLE: Accept shorter writes on Server2Client / Client2Server

---

identity/src/main/java/com/android/identity/VerificationHelper.java

The linter started crashing after PR 166 landed. This fixes the problem and also fixes a bug where the int parameter for a %d directive in String.format() wasn't passed.
Test: Builds.

Fix linter crash.

---

identity/src/main/java/com/android/identity/CborUtil.java
identity/src/main/java/com/android/identity/DataTransportNfc.java
identity/src/main/java/com/android/identity/GattClient.java
identity/src/main/java/com/android/identity/GattServer.java
identity/src/main/java/com/android/identity/Logger.java
identity/src/main/java/com/android/identity/NfcEngagementHelper.java
identity/src/main/java/com/android/identity/PresentationHelper.java
identity/src/main/java/com/android/identity/QrEngagementHelper.java
identity/src/main/java/com/android/identity/Util.java
identity/src/main/java/com/android/identity/VerificationHelper.java
identity/src/test/java/com/android/identity/CborUtilTest.java

Add new CborUtil.toDiagnostics() which returns a string with the given CBOR (either a DataItem or a byte[]) print in diagnostics format as per RFC 8949 Section 8. Add flags so the caller can request it to be pretty-printed (indent and newlines) and also whether it should print embedded CBOR bytestrings.
Also introduce new Logger methods which prints CBor (both hex and diagnostics) or Hex for a given byte[], and adjust callsites to use this. This cleans up callsites since they no longer need to use Logger.isDebugEnabled() to avoid a costly conversion in the event that debug isn't enabled.
Test: New unit tests and all unit tests pass

Logging improvements and CBOR helper for printing diagnostics.

---

identity/src/androidTest/java/com/android/identity/PresentationHelperTest.java
identity/src/main/java/com/android/identity/Constants.java
identity/src/main/java/com/android/identity/DataTransportTcp.java
identity/src/main/java/com/android/identity/PresentationHelper.java
identity/src/main/java/com/android/identity/SessionEncryptionReader.java
identity/src/main/java/com/android/identity/VerificationHelper.java
identity/src/test/java/com/android/identity/SessionEncryptionDeviceTest.java
identity/src/test/java/com/android/identity/SessionEncryptionReaderTest.java

Previous behavior is that we would just terminate the session. With this change before session termination we send a message with no data and status 10 which according to 18013-5 Table 20 means "Error: session decryption".
It's not clear the standard actually requires an mdoc to do this but unfortunately it's something that certain test suites will check for.
Add new unit test to check the behavior and introduce symbolic constants instead of hardcoding 10 and 20.
Test: New unit test and all unit tests pass.
Test: Manually tested reference apps on two Pixel devices.
Issue: 115

Send message with status 10 if unable to decrypt message from reader.

---

appholder/src/main/java/com/android/mdl/app/transfer/TransferManager.kt
identity/src/androidTest/java/com/android/identity/DeviceResponseGeneratorTest.java
identity/src/androidTest/java/com/android/identity/PresentationHelperTest.java
identity/src/main/java/com/android/identity/DeviceResponseGenerator.java

Return an error for a data element is possible according to ISO 18013-5:2021 but our DeviceResponseGenerator class didn't provide a way to do this.
This commit doesn't include API in DeviceResponseParser to obtain the errors, this may be done in a future commit.
Test: Unit tests
Issue: 98

Make it possible to return error codes for data elements.

---

identity/src/androidTest/java/com/android/identity/X509CertificateSigningTest.java
identity/src/main/java/com/android/identity/CredentialData.java

Fixes an issue where the `FileOutputStream` was being closed before the sync is completed in the finishWrite Call. The finishWrite call in its current implementation will handle closing the stream after the sync is attempted.

Removing code that closes a FileOutputStream before a sync is completed

---

identity/src/main/java/com/android/identity/Util.java

Might be too big of a change to make, not sure if you had other plans to test it more gradually.

Point `cborEncode` to `cborEncodeWithoutCanonicalizing` thereby making all cbor encodings use nonCanonical()

---

identity/src/androidTest/java/com/android/identity/NfcEnagementHelperTest.java
identity/src/main/java/com/android/identity/NfcEngagementHelper.java
identity/src/main/java/com/android/identity/NfcUtil.java
identity/src/main/java/com/android/identity/VerificationHelper.java

Properly parse service parameter record and calculate tWait and use it. As it turns out, some mDLs in the wild actually require us to respect the timing requirements.
The service selection response parsing code has also been modified to accomodate the fact that the tag may return other records.
Add a way to bypass UPDATE_BINARY optimization to better facilitate testing with mDLs that don't properly support this, see the boolean bypassUpdateBinaryOptimization in VerificationHelper.java.
Test: New unit tests and manual testing.

Assorted NFC Negotiated Handover fixes.

---

identity/src/main/java/com/android/identity/DeviceRequestParser.java

Enabling flag has side effect of automatically treating as an unverified reader.

Flag to skip request reader auth structure parsing

---

identity/src/androidTest/java/com/android/identity/DeviceResponseGeneratorTest.java
identity/src/androidTest/java/com/android/identity/StaticAuthDataTest.java
identity/src/main/java/com/android/identity/CredentialData.java
identity/src/main/java/com/android/identity/DeviceResponseGenerator.java
identity/src/main/java/com/android/identity/DeviceResponseParser.java
identity/src/main/java/com/android/identity/Util.java
identity/src/test/java/com/android/identity/UtilTest.java

Since Util.cborEncode() is equivalent now, just use that.
Also simplify the StaticAuthDataTest to use the new CborUtil.toDiagnostics() which can print embedded CBOR.

Delete Util.cborEncodeWithoutCanonicalizing() and fix static auth data test.

---

identity/src/main/java/com/android/identity/ConnectionMethod.java
identity/src/main/java/com/android/identity/ConnectionMethodNfc.java
identity/src/main/java/com/android/identity/NfcEngagementHelper.java
identity/src/main/java/com/android/identity/NfcUtil.java
identity/src/main/java/com/android/identity/VerificationHelper.java

Google apps use TNF == 0x02 (Media-type) for all AC records including NFC which is wrong
According to mDL spec, it should be 0x04 (NFC Forum external type) 
Test: Manually (used other vendor mDL holder which detects the issue)
Fixes #243

Change NFC AC record TNF ID to 0x04 (NFC Forum external type) 

---

identity/src/androidTest/java/com/android/identity/DeviceRetrievalHelperTest.java
identity/src/main/java/com/android/identity/DeviceRetrievalHelper.java
identity/src/main/java/com/android/identity/SessionEncryptionDevice.java
identity/src/main/java/com/android/identity/SessionEncryptionReader.java
identity/src/main/java/com/android/identity/Util.java

In this case, send status code 10 to the reader to end the session and report an error to the application.
Fixes #115.
Test: New unit test and all tests pass.
Issue: 115

Better handling when the reader sends an invalid COSE_Key for EReaderKey

---

appholder/src/main/java/com/android/mdl/app/MainActivity.kt
appholder/src/main/java/com/android/mdl/app/fragment/TransferDocumentFragment.kt
appholder/src/main/java/com/android/mdl/app/transfer/Communication.kt
appholder/src/main/java/com/android/mdl/app/transfer/QrCommunicationSetup.kt
appholder/src/main/java/com/android/mdl/app/transfer/ReverseQrCommunicationSetup.kt
appholder/src/main/java/com/android/mdl/app/transfer/TransferManager.kt
appholder/src/main/java/com/android/mdl/app/util/NfcEngagementHandler.kt
appholder/src/main/java/com/android/mdl/app/viewmodel/TransferDocumentViewModel.kt
appverifier/src/main/java/com/android/mdl/appreader/fragment/DeviceEngagementFragment.kt
appverifier/src/main/java/com/android/mdl/appreader/fragment/TransferFragment.kt
identity/src/androidTest/java/com/android/identity/DeviceRetrievalHelperTest.java
identity/src/main/java/com/android/identity/DataTransport.java
identity/src/main/java/com/android/identity/DataTransportBleCentralClientMode.java
identity/src/main/java/com/android/identity/DataTransportBlePeripheralServerMode.java
identity/src/main/java/com/android/identity/DeviceRetrievalHelper.java
identity/src/main/java/com/android/identity/GattClient.java
identity/src/main/java/com/android/identity/GattServer.java
identity/src/main/java/com/android/identity/VerificationHelper.java

Fix a problem with BLE data transport methods where data isn't flushed before the connection is closed.
Also rework DeviceRetrievalHelper.SendMessage() so it's possible to specify the status code in addition or instead of the DeviceResponse CBOR to send.
Combined, these two fixes makes it possible for an application to send status 20 (session termination) in addition to DeviceResponse. Use this to implement the "Auto close connection" preference in the holder application. Fix up VerificationHelper so looks at both status and data and it behaves in the expected way when the holder does this.
This has been tested with both mdoc BLE central client mode and mdoc BLE peripheral server mode and with the case where holder uses "auto close connection" and not. For the latter, was also tested with …

Slightly refactor API to make it possible to properly auto-close connections.

---

README.md

Include a step to add datastore permissions for AppEngine's default service account.
Without this, we'll see the `com.google.cloud.datastore.DatastoreException: Missing or insufficient permissions` error during runtime

Update README.md to add datastore permissions for AppEngine's default service account.

---

wwwverifier/build.gradle

Encountered the following error after deploying to app engine:
```
com/android/identity/wwwreader/RequestServlet has been compiled by a more recent version of the Java Runtime (class file version 55.0
--
this version of the Java Runtime only recognizes class file versions up to 52.0
```
Noticed that the Java 11 is used in build.gradle for both source and target compatibility. Updating it to use Java 1.8

Update build.gradle to use Java 1.8

---

identity/src/main/java/com/android/identity/keystore/BouncyCastleKeystore.java
identity/src/main/java/com/android/identity/keystore/KeystoreEngine.java
identity/src/main/java/com/android/identity/keystore/KeystoreEngineRepository.java
identity/src/main/java/com/android/identity/storage/EphemeralStorageEngine.java
identity/src/main/java/com/android/identity/storage/GenericStorageEngine.java
identity/src/main/java/com/android/identity/storage/StorageEngine.java
identity/src/test/java/com/android/identity/keystore/BouncyCastleKeystoreTest.java
identity/src/test/java/com/android/identity/storage/EphemeralStorageTest.java
identity/src/test/java/com/android/identity/storage/GenericStorageTest.java

These two abstractions will form the foundation of the new credential storage system. This PR includes a keystore implementation using Bouncycastle which is useful on the server-side and other non-Android environments. An implementation using Android Keystore will follow.

Add storage and keystore abstractions.

---

identity-android/src/androidTest/java/com/android/identity/android/credential/AndroidKeystoreCredentialStoreTest.java
identity/src/main/java/com/android/identity/credential/Credential.java
identity/src/main/java/com/android/identity/credential/CredentialStore.java
identity/src/main/java/com/android/identity/credential/CredentialUtil.java
identity/src/main/java/com/android/identity/credential/NameSpacedData.java
identity/src/main/java/com/android/identity/internal/Util.java
identity/src/test/java/com/android/identity/credential/CredentialStoreTest.java
identity/src/test/java/com/android/identity/credential/CredentialUtilTest.java
identity/src/test/java/com/android/identity/credential/NameSpacedDataTest.java

This adds a new credential store, replacing IdentityCredentialStore.
The new credential store is built on top of StorageEngine and KeystoreEngine introduced in previous commits and as such can work in non-Android environments. Additionally, the credential store is generic in the sense that it is not tied to ISO/IEC 18013-5:2021 at all, it can work for any credential shape, regardless of data-model, presentation-protocol, or issuance-protocol.
A future commit will add ways to use this new credential store for 18013-5 presentations and also migrate credentials from IdentityCredentialStore, preserving key material and PII previously issued.
Test: New unit test and all unit tests pass.

Add new credential store.

---

identity-android/src/androidTest/java/com/android/identity/android/mdoc/engagement/NfcEnagementHelperTest.java

Forgot to update the unit tests when landing the changes to NFC negotiated handover in
https://github.com/google/identity-credential/commit/c4f18ecd03958974fa72fb2ac435a84276e07cdd

Fix up NFC negotiated handover unit tests.

---

identity-android/src/main/java/com/android/identity/android/legacy/Utility.java
identity/src/main/java/com/android/identity/mdoc/mso/StaticAuthDataGenerator.java
identity/src/main/java/com/android/identity/mdoc/mso/StaticAuthDataParser.java
identity/src/main/java/com/android/identity/mdoc/response/DeviceResponseGenerator.java
identity/src/test/java/com/android/identity/mdoc/mso/StaticAuthDataTest.java

When replacing parsing code in Utility.java with StaticAuthDataParser, the API spec was changed to return IssuerSignedItemMetadataBytes instead of IssuerSignedItemMetadata (ie. the unwrapped tag-24 data), but the parsing code was not updated. This updates the parsing routine, tester, and any dependencies of StaticAuthDataParser.
All tests pass.

Ensuring StaticAuthDataParser meets API spec

---

identity-android/src/main/java/com/android/identity/android/mdoc/deviceretrieval/DeviceRetrievalHelper.java
identity/src/main/java/com/android/identity/internal/Util.java

If the verifier sends a malformed EReaderKey send back an appropriate error code (10 or 11) instead of throwing an exception and letting the application deal with it.
Fixes Issue #115 and Issue #330.

DeviceRetrievalHelper: Gracefully handle malformed EReaderKey.

---

identity/src/test/java/com/android/identity/internal/UtilTest.java

Change the curve of the EC key used in unit tests from `secp256k1` to NIST P-256 `secp256r1` as it is no longer supported in current Java versions.
Fixes #334.

Fix Java 17 compatibility

---

identity/build.gradle
identity/src/test/java/com/android/identity/TestUtilities.java
identity/src/test/java/com/android/identity/internal/UtilTest.java
identity/src/test/java/com/android/identity/keystore/BouncyCastleKeystoreTest.java
identity/src/test/java/com/android/identity/mdoc/request/DeviceRequestParserTest.java
identity/src/test/java/com/android/identity/mdoc/sessionencryption/SessionEncryptionTest.java

Apparently the `secp256k1` curve wasn't the only thing that was removed from later versions of Java, as fixed in #335. The brainpool curves are no longer usable either. Unfortunately the Security subsystem is not able to fallback to different provider when the default provider is unable to provide these curves. Therefore use the BouncyCastle provider as the default provider in unit tests to provide them. Update BouncyCastle to 1.69 because there appears to be a compatibility issue with the previous version and `BouncyCastleKeystoreTest.testEcKeySigningWithLockedKey()`.
Fixes #337.

Fix remaining unit tests in Java 17

---

appholder/src/main/java/com/android/mdl/app/transfer/QrCommunicationSetup.kt
appholder/src/main/java/com/android/mdl/app/transfer/ReverseQrCommunicationSetup.kt
appholder/src/main/java/com/android/mdl/app/util/NfcEngagementHandler.kt
identity-android/src/androidTest/java/com/android/identity/android/legacy/DynamicAuthTest.java
identity-android/src/androidTest/java/com/android/identity/android/legacy/MultiDocumentPresentationTest.java
identity-android/src/androidTest/java/com/android/identity/android/legacy/ProvisioningTest.java
identity-android/src/androidTest/java/com/android/identity/android/mdoc/deviceretrieval/DeviceRetrievalHelperTest.java
identity-android/src/androidTest/java/com/android/identity/android/mdoc/engagement/NfcEnagementHelperTest.java
identity-android/src/androidTest/java/com/android/identity/mdoc/response/DeviceResponseGeneratorOnAndroidTest.java
identity-android/src/main/java/com/android/identity/android/legacy/Utility.java
identity-android/src/main/java/com/android/identity/android/mdoc/deviceretrieval/DeviceRetrievalHelper.java
identity-android/src/main/java/com/android/identity/android/mdoc/deviceretrieval/VerificationHelper.java
identity-android/src/main/java/com/android/identity/android/mdoc/engagement/NfcEngagementHelper.java
identity-android/src/main/java/com/android/identity/android/mdoc/engagement/QrEngagementHelper.java
identity/src/main/java/com/android/identity/internal/Util.java
identity/src/main/java/com/android/identity/util/Constants.java
identity/src/test/java/com/android/identity/TestUtilities.java
identity/src/test/java/com/android/identity/mdoc/sessionencryption/SessionEncryptionTest.java

With PresentationSession now in the 'legacy' package it would be helpful if an application could just pass a KeyPair and PublicKey which can be used for mdoc session authentication.
Also remove EC Curve constants from Constants class since these are already available in KeystoreEngine interface

Make PresentationSession optional.

---

identity/src/main/java/com/android/identity/credential/Credential.java
identity/src/main/java/com/android/identity/credential/CredentialUtil.java
identity/src/main/java/com/android/identity/internal/Util.java
identity/src/main/java/com/android/identity/util/ApplicationData.java
identity/src/main/java/com/android/identity/util/SimpleApplicationData.java
identity/src/test/java/com/android/identity/credential/CredentialStoreTest.java
identity/src/test/java/com/android/identity/credential/CredentialUtilTest.java
identity/src/test/java/com/android/identity/internal/UtilTest.java
identity/src/test/java/com/android/identity/util/SimpleApplicationDataTest.java

Created an ApplicationData interface and basic implementation (SimpleApplicationData) to reduce copied code related to application data between Credential, Credential.PendingAuthKey, and Credential.AuthenticationKey classes and increase modularity. Introduced the ability to save additional types (long, Timestamp, Boolean) to the ApplicationData. Tested using SimpleApplicationDataTest and slight modifications to CredentialStoreTest.
Fixes #324 
- [x ] Tests pass

Introduce ApplicationData interface

---

identity/src/test/java/com/android/identity/internal/UtilTest.java

Addressed the to-do comment in UtilTest to replace assertThrows function with Assert.assertThrows.
Fixes #343

Replace UtilTest#assertThrows with Assert.assertThrows

---

identity/src/main/java/com/android/identity/util/SimpleApplicationData.java
identity/src/test/java/com/android/identity/util/SimpleApplicationDataTest.java

Test: New unit test and all unit tests pass.

SimpleApplicationData: Don't call listener during construction.

---

appholder/src/main/java/com/android/mdl/app/transfer/QrCommunicationSetup.kt
identity-android/src/androidTest/java/com/android/identity/android/credential/AndroidKeystoreSecureAreaCredentialStoreTest.java
identity-android/src/androidTest/java/com/android/identity/android/mdoc/deviceretrieval/DeviceRetrievalHelperTest.java
identity-android/src/androidTest/java/com/android/identity/android/securearea/AndroidKeystoreSecureAreaTest.java
identity-android/src/main/java/com/android/identity/android/mdoc/deviceretrieval/DeviceRetrievalHelper.java
identity-android/src/main/java/com/android/identity/android/mdoc/deviceretrieval/VerificationHelper.java
identity-android/src/main/java/com/android/identity/android/securearea/AndroidKeystoreSecureArea.java
identity/src/main/java/com/android/identity/credential/Credential.java
identity/src/main/java/com/android/identity/credential/CredentialStore.java
identity/src/main/java/com/android/identity/credential/CredentialUtil.java
identity/src/main/java/com/android/identity/internal/Util.java
identity/src/main/java/com/android/identity/mdoc/response/DocumentGenerator.java
identity/src/main/java/com/android/identity/securearea/BouncyCastleSecureArea.java
identity/src/main/java/com/android/identity/securearea/SecureArea.java
identity/src/main/java/com/android/identity/securearea/SecureAreaRepository.java
identity/src/test/java/com/android/identity/credential/CredentialStoreTest.java
identity/src/test/java/com/android/identity/credential/CredentialUtilTest.java
identity/src/test/java/com/android/identity/mdoc/response/DeviceResponseGeneratorTest.java
identity/src/test/java/com/android/identity/mdoc/sessionencryption/SessionEncryptionTest.java
identity/src/test/java/com/android/identity/securearea/BouncyCastleSecureAreaTest.java
testapp/src/main/java/com/android/identity/testapp/MainActivity.kt

It's likely we want to add features implemented in the secure area in the future that are specific to real-world identity credentials in addition to symmetric and asymmetric keys that are guaranteed to never leave the secure area. For example, this could include keys and objects needed for ZKP and storage of credential data.
Also add a feature to the Android Keystore implementation of SecureArea to allow specifying whether LSKF, biometric, or both can be used to unlock the key. Make a note in the docs that this only works with API 30 or later.
Also fix a bug in DeviceRetrievalHelperTest.
Test: Manually tested with holder and reader.

Rename KeystoreEngine to SecureArea.

---

appverifier/src/main/java/com/android/mdl/appreader/fragment/ShowDocumentFragment.kt

Replaced search for "O=" with "CN=" since the intended behavior is to show the common name of the issuer as opposed to the organization name.
Tested manually.
Fixes #369

Ensure appverifier shows common name

---

appholder/src/main/java/com/android/mdl/app/adapter/DocumentAdapter.kt
appholder/src/main/java/com/android/mdl/app/authconfirmation/AuthConfirmationFragment.kt
appholder/src/main/java/com/android/mdl/app/authconfirmation/RequestedDocumentData.kt
appholder/src/main/java/com/android/mdl/app/authconfirmation/SignedDocumentData.kt
appholder/src/main/java/com/android/mdl/app/authconfirmation/SignedElementsCollection.kt
appholder/src/main/java/com/android/mdl/app/composables/Preview.kt
appholder/src/main/java/com/android/mdl/app/document/DocumentInformation.kt
appholder/src/main/java/com/android/mdl/app/document/DocumentManager.kt
appholder/src/main/java/com/android/mdl/app/documentinfo/DocumentInfoScreen.kt
appholder/src/main/java/com/android/mdl/app/documentinfo/DocumentInfoScreenState.kt
appholder/src/main/java/com/android/mdl/app/documentinfo/DocumentInfoViewModel.kt
appholder/src/main/java/com/android/mdl/app/fragment/DocumentDetailFragment.kt
appholder/src/main/java/com/android/mdl/app/selfsigned/AddSelfSignedDocumentScreen.kt
appholder/src/main/java/com/android/mdl/app/selfsigned/AddSelfSignedFragment.kt
appholder/src/main/java/com/android/mdl/app/selfsigned/AddSelfSignedScreenState.kt
appholder/src/main/java/com/android/mdl/app/selfsigned/AddSelfSignedViewModel.kt
appholder/src/main/java/com/android/mdl/app/selfsigned/SelfSignedDocumentData.kt
appholder/src/main/java/com/android/mdl/app/transfer/AddDocumentToResponseResult.kt
appholder/src/main/java/com/android/mdl/app/transfer/TransferManager.kt
appholder/src/main/java/com/android/mdl/app/util/ProvisioningUtil.kt
appholder/src/main/java/com/android/mdl/app/viewmodel/TransferDocumentViewModel.kt
appholder/src/main/res/values/strings.xml
appholder/src/test/java/com/android/mdl/app/selfsigned/SelfSignedScreenStateTest.kt
identity-android/src/main/java/com/android/identity/android/securearea/KeystoreUtil.kt

AndroidSecureArea keys creation improvements

---

identity-android/src/androidTest/java/com/android/identity/android/legacy/MigrateFromKeystoreICStoreTest.java
identity-android/src/main/java/com/android/identity/android/legacy/CredentialData.java
identity-android/src/main/java/com/android/identity/android/legacy/KeystoreIdentityCredential.java
identity-android/src/main/java/com/android/identity/android/legacy/Utility.java
identity-android/src/main/java/com/android/identity/android/securearea/AndroidKeystoreSecureArea.java
identity/src/main/java/com/android/identity/credential/Credential.java
identity/src/main/java/com/android/identity/credential/CredentialStore.java

Added a function to the KeystoreIdentityCredential class that creates a new Credential (identity/src/main/java/com/android/identity/credential/Credential.java) using the information in the given KeystoreIdentityCredential and deletes the KeystoreIdentityCredential once the new Credential is created. This change required additional functions in the Credential, CredentialStore, and AndroidKeystore classes which allow Credential creation with an existing key so the credential key from the KeystoreIdentityCredential could be preserved. A function in Utility.java to extract key settings from an existing key as well as a function in CredentialData.java to delete credential information while preserving the key were also added to aid in this process.
Tested in MigrateFromKeystoreICStoreTest. …

Add Migrate Function For KeystoreIdentityCredential

---

README.md
appholder/src/main/res/navigation/navigation_graph.xml
appholder/src/main/res/values/strings.xml

Additional improvements for the appholder flavors labels, and updated README
| / | Purse | Wallet |
| -- | -- | -- |
| Home | ![ic_purse_home](https://github.com/google/identity-credential/assets/1390865/41a3d7a6-b7d6-41d0-af6d-0541ca5e5a25) | ![ic_wallet_home](https://github.com/google/identity-credential/assets/1390865/ae7befae-fb05-4150-91b3-1383891f96e9) |
| NFC Engage | ![chooser](https://github.com/google/identity-credential/assets/1390865/1047f72c-71bf-4a4f-a2a9-7ad778252898) | ![chooser](https://github.com/google/identity-credential/assets/1390865/1047f72c-71bf-4a4f-a2a9-7ad778252898) |

Improve the labels of the flavors, update the README

---

identity-android/src/main/java/com/android/identity/android/mdoc/transport/GattClient.java

This would cause issues on some readers with some devices. Left previous connection open and was prone to further unexpected communications.

Close BluetoothGatt after disconnect.

---

identity-android/build.gradle
identity/build.gradle
publish-helper.gradle

Added publish-helper.gradle for use by identity/build.gradle and identity-android/build.gradle so that publishing will generate the appropriate files for only those two modules.
Tested manually.
Fixes #299

Modify gradle files for publication of identity and identity-android

---

appholder/src/main/java/com/android/identity/wallet/MainActivity.kt
appholder/src/main/java/com/android/identity/wallet/settings/SettingsFragment.kt
appholder/src/main/java/com/android/identity/wallet/settings/SettingsScreen.kt
appholder/src/main/java/com/android/identity/wallet/settings/SettingsScreenState.kt
appholder/src/main/java/com/android/identity/wallet/settings/SettingsViewModel.kt
appholder/src/main/java/com/android/identity/wallet/transfer/Communication.kt
appholder/src/main/java/com/android/identity/wallet/transfer/TransferManager.kt
appholder/src/main/java/com/android/identity/wallet/util/PreferencesHelper.kt
appverifier/src/main/java/com/android/mdl/appreader/MainActivity.kt
appverifier/src/main/java/com/android/mdl/appreader/VerifierApp.kt
appverifier/src/main/java/com/android/mdl/appreader/fragment/ShowDocumentFragment.kt
appverifier/src/main/java/com/android/mdl/appreader/settings/UserPreferences.kt
appverifier/src/main/java/com/android/mdl/appreader/transfer/TransferManager.kt
identity-android/src/main/java/com/android/identity/android/mdoc/deviceretrieval/DeviceRetrievalHelper.java
identity-android/src/main/java/com/android/identity/android/mdoc/deviceretrieval/VerificationHelper.java
identity/src/main/java/com/android/identity/internal/Util.java
identity/src/main/java/com/android/identity/mdoc/sessionencryption/SessionEncryption.java
identity/src/main/java/com/android/identity/util/Constants.java
identity/src/test/java/com/android/identity/internal/UtilTest.java
identity/src/test/java/com/android/identity/mdoc/sessionencryption/SessionEncryptionTest.java

Change from "Ephemeral Key Curve" to "Session Encryption Curve" in preferences since that's more accurate.
Also show which mdoc Session Encryption curve was used in the reader.
Fix "Show debugging logs" buttons in both wallet and reader app (currently a no-op).
Add new unit tests for COSE_Key encode and decode.
Also fix mdoc MAC authentication to make it use the reader public key.
Test: New unit tests + all unit tests pass.
Test: Manually tested all nine curves with 18013-5 presentations.

Make mdoc Session Encryption work with all nine KA curves.

---

identity/src/main/java/com/android/identity/mdoc/engagement/EngagementParser.java
identity/src/main/java/com/android/identity/mdoc/origininfo/OriginInfoBaseUrl.java
identity/src/main/java/com/android/identity/mdoc/origininfo/OriginInfoReferrerUrl.java
wwwverifier/build.gradle
wwwverifier/src/main/java/com/android/identity/wwwreader/RequestServlet.java
wwwverifier/src/main/java/com/android/identity/wwwreader/ServletConsts.java
wwwverifier/src/main/webapp/index.html
wwwverifier/src/main/webapp/script.js
wwwverifier/src/main/webapp/style.css
wwwverifier/src/test/java/com/android/identity/wwwreader/RequestServletTest.java

Added the ability to chose between request scenarios, as well as required checks + associated logging. Also added the ability to render the returned portrait image.
Manually tested.
Fixes #358

Incorporate Interoperability Event Features to wwwverifier

---

appholder/src/main/java/com/android/identity/wallet/HolderApp.kt
appholder/src/main/java/com/android/identity/wallet/authconfirmation/AuthConfirmationFragment.kt
appholder/src/main/java/com/android/identity/wallet/util/ProvisioningUtil.kt
appverifier/src/main/java/com/android/mdl/appreader/VerifierApp.kt
appverifier/src/main/java/com/android/mdl/appreader/fragment/ShowDocumentFragment.kt
appverifier/src/main/java/com/android/mdl/appreader/readercertgen/CertificateGenerator.java
gradle/libs.versions.toml
identity/src/main/java/com/android/identity/securearea/AttestationExtension.kt
identity/src/main/java/com/android/identity/securearea/SecureArea.java
identity/src/main/java/com/android/identity/securearea/SoftwareSecureArea.java
identity/src/test/java/com/android/identity/credential/CredentialStoreTest.java
identity/src/test/java/com/android/identity/credential/CredentialUtilTest.java
identity/src/test/java/com/android/identity/mdoc/response/DeviceResponseGeneratorTest.java
identity/src/test/java/com/android/identity/securearea/SoftwareSecureAreaTest.java

First of all, rename this to SoftwareSecureArea since there is no need to leak the fact that we're currently using BouncyCastle which could change in the future.
Instead of always using self-signed keys, make it possible to specify the attestation key to use at key creation time. Without this we cannot easily support curves which cannot be used for signing (for example X25519). Modify holder app to create an attestation root on demand.
Introduce attestation extension so SoftwareSecureArea keys also can convey the attestation challenge. The OID for this has been reserved (it's 1.3.6.1.4.1.11129.2.1.39) and we can extend this if needed. Add code for dealing with this and use it in SoftwareSecureArea.
Show the curve of DeviceKey in the reader app.
Make sure we use the BouncyCastle library …

Rework BouncyCastleSecureArea.

---

identity-android/src/main/java/com/android/identity/android/securearea/AndroidKeystoreSecureArea.java
secure-area-test-app/src/main/java/com/android/identity/secure_area_test_app/MainActivity.kt

Android devices shipping with versions before Android 12 are not required to set their KeyMint version number in the properties android.hardware.hardware_keystore and android.hardware.strongbox_keystore. Add code to work around this.
In the Secure Area Test App, show name for API level and also show the First API Level and its name (the First API level is the API level the device shipped with).
Also add code to work around Android Keystore creating software-backed keys if its Keymint version does not support the requested features.
Test: Manually tested on Pixels 4XL, 4a, 7a, 7 Pro, 8 Pro.

Fixes for Android Keystore Capabilities on older Android devices.

---

identity-android/src/main/java/com/android/identity/android/securearea/AndroidKeystoreSecureArea.java

The current text assumes the failure has to do with key purpose, but this is not the case and we're actively running into this error message in the context of brokenness in Android Keystore wrt. Ed25519 and X25519 support. With this fix, it's clear what the error is.
Test: Manually test.

Clarify error messages in Android Keystore Secure Area.

---

appholder/src/main/java/com/android/identity/wallet/util/ProvisioningUtil.kt
identity-android/src/androidTest/java/com/android/identity/android/legacy/MigrateFromKeystoreICStoreTest.java
identity/src/main/java/com/android/identity/credential/Credential.java
identity/src/main/java/com/android/identity/mdoc/mso/StaticAuthDataGenerator.java
identity/src/main/java/com/android/identity/mdoc/mso/StaticAuthDataParser.java
identity/src/main/java/com/android/identity/mdoc/util/MdocUtil.java
identity/src/test/java/com/android/identity/credential/CredentialStoreTest.java
identity/src/test/java/com/android/identity/mdoc/mso/StaticAuthDataTest.java
identity/src/test/java/com/android/identity/mdoc/response/DeviceResponseGeneratorTest.java
identity/src/test/java/com/android/identity/mdoc/util/MdocUtilTest.java

Our current model involves sending all PII to the device and then a bunch of MSOs + associated data (StaticAuthData) where the latter doesn't include any PII at all. Add the ability for StaticAuthData to also include PII meaning the issuer has the option to send none, some, or all PII along with each MSO.
Also use this in appholder by embedding the string "MSO <counter>" on top of the portrait image where <counter> is the count of the MSO and increasing for every use. In this example, only the portrait data element is per-MSO.
Fixes #405.

Add support for per-MSO data elements.

---

appholder/src/main/java/com/android/identity/wallet/util/PreferencesHelper.kt
appholder/src/main/java/com/android/identity/wallet/util/ProvisioningUtil.kt
identity-android/src/androidTest/java/com/android/identity/android/credential/AndroidKeystoreSecureAreaCredentialStoreTest.java
identity-android/src/androidTest/java/com/android/identity/android/legacy/MigrateFromKeystoreICStoreTest.java
identity-android/src/androidTest/java/com/android/identity/android/securearea/AndroidKeystoreSecureAreaTest.java
identity-android/src/main/java/com/android/identity/android/legacy/KeystoreIdentityCredential.java
identity-android/src/main/java/com/android/identity/android/securearea/AndroidKeystoreSecureArea.java
identity/src/main/java/com/android/identity/credential/Credential.java
identity/src/main/java/com/android/identity/credential/CredentialStore.java
identity/src/main/java/com/android/identity/credential/CredentialUtil.java
identity/src/main/java/com/android/identity/securearea/SecureArea.java
identity/src/main/java/com/android/identity/securearea/SecureAreaRepository.java
identity/src/main/java/com/android/identity/securearea/SoftwareSecureArea.java
identity/src/test/java/com/android/identity/credential/CredentialStoreTest.java
identity/src/test/java/com/android/identity/credential/CredentialUtilTest.java
identity/src/test/java/com/android/identity/mdoc/response/DeviceResponseGeneratorTest.java
identity/src/test/java/com/android/identity/securearea/SoftwareSecureAreaTest.java

In order to support new kinds of SecureArea without app changes, change the SecureArea.CreateKeySettings class so it can be instantiated by apps.
Also stop carrying the SecureArea class name in CreateKeySettings subclasses, instead have users of CreateKeySettings take a separate SecureArea class. Make it explicit that different SecureArea instances can be used by CredentialKey and even for different Authentication Keys.
Introduce the concept of an "identifier" for a SecureArea instead of Credential, Credential.Authentiationkey, and
Credential.PendingAuthenticationKey classes all using the Java class name when persisting on-disk. This paves the way to have multiple SecureArea instances of the same type but with different configuration. We'll need this for CloudSecureArea so an app can have …

Allow instantiating SecureArea.CreateKeySettings object.

---

README.md

Update the documentation link (GitHub pages). While a redirection on the repository level (https://github.com/google/identity-credential/) is already in place this is not the case for the documentation link: 
* https://google.github.io/identity-credential/
The new place for the documentation is: 
* https://openwallet-foundation-labs.github.io/identity-credential/
Fixes #425

Update Documentation link in README.md

---

appholder/src/main/java/com/android/identity/wallet/util/PreferencesHelper.kt
identity-android/src/main/java/com/android/identity/android/mdoc/deviceretrieval/DeviceRetrievalHelper.java
identity-android/src/main/java/com/android/identity/android/mdoc/engagement/NfcEngagementHelper.java
identity-android/src/main/java/com/android/identity/android/mdoc/engagement/QrEngagementHelper.java
identity-android/src/main/java/com/android/identity/android/mdoc/transport/DataTransport.java

Make the wallet app default to NFC Negotiated Handover and close the connection after sending the response. This change is to more closely mimic wallets already in production using this code.
Also add additional checks for callback inhibition when inside the executor to avoid transport callbacks after closing a connection. This happened in the reader app - causing a crash - when the mDL included status 20 in the same SessionData message which contained the result (e.g. using auto-close).

Change wallet defaults and fix race condition.

---

appverifier/src/main/java/com/android/mdl/appreader/fragment/ShowDocumentFragment.kt
appverifier/src/main/java/com/android/mdl/appreader/transfer/TransferManager.kt
identity-android/src/main/java/com/android/identity/android/mdoc/deviceretrieval/VerificationHelper.java

This shows how a transaction takes, from the reader's perspective. We show both the total and also broken down in various phases.

Reader: Show transaction times.

---

wallet/src/main/AndroidManifest.xml
wallet/src/main/java/com/android/identity_credential/wallet/CredentialInformationViewModel.kt
wallet/src/main/java/com/android/identity_credential/wallet/MainActivity.kt
wallet/src/main/java/com/android/identity_credential/wallet/NfcEngagementHandler.kt
wallet/src/main/java/com/android/identity_credential/wallet/PermissionTracker.kt
wallet/src/main/java/com/android/identity_credential/wallet/PresentationActivity.kt
wallet/src/main/java/com/android/identity_credential/wallet/WalletApplication.kt
wallet/src/main/java/com/android/identity_credential/wallet/commonUI.kt
wallet/src/main/res/values/strings.xml
wallet/src/main/res/xml/nfc_engagement_apdu_service.xml

Adding PresentationActivity to wallet, which will appear on-screen with related presentation UI once the NfcEngagementHandler starts the activity. This addition allows for in-person presentation with NFC engagement.
Tested manually with 0/1/2 active credentials in wallet.

Presentation Activity in Wallet

---

samples/simple-verifier/build.gradle
samples/simple-verifier/src/main/java/com/example/simple_verifier/MdocReaderPrompt.kt

Updated simple-verifier's build.gradle to use tip-of-tree identity libraries rather than published libraries, which also involved updating the code to work with the library changes.
Tested both NFC and QR engagement manually against appholder.

Use tip-of-tree identity libraries

---

wallet/build.gradle
wallet/src/main/java/com/android/identity_credential/wallet/MainActivity.kt
wallet/src/main/java/com/android/identity_credential/wallet/PresentationActivity.kt
wallet/src/main/java/com/android/identity_credential/wallet/QrEngagementViewModel.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/CommonUI.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/QrEngagementScreen.kt

Adds a button on-screen when there is at least one credential in the wallet which will shows a QR code that can be used for engagement. Also moves pure composables to ui/
Tested manually with 0/1/2 credentials in wallet against appverifier.

QR Engagement

---

identity/src/main/java/com/android/identity/crypto/EcCurve.kt

These identifiers were added to
https://www.iana.org/assignments/cose/cose.xhtml#elliptic-curves
a while ago. This fixes issue #454.
Fixes #454 and obsoletes PR #457.

Fix Brainpool curve identifiers.

---

wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/credential/CredentialInfoScreen.kt

This screen had pending and non-pending auth keys mixed up.

Credential Information: Show the correct number of pending auth keys and auth keys.

---

wallet/src/main/java/com/android/identity/issuance/simple/SimpleIssuingAuthorityProofingGraph.kt
wallet/src/main/java/com/android/identity_credential/wallet/PassportBasedIssuingAuthority.kt
wallet/src/main/java/com/android/identity_credential/wallet/SelfCertificationIssuingAuthority.kt
wallet/src/main/java/com/android/identity_credential/wallet/SelfSignedMdlIssuingAuthority.kt
wallet/src/main/java/com/android/identity_credential/wallet/WalletApplication.kt
wallet/src/main/res/values/strings.xml

Split passport-based and self-certifying issuers apart. Also only use tunnel-based workflow to read MRTD (so that we can do chip/active authentication). This simplifies the evidence-gathering workflow.
Still to do: wordsmith the messages (and localize them if wanted?)

Split self-signed issuing authority in two

---

wallet/src/main/java/com/android/identity/issuance/CredentialExtensions.kt
wallet/src/main/java/com/android/identity_credential/wallet/BiometricUserAuthPrompt.kt
wallet/src/main/java/com/android/identity_credential/wallet/MainActivity.kt
wallet/src/main/java/com/android/identity_credential/wallet/PresentationActivity.kt
wallet/src/main/java/com/android/identity_credential/wallet/presentation/TransferHelper.kt
wallet/src/main/res/values/strings.xml

Adds BiometricUserAuthPrompt and integrates into PresentationActivity such that any KeyLocked exceptions thrown during presentation can be caught and handled. BiometricUserAuthPrompt can support both LSKF and biometric unlocking - while it prefer biometric when both are available, LSKF is integrated into the prompt behavior as a fallback. Additionally, authkeys for credentials in AndroidSecureArea now require user authentication with timeout 0sec by default.
Tested manually with authkeys which require user authentication with allowed auth types of (LSKF + Biometric), (LSKF only), and (Biometric only) respectively. Also tested the cancellation + LSKF fallback cases.

Biometric Prompt in Wallet

---

identity/src/main/java/com/android/identity/credential/CredentialUtil.kt
wallet/src/main/java/com/android/identity/issuance/CredentialExtensions.kt
wallet/src/main/java/com/android/identity_credential/wallet/CardViewModel.kt
wallet/src/main/java/com/android/identity_credential/wallet/SelfSignedMdlIssuingAuthority.kt
wallet/src/main/java/com/android/identity_credential/wallet/presentation/TransferHelper.kt
wallet/src/main/res/values/plurals.xml
wallet/src/main/res/values/strings.xml

At provisioning the issuer sends out multiple "the credential has changed" updates which we process in separate threads from CardViewModel by running Credential.housekeeping() to call back into the issuer and run the issuance flow. Fix this race by seralizing these housekeeping() calls. Add a note that in the future we might want to do this more elegantly through e.g. a channel.
Fix a bug in where we forgot to increase the use-count at presentation time. Also show a Toast if the auth-key being used has previously been used.
If forcibly refreshing a credential, show a toast conveying how many authentication keys were refreshed.
Fix a bug in CredentialUtil.managedAuthenticationKeyHelper() where we miscounted the number of pending authentication keys on a dry run. …

Fix race when receiving an issuer update notification.

---

wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/consentprompt/ConsentPrompt.kt

Made the background color of the consent prompt surface so that the text could be onSurface and therefore Material You compliant as well as consistently readable.
Fixes #521 
Tested manually with both light and dark themes.

Adjusted Consent Prompt Colors

---

wallet/src/main/java/com/android/identity_credential/wallet/BiometricUserAuthPrompt.kt
wallet/src/main/java/com/android/identity_credential/wallet/PresentationActivity.kt
wallet/src/main/res/values/strings.xml

Modified showBiometricPrompt to take in a subtitle and updated the strings passed by PresentationActivity to be more informative.
Tested manually.

Change Biometric Prompt Title/Subtitle in Presentation Activity

---

appholder/src/main/java/com/android/identity/wallet/document/DocumentManager.kt
appverifier/build.gradle
appverifier/src/main/java/com/android/mdl/appreader/fragment/ShowDocumentFragment.kt
identity/src/main/java/com/android/identity/cbor/Cbor.kt
identity/src/main/java/com/android/identity/cbor/DataItemExtensions.kt
identity/src/main/java/com/android/identity/cbor/DiagnosticOption.kt
identity/src/main/java/com/android/identity/credentialtype/MdocDataElement.kt
identity/src/test/java/com/android/identity/credentialtype/TestCredentialTypeRepository.kt

This takes the type of the value into account as per the CredentialTypeRepository and supports enumerations used for that particular DocType. For example, for in the AAMVA namespace instead of rendering "1" for data element `organ_donor`, it will render "Donor". Similarly, instead of rendering "AP" for data element `race_ethnicity` it will render "Asian or Pacific Islander".
Use this in appverifier to display the retrieved document and test with retrieving "Full mDL" from appholder to manually verify it's correct. This uncovered a bug in appholder where data elements for numbers were accidentially encoded as strings. Fix this.
This code will be used to render the values for the Credman credential picker which has "View details" button to see the value of the data elements which will be …

Add method MdocDataElement.renderValue() to nicely render values.

---

appholder/src/main/java/com/android/identity/wallet/document/KeysAndCertificates.kt

Adjusted get{Public/Private}Key functions to enforce returned keys use BouncyCastle as provider.
Fixes #528
Tested manually.

Force appholder to use BouncyCastle

---

wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/consentprompt/ConsentPrompt.kt

Fixes issue https://github.com/openwallet-foundation-labs/identity-credential/issues/543 where if there are a large number of credential data requested now they are in a scrollable list with the bottom action buttons visible.
https://github.com/openwallet-foundation-labs/identity-credential/assets/1477025/98e3fb8d-36c9-44c1-9450-0f26ea979348
Tested manually for sharing of documents between Wallet and Verifier apps.

Fix for Consent Prompt showing a scrollable list of credentials to approve, resolving issue 543

---

wallet/src/main/java/com/android/identity_credential/wallet/BiometricUserAuthPrompt.kt

In the case of no enrolled biometrics, allow users with secure lock screen to use LSKF only to unlock auth keys. Also improves user experience by allowing for a retry when the biometrics are not clear (ie, when the prompt tells you to press your finger firmly against the sensor) - before, the presentation would be cancelled after a single failure but the prompt would remain on-screen.
Tested manually as a user with only PIN and no biometrics and when pressing finger lightly enough to need a retry.
Fixes #550

Support more error types in BiometricPrompt

---

cbor-processor/src/main/kotlin/com/android/identity/cbor/processor/CborSymbolProcessor.kt
cbor-processor/src/main/kotlin/com/android/identity/cbor/processor/CodeBuilder.kt
identity/src/main/java/com/android/identity/cbor/DataItem.kt
identity/src/test/java/com/android/identity/processor/ProcessorTests.kt
wallet/src/main/java/com/android/identity/issuance/evidence/EvidenceRequest.kt
wallet/src/main/java/com/android/identity/issuance/evidence/EvidenceResponse.kt

- named serializer/deserializer to be consistent with the CBOR library, toDataItem is now a property
- add correct import statement for classes that supply their own serializers
- support for Float, Double, Instant, and LocalDate
Updated the (currently minimalistic) unit text
Fixes #541 - need to understand better what (if anything) would need to be done for EcPublicKey and friends. It seems that generic toDataItem/fromDataItem should work fine.

Tweaks to CBOR annotation processor:

---

wallet/src/main/java/com/android/identity_credential/wallet/navigation/WalletNavigation.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/main/MainScreen.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/qrengagement/QrEngagementScreen.kt
wallet/src/main/res/values/strings.xml

Both provisioning and presenting a credential in wallet require a secure lockscreen (ie. the user has set a pin/pattern/password). In order to improve UX when a user does not have one set, the PR adds a dialog to warn the users when functionality is blocked. 
Fixes #534

Add Warning for Users Without Secure Lock Screen

---

wallet/src/main/java/com/android/identity_credential/wallet/PermissionTracker.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/main/MainScreen.kt
wallet/src/main/res/values/strings.xml

Request all the permissions that are needed, not one-by-one. On Pixel this means that there is only a single button to push and a single system dialog to confirm (in theory other OS may display multiple dialogs - but that's highly unlikely). This PR also rearranges buttons on the main screen permission request snackbar, so that they are in a single row.
Fixes #555

Request all the permissions that are needed, not one-by-one.

---

wallet/src/main/java/com/android/identity_credential/wallet/NfcEngagementHandler.kt
wallet/src/main/java/com/android/identity_credential/wallet/SettingsModel.kt
wallet/src/main/java/com/android/identity_credential/wallet/WalletApplication.kt
wallet/src/main/java/com/android/identity_credential/wallet/navigation/WalletNavigation.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/main/MainScreen.kt
wallet/src/main/res/values/strings.xml

This changes how we handle requesting proximity permissions.
Introduce a snackbar in MainScreen shown if there's at least one credential and we lack the BLE permissions to present it. Make the Action button request the permission and also allow the user to dismiss this. Record whether the snackbar was dismissed to avoid painting it in the future, via SharedPreference.
Add logic to check for permissions if "Show code" button is pressed (for QR presentations) and if we lack permissions, show an Alert dialog explaining that permissions need to be granted.
Add logic in `NfcEngagementHandler` to clear the preference for whether to hide the snackbar and post a notification (best effort) explaining to the user that they need to grant permissions. The user clicking the notification will take them …

wallet: better handling of permissions related to proximitiy presentations.

---

appverifier/build.gradle
appverifier/src/main/java/com/android/mdl/appreader/fragment/ShowDocumentFragment.kt
gradle/libs.versions.toml
jpeg2k/build.gradle
jpeg2k/src/main/java/com/android/identity/jpeg2k/Jpeg2kConverter.kt
mrtd-reader/build.gradle
mrtd-reader/src/main/java/com/android/identity_credential/mrtd/MrtdDecodedData.kt
mrtd-reader/src/main/java/com/android/identity_credential/mrtd/MrtdNfcDataDecoder.kt
wallet/build.gradle
wallet/src/main/java/com/android/identity_credential/wallet/DocumentDetails.kt
wallet/src/main/java/com/android/identity_credential/wallet/SelfSignedEuPidIssuingAuthority.kt
wallet/src/main/java/com/android/identity_credential/wallet/SelfSignedMdlIssuingAuthority.kt
wallet/src/main/java/com/android/identity_credential/wallet/SelfSignedMdocIssuingAuthority.kt

Read all the data from the MRTD "DG1" data group. Also, avoid converting portrait to Android Bitmap, instead pass it as is to the Issuing Authority. Display JPEG2k correctly both in wallet and appverifier. Set date of bith along with "over 18/21" in mDoc/mDL from the MRTD data.
Fixes #565

Pass more data from passport to mDoc

---

wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/consentprompt/ConsentPrompt.kt
wallet/src/main/res/values/strings.xml

The Share button is disabled until the user scrolls to the bottom of list then it becomes enabled. Scroll-to-bottom text below the action buttons fades out.
https://github.com/openwallet-foundation-labs/identity-credential/assets/1477025/6cb2717f-cd57-4de0-baa0-3eb3712700bf
All unit tests pass and manually tested a few mDL presentations.

Refactored Consent Prompt share button to have state so its disabled or permits sharing

---

cbor-processor/src/main/kotlin/com/android/identity/cbor/annotation/CborSerializable.kt
cbor-processor/src/main/kotlin/com/android/identity/cbor/processor/CborSymbolProcessor.kt
cbor-processor/src/main/kotlin/com/android/identity/cbor/processor/CodeBuilder.kt
wallet/src/main/java/com/android/identity/issuance/evidence/EvidenceRequestCreatePassphrase.kt
wallet/src/main/java/com/android/identity/issuance/simple/SimpleIssuingAuthorityProofingGraph.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/provisioncredential/EvidenceRequest.kt

Added imports for generated serializer/deserializer functions.
Fixes #575

Fixes for cbor annotation processor.

---

.scripts/install-precommit-git-hook
.scripts/pre-commit.ktlint
build.gradle
gradle/libs.versions.toml
wallet/build.gradle

All project modules whose build.gradle defines the ktlint plugin dependency are included when linting. The current implementation applies the ktlint plugin to all modules in the project from the root build.gradle. It is thus easy to disable linting (for development) by commenting out 1 line of code.
[Gradle tasks](https://github.com/jlleitschuh/ktlint-gradle?tab=readme-ov-file#main-tasks) such as ktlintFormat, ktlintCheck are added.
The standard set of rules (pinterest.github.io/ktlint/0.49.1/rules/standard/) are run with every lint.
See [Android Code Linting](https://docs.google.com/document/d/1ThqPdQIgIusnJGslxF1f9s-Q811pDYv13VNlSoEAko8/edit?resourcekey=0-16wrXQeUGW673RVcItDw9Q&tab=t.0).
All unit tests pass. The wallet, reader, verifier apps run OK.

Adding KTLint to the project to provide a uniform coding style

---

appholder/src/main/java/com/android/identity/wallet/GetCredentialActivity.kt
appverifier/src/main/java/com/android/mdl/appreader/fragment/RequestOptionsFragment.kt
appverifier/src/main/java/com/android/mdl/appreader/fragment/ShowDeviceResponseFragment.kt
gradle/libs.versions.toml
identity-android/build.gradle
identity-android/src/main/java/com/android/identity/android/mdoc/util/CredmanUtil.kt
identity/build.gradle
identity/src/main/java/com/android/identity/crypto/Algorithm.kt
identity/src/main/java/com/android/identity/crypto/Crypto.kt
identity/src/main/java/com/android/identity/crypto/EcPublicKeyDoubleCoordinate.kt
identity/src/test/java/com/android/identity/crypto/CryptoTests.kt
wallet/src/main/java/com/android/identity_credential/wallet/credman/CredmanPresentationActivity.kt

This is based on the HPKE encryption routines in CredmanUtils. It's presently using Tink but in the future we may switch to the HPKE implementation in BC to avoid the extra dependency (or we may switch to using just Tink and not BC at all.)
Also port our Credman integration to use these new routines.
Test: Manually tested Credman presentations from appholder
and wallet to both appverifier and https://www.identitycredential.dev/

Crypto: add support for HPKE encryption and decryption.

---

appholder/src/main/java/com/android/identity/wallet/GetCredentialActivity.kt

Remove the early exit upon onAuthenticationFailed callback since it is expected to happen occasionally e.g. when a user fingerprint isn't recognized in the first few attempts. This allows the user to retry biometric prompt until it reaches the built in limit, in which case onAuthenticationError will then be invoked.

Allow device authenticaton retry.

---

appholder/src/main/java/com/android/identity/wallet/util/ProvisioningUtil.kt
identity-android/src/androidTest/java/com/android/identity/android/document/AndroidKeystoreSecureAreaDocumentStoreTest.kt
identity-android/src/androidTest/java/com/android/identity/android/mdoc/deviceretrieval/DeviceRetrievalHelperTest.kt
identity-mdoc/src/main/java/com/android/identity/mdoc/credential/MdocCredential.kt
identity-mdoc/src/test/java/com/android/identity/mdoc/response/DeviceResponseGeneratorTest.kt
identity/src/main/java/com/android/identity/credential/Credential.kt
identity/src/main/java/com/android/identity/credential/CredentialFactory.kt
identity/src/main/java/com/android/identity/credential/SecureAreaBoundCredential.kt
identity/src/main/java/com/android/identity/document/Document.kt
identity/src/main/java/com/android/identity/document/DocumentUtil.kt
identity/src/test/java/com/android/identity/document/DocumentStoreTest.kt
identity/src/test/java/com/android/identity/document/DocumentUtilTest.kt
samples/preconsent-mdl/src/main/java/com/android/identity/preconsent_mdl/MainActivity.kt
wallet/src/main/java/com/android/identity_credential/wallet/DocumentModel.kt

The previous commit which introduced a new hierarchy of Credential classes introduced a couple of small subtle bugs.
First problem was that MdocCredential.doctype wasn't read back properly. This manifested itself in an error when using the "Check for update" facility in the wallet app.
The second problem was that all SecureAreaCredential had the same alias. This is because Credential.identifier isn't assigned until it was added to the Document. This manifested itself in only a single credential being visible in the wallet app.
This PR fixes these problems.
Test: Manually tested with wallet app.

SecureAreaCredential and MdocCredential fixes.

---

identity-android/src/main/java/com/android/identity/android/mdoc/deviceretrieval/VerificationHelper.kt
identity-android/src/main/java/com/android/identity/android/mdoc/transport/DataTransportBleCentralClientMode.kt
identity-android/src/main/java/com/android/identity/android/mdoc/transport/GattServer.kt

At while ago (PR #434) we introduced the concept of warmed-up transports when using Negotiated Handover to speed up presentations. Unfortunately this introduced a bug where we didn't set the right BLEIdent on the GATT Server when using mdoc BLE central client mode. This caused a problem with some mdoc implementations which fails if the BLEIdent value isn't what they expect.
Our own mdoc implementation will only warn if the BLEIdent read from the GATT server isn't what is expects. This behavior has existed for a while but it originally used to error out. Implementations using an old version of our code thus may not currently work with our current VerificationHelper if they're using Negotiated Handover.
Fix this by setting the BLEIdent on a warmed-up connection right after receiving …

VerificationHelper: Fix BLEIdent when using Negotiated Handover.

---

identity-mdoc/src/main/java/com/android/identity/mdoc/response/DocumentGenerator.kt
identity/src/main/java/com/android/identity/cose/Cose.kt

ISO/IEC 18013-5:2021 clause 9.1.3.4 specifically said to not do that. This bug was introduced in PR #482 when switching to the new CBOR and COSE libraries. Fix this.
Also add a new check to Cose.coseSign1Check() for this. This check will trigger a unit-test failure if the fix mentioned in the previous paragraph isn't applied.
Test: New test and all unit tests pass.

DocumentGenerator: Don't include payload in DeviceSigned COSE_Sign1.

---

cbor-processor/src/main/kotlin/com/android/identity/cbor/processor/CborSymbolProcessor.kt
identity-doctypes/src/main/java/com/android/identity/documenttype/knowntypes/DrivingLicense.kt
identity-doctypes/src/main/java/com/android/identity/documenttype/knowntypes/EUPersonalID.kt
identity-doctypes/src/main/java/com/android/identity/documenttype/knowntypes/SampleData.kt
jpeg2k/src/main/java/com/android/identity/jpeg2k/Jpeg2kConverter.kt

Addresses some of the violations from the `property-naming` rule - namely, this PR provides fixes for lines that violate `Property name should use the screaming snake case notation when the value can not be changed (standard:property-naming)`
KTLint progress
https://docs.google.com/document/d/15sudT38S_EMyEANG2td4uDj1i5AlPsWh89JEci9ztgU/edit?resourcekey=0-FYwTd3Tp8f-RZnyEvUdfHQ&tab=t.0#heading=h.7ekjxflvdla5
All tests pass and ran app holder + verifier for sanity test.

KTLint Violation Fix - const val names should follow screaming snake case

---

identity-android/src/androidTest/java/com/android/identity/AndroidAttestationExtensionParser.kt

Replaced taggedEntry.getObject() with taggedEntry.baseObject as ASN1Primitive.
Tested locally.
Fixes #602

Bug Fix in AndroidAttestationExtensionParser

---

identity-android-legacy/build.gradle
identity-android/build.gradle
identity-android/src/androidTest/java/com/android/identity/android/document/AndroidKeystoreSecureAreaDocumentStoreTest.kt
identity-android/src/androidTest/java/com/android/identity/android/securearea/AndroidKeystoreSecureAreaTest.kt
identity/build.gradle
identity/src/main/java/com/android/identity/flow/environment/Configuration.kt
identity/src/main/java/com/android/identity/util/AndroidAttestationExtensionParser.kt
wallet-issuance/src/main/java/com/android/identity/issuance/authenticationUtilities.kt
wallet-issuance/src/main/java/com/android/identity/issuance/hardcoded/AuthenticationState.kt
wallet-server/environment/settings.json
wallet-server/src/main/java/com/android/identity/wallet/server/FlowServlet.kt
wallet/src/main/java/com/android/identity_credential/wallet/WalletApplication.kt

- Introduce settings to require GMS attestation, Verified Boot Green, or a particular digest of an app signing key. For now just set these to false, for production these should be true and bound to a particluar application.
- Change default wallet server URL so things work out-of-the-box in the emulator. An upcoming PR will add UI to change this.
- Don't store message-encryption key in Configuration, use Storage instead.
Also fix some build errors for unit-tests in identity-android and identity-android-legacy.

Misc wallet server changes.

---

wallet/src/main/AndroidManifest.xml
wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/settings/SettingsScreen.kt
wallet/src/main/res/values/strings.xml
wallet/src/main/res/xml/network_security_config.xml

This should resolve issues with tunneling local dev server to the wallet app.
Fixes #619

Add items to manifest to allow connections to http (only localhost for development).

---

README.md
identity-flow/src/main/java/com/android/identity/flow/environment/Notifications.kt
identity-flow/src/main/java/com/android/identity/flow/handler/FlowHandlerRemote.kt
identity-issuance/build.gradle
identity-issuance/src/main/java/com/android/identity/issuance/AuthenticationFlow.kt
identity-issuance/src/main/java/com/android/identity/issuance/ClientAuthentication.kt
identity-issuance/src/main/java/com/android/identity/issuance/WalletApplicationCapabilities.kt
identity-issuance/src/main/java/com/android/identity/issuance/WalletNotificationPayload.kt
identity-issuance/src/main/java/com/android/identity/issuance/WalletServer.kt
identity-issuance/src/main/java/com/android/identity/issuance/WalletServerCapabilities.kt
identity-issuance/src/main/java/com/android/identity/issuance/hardcoded/AuthenticationState.kt
identity-issuance/src/main/java/com/android/identity/issuance/hardcoded/IssuingAuthorityState.kt
identity-issuance/src/main/java/com/android/identity/issuance/hardcoded/WalletServerState.kt
server/environment/settings.json
server/src/main/java/com/android/identity/wallet/server/FlowServlet.kt
server/src/main/java/com/android/identity/wallet/server/ServerEnvironment.kt
server/src/main/java/com/android/identity/wallet/server/ServerNotifications.kt
server/src/main/webapp/WEB-INF/web.xml
wallet/src/main/AndroidManifest.xml
wallet/src/main/java/com/android/identity/issuance/DocumentExtensions.kt
wallet/src/main/java/com/android/identity/issuance/remote/LocalDevelopmentEnvironment.kt
wallet/src/main/java/com/android/identity/issuance/remote/WalletHttpClient.kt
wallet/src/main/java/com/android/identity/issuance/remote/WalletServerProvider.kt
wallet/src/main/java/com/android/identity_credential/wallet/DocumentModel.kt
wallet/src/main/java/com/android/identity_credential/wallet/WalletApplication.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/document/DocumentInfoScreen.kt

These notifiactions only work when the appliaction is running but on the other hand, no secrets/configuration is needed on neither the client nor server side. Support for real push notifications using Firebase Messaging will be added in a future commit.
Also add WalletServerCapabilities and WalletApplicationCapabilities objects which are exchanged at authentication time, that is, the first time a fresh wallet app instance connects to the wallet server.
Also clarify the document sync code in DocumentModel a little bit and fix a bug there so we get notifiactions on remote document deletion.
Also enhance logging in the FlowServlet code.

Add a way for the wallet server to send notifications to the wallet app.

---

README.md
gradle/libs.versions.toml
wallet/build.gradle
wallet/src/customized/java/com/android/identity_credential/wallet/WalletApplicationConfiguration.kt
wallet/src/customized/res/xml/network_security_config.xml
wallet/src/main/java/com/android/identity/issuance/remote/WalletHttpClient.kt
wallet/src/main/java/com/android/identity/issuance/remote/WalletServerProvider.kt
wallet/src/main/res/xml/network_security_config.xml

The CIO engine for ktor seems to have some problems, for example it doesn't respect network_security_config.xml and it has issues when using https URLs. Fix this by changing to the Android engine which has none of these problems.
For the default flavor, allow any cleartext traffic and leave a note explaining why this is allowed (so developers can easily point to local wallet servers). For the 'customized' flavor don't allow cleartext traffic and only allow traffic to ws.example.com. Make a note in README.md that downstreams need to customize this.
Test: Manually tested `customized` flavor pointing to a wallet server.

Fix network configuration problem when whitelabeling.

---

gradle/libs.versions.toml
identity-doctypes/src/main/java/com/android/identity/documenttype/knowntypes/EUPersonalID.kt
wallet/build.gradle
wallet/src/main/AndroidManifest.xml
wallet/src/main/java/com/android/identity_credential/wallet/presentation/OpenID4VPPresentationActivity.kt
wallet/src/test/java/com/android/identity_credential/wallet/OpenID4VPTest.kt

Created a new OpenID4VPPresentationActivity in wallet which will handle any uri invocations with supported schema, parse the incoming request, ask user for confirmation, and send the appropriate response. Also added unit tests to confirm functionality of a subset of parsing methods.
Test methods: Unit tests + manually against EUDIW verifier at https://verifier.eudiw.dev/home

Add support for mdoc profile of OpenID4VP in wallet

---

wallet/src/main/java/com/android/identity_credential/wallet/presentation/OpenID4VPPresentationActivity.kt

Wrap calls to processRequest and createAndSendResponse in try-catch blocks with logging and more graceful end to the activity.
Tested methods: Unit tests + manually against EUDIW verifier at https://verifier.eudiw.dev/home

Graceful Failure of OpenID4VPPresentationActivity

---

wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/provisioncredential/EvidenceRequest.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/prompt/passphrase/PassphraseEntryField.kt
wallet/src/main/res/values/strings.xml

Also fixed a minor bug in PassphraseEntryField. 
Fixes #655.
Manually tested.

Use PassphraseEntryField for German eID PIN entry.

---

appholder/src/androidTest/java/com/android/mdl/app/selfsigned/SelfSignedScreenStateTest.kt
appholder/src/main/java/com/android/identity/wallet/HolderApp.kt
appholder/src/main/java/com/android/identity/wallet/util/PreferencesHelper.kt
identity-android-legacy/build.gradle.kts
identity-android-legacy/src/androidTest/java/com/android/identity/android/legacy/MigrateFromKeystoreICStoreTest.java
identity-android/build.gradle.kts
identity-android/src/androidTest/java/com/android/identity/android/document/AndroidKeystoreSecureAreaDocumentStoreTest.kt
identity-android/src/androidTest/java/com/android/identity/android/securearea/AndroidKeystoreSecureAreaTest.kt
identity-android/src/androidTest/java/com/android/identity/android/storage/AndroidStorageTest.kt
identity-android/src/main/java/com/android/identity/android/storage/AndroidStorageEngine.kt
identity/src/commonMain/kotlin/com/android/identity/storage/GenericStorageEngine.kt
samples/age-verifier-mdl/build.gradle.kts
samples/age-verifier-mdl/src/main/java/com/android/identity/age_verifier_mdl/TransferHelper.kt
samples/preconsent-mdl/build.gradle.kts
samples/preconsent-mdl/src/main/java/com/android/identity/preconsent_mdl/TransferHelper.kt
samples/secure-area-test-app/build.gradle.kts
samples/secure-area-test-app/src/androidMain/kotlin/com/android/identity/secure_area_test_app/ui/AndroidKeystoreSecureAreaScreenAndroid.kt
wallet/src/main/java/com/android/identity_credential/wallet/WalletApplication.kt

This is similar to the change made in GenericStorageEngine recently and makes it simpler to write unit tests to check that new code is backwards compatible with existing on-disk data. We want to do this so we can guarantee backwards compat to our downstream users.
This is a breaking change, the `wallet` module will lose all provisioned documents.
Test: ./gradlew checkConnected
Test: Manually tested wallet app and secure-area-test-app.

AndroidStorageEngine: Change to store data in a single file.

---

wallet/src/main/java/com/android/identity_credential/wallet/PresentationActivity.kt
wallet/src/main/java/com/android/identity_credential/wallet/credman/CredmanPresentationActivity.kt

**Squashed commits from PR https://github.com/openwallet-foundation-labs/identity-credential/pull/667**
Due to `main` pulled into the branch replaying main's commits on the branch first then adding the branch's commit on top -- once pushed the commit history is unrecoverable at this point which is why PR #667 is closed. This PR provides all the commits already squashed rather than squashing the commits at the time of merging the PR. 
- Removal of unused functions in CredmanPresentationActivity whose functionality is provided from the Presentment Flow.
- Helper function in CredmanPresentationActivity to handle showing the Presentment Flow
- Removal of param to optionally hide the Consent Prompt from a Presentment Flow
- Reverting to allowing each protocol handle their own response after a …

CredmanPresentationActivity updates to use showPresentmentFlow

---

identity-android/src/main/java/com/android/identity/android/mdoc/transport/GattClient.kt
identity-android/src/main/java/com/android/identity/android/mdoc/transport/GattServer.kt

On some combination of devices, messages being sent to the GATT layer are list if we call disconnect() right after sending them. Specifically this results in the mDL reader not receiving the entire DeviceResponse before receiving a notification that the other device disconnected.
Work around this bug by inserting a 1 second sleep before calling disconnect().
Test: Manually tested with two devices.

Bluetooth LE: work around bugs in BLE stack.

---

wallet/src/main/java/com/android/identity_credential/wallet/PresentationActivity.kt

After running PresentationActivity we forgot to reset the global state so subsequent NFC taps didn't work. Manually tested two mdoc presentations in the same wallet app instance, both using NFC engagement.

PresentationActivity: Make sure multiple NFC taps work.

---

.github/workflows/unit-test.yml
appholder/build.gradle.kts
appverifier/build.gradle.kts
build.gradle.kts
gradle/libs.versions.toml
identityctl/build.gradle.kts
identityctl/src/main/java/com/android/identity/identityctl/IdentityCtl.kt
samples/age-verifier-mdl/build.gradle.kts
samples/preconsent-mdl/build.gradle.kts
samples/secure-area-test-app/build.gradle.kts
samples/simple-verifier/build.gradle.kts
wallet/build.gradle.kts
wallet/src/main/assets/webview/about.md

Use the output of `git describe --tags --dirty` as the version number which for releases is equal to the tag name (e.g. `20240702`) and for snapshots will be the latest tag, the number of commits since, the commit-id, and possibly if the tree has been modified. For example `20231002-179-gd592df9c-dirty`.
Also start using a Gradle plugin for generating `BuildConfig` so we can convey the version numbers in code. Do this for `identityctl` tool and make room in the `about.md` page in the Wallet app to do this. Peter will implement conveying the version number to Markdown/HTML in a future commit.

Add automatically generated version string to apps.

---

wallet/build.gradle.kts
wallet/src/main/assets/webview/about.md
wallet/src/main/java/com/android/identity_credential/wallet/ui/HtmlSnippet.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/Markdown.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/WebViewContentRenderer.kt

Added appinfo attribute to inject app-specific content into HTML/Markdown that we render in-app and hooked that to about screen.
Tested manually for both markdown and HTML.

Display version info in about screen.

---

appholder/src/main/java/com/android/identity/wallet/util/PreferencesHelper.kt

This fixes a problem introduced in commit
https://github.com/openwallet-foundation-labs/identity-credential/commit/419b69f2f46e144ea6a0f00b66a29e78b7c320d1
Test: Manually tested appholder

appholder: Fix crash.

---

gradle/libs.versions.toml
identity-issuance/src/main/java/com/android/identity/issuance/evidence/EvidenceRequestSelfieVideo.kt
identity-issuance/src/main/java/com/android/identity/issuance/evidence/EvidenceResponseSelfieVideo.kt
identity-issuance/src/main/java/com/android/identity/issuance/proofing/ProofingGraphBuilder.kt
identity-issuance/src/main/java/com/android/identity/issuance/proofing/defaultGraph.kt
wallet/build.gradle.kts
wallet/src/main/AndroidManifest.xml
wallet/src/main/java/com/android/identity/issuance/remote/StorageImpl.kt
wallet/src/main/java/com/android/identity_credential/wallet/FaceImageClassifier.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/SelfieRecorder.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/provisioncredential/EvidenceRequest.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/provisioncredential/ProvisionCredentialScreen.kt
wallet/src/main/res/values/strings.xml

This adds ML Kit, hooks it into the Selfie camera recording code, detects
all the current poses we support (and adds support for detecting smiling),
and replaces the button to proceed to the next pose.
Fixes #680

Add Selfie verification, including MLKit-based facial pose recognition

---

wallet/src/main/java/com/android/identity_credential/wallet/SettingsModel.kt

This was broken with the port to Kotlin Multiplatform.

Wallet: Make "log sharing" work again.

---

gradle/libs.versions.toml
wallet/build.gradle.kts
wallet/src/main/AndroidManifest.xml
wallet/src/main/java/com/android/identity_credential/wallet/presentation/OpenID4VPPresentationActivity.kt

Main fix here is to use `showPresentmentFlow()` just like Proximity and Credman presentations. Also simplifies code flows and shows an "error" and "success" graphics before switching back to the browser which invoked us. Also set the activity flags properly so the activity is single task, no history, and doesn't appear in recents.

wallet: OpenID4VP presentation fixes.

---

wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/main/MainScreen.kt
wallet/src/main/res/values/strings.xml

Ask the user to enable Bluetooth if it's disabled, when sharing a QR code.
Tested by:
- Manual testing through UI.
Fixes #698

Ask the user to enable Bluetooth if it's disabled, when sharing a QR code

---

wallet/src/main/AndroidManifest.xml
wallet/src/main/java/com/android/identity_credential/wallet/NfcEngagementHandler.kt
wallet/src/main/java/com/android/identity_credential/wallet/PresentationActivity.kt
wallet/src/main/java/com/android/identity_credential/wallet/QrEngagementViewModel.kt
wallet/src/main/res/drawable/waiting_for_reader.xml
wallet/src/main/res/values/strings.xml

This change also shows a "Waiting for reader to connect…" right after the NFC tap / QR code scan. This is very helpful for users insofar they see that something in happening sooner.
Also simplify the flow/state management in `PresentationActivity.kt`.
See [this video](https://photos.app.goo.gl/dqAp6dy9Xy5B19ke7) for an example of what it looks like.

wallet: Make proximity presentations work even if app isn't running.

---

README.md

README.md: fix typo 'arbritrary'.

README.md: fix typo 'arbritrary'.

---

wallet/src/main/java/com/android/identity_credential/wallet/ui/prompt/consent/ConsentPromptEntryField.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/prompt/passphrase/PassphrasePinScreen.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/prompt/passphrase/PassphrasePrompt.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/prompt/passphrase/PassphrasePromptInputField.kt

- UI updates to Consent Prompt including larger font size, better alignment of action buttons cancel and done, better alignment of title and verifier icon.
- UI updates to Passphrase Prompt including larger font size and using the default background color for Keypad Buttons on PIN constraints.
- Cloned PassphraseEntryField into PassphrasePromptInputField to provide specific business logic related to the Passphrase/PIN Prompt and not related to PassphraseEntryField and its weak-passphrase logic.
- Reverted PassphraseEntryField to no longer accept params imeAction, disableKeyboard, or setText.
- PassphrasePromptInputField now accepts one parameter -setPin- which sets the Input Field text to be the value of -setPin- and is used to identify whether to disable the keyboard focus.
- Updated …

Updates to Wallet UI so its more preseentable and appealing

---

identity-issuance/src/main/java/com/android/identity/issuance/IssuingAuthorityException.kt
identity-issuance/src/main/java/com/android/identity/issuance/funke/FunkeIssuingAuthorityState.kt
identity-issuance/src/main/java/com/android/identity/issuance/funke/FunkeProofingState.kt
identity-issuance/src/main/java/com/android/identity/issuance/funke/FunkeRequestCredentialsState.kt
identity-issuance/src/main/java/com/android/identity/issuance/funke/FunkeUtil.kt
identity-issuance/src/main/java/com/android/identity/issuance/wallet/WalletServerState.kt
server/src/main/java/com/android/identity/wallet/server/FlowServlet.kt
wallet/src/main/java/com/android/identity/issuance/remote/WalletServerProvider.kt
wallet/src/main/java/com/android/identity_credential/wallet/DocumentModel.kt
wallet/src/main/java/com/android/identity_credential/wallet/ProvisioningViewModel.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/document/DocumentInfoScreen.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/main/MainScreen.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/provisioncredential/ProvisionCredentialScreen.kt
wallet/src/main/res/values/strings.xml

Created an exception type to deliver issuer-side errors to the client and handle it on the client. Got Funke issuer to throw that exception when issuance network requests fail.
Also adjusted end-point for the issuer, so it is easier to flip between option C and option C' endpoints.
Tested by artificially creating malformed requests to the issuance server.

Better handling of error conditions for Funke issuing authority.

---

identity/src/commonMain/kotlin/com/android/identity/document/Document.kt
server/build.gradle.kts
server/src/main/java/com/android/identity/wallet/server/VerifierServlet.kt
server/src/main/webapp/verifier.html
wallet/src/main/java/com/android/identity_credential/wallet/PresentationActivity.kt
wallet/src/main/java/com/android/identity_credential/wallet/credman/CredmanPresentationActivity.kt
wallet/src/main/java/com/android/identity_credential/wallet/presentation/OpenID4VPPresentationActivity.kt
wallet/src/main/java/com/android/identity_credential/wallet/presentation/PresentmentFlow.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/prompt/consent/ConsentPrompt.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/prompt/consent/ConsentPromptEntryField.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/prompt/consent/ConsentPromptEntryFieldData.kt
wallet/src/test/java/com/android/identity_credential/wallet/OpenID4VPTest.kt

This adds support to the verifier server to request an SD-JWT PID, then check and display the results. There are corresponding changes to the oid4vp presentation code in the client.
This contains a number of shortcuts that should probably be refactored in the future to make the code cleaner, including:
- Display names in the consent prompt code, rather than a new document type that describes all the known SD-JWT fields.
- Several "if mdoc / if sdjwt" patterns that would be cleaner if this functionality were moved into corresponding classes.
- Special handling for several fields that exist in the SD-JWT but are not in the list of disclosures.
The request and checks in the server likely have differences from the standard. Please file bugs for any differences you find.
Tested by:
- Manual …

Add support for SD-JWT verification.

---

server/src/main/java/com/android/identity/wallet/server/VerifierServlet.kt

This was useful for debugging, but we don't want it surfaced in the UI anymore.
Tested by:

Remove the UI that indicated when a requested value was not returned.

---

identity-doctypes/src/commonMain/kotlin/com/android/identity/documenttype/knowntypes/DrivingLicense.kt
identity-doctypes/src/commonMain/kotlin/com/android/identity/documenttype/knowntypes/EUPersonalID.kt
identity-issuance/src/main/java/com/android/identity/issuance/hardcoded/IssuingAuthorityState.kt
identity/src/commonMain/kotlin/com/android/identity/documenttype/DocumentType.kt
identity/src/commonMain/kotlin/com/android/identity/documenttype/DocumentWellKnownRequest.kt
identity/src/commonMain/kotlin/com/android/identity/documenttype/VcRequest.kt
server/build.gradle.kts
server/src/main/java/com/android/identity/wallet/server/VerifierServlet.kt
server/src/main/webapp/verifier.html
server/src/main/webapp/verifier.js
wallet/src/main/java/com/android/identity_credential/wallet/SelfSignedEuPidIssuingAuthority.kt
wallet/src/main/java/com/android/identity_credential/wallet/SelfSignedIssuingAuthority.kt

Also add support for W3C VC claims in sample requests in the DocumentType API and use this to avoid repetition in VerifierServlet.

verifier: Add support for W3C Digital Credentials API.

---

server/src/main/java/com/android/identity/wallet/server/VerifierServlet.kt
wallet/src/main/java/com/android/identity_credential/wallet/presentation/OpenID4VPPresentationActivity.kt
wallet/src/test/java/com/android/identity_credential/wallet/OpenID4VPTest.kt

Most of the changes are to make the client more permissive for different types of requests. A few parts of the exchange between client and server needed to change to better match the spec (for instance, where the expected format is sent).
Tested by:
- Manual testing of both mdoc and sd-jwt verification.

Adjust the protocol slightly between the verifier and our client.

---

server/src/main/java/com/android/identity/wallet/server/VerifierServlet.kt
wallet/src/main/java/com/android/identity_credential/wallet/presentation/OpenID4VPPresentationActivity.kt

Namespaces were re-added to the descriptor in a recent CL. This strips them out again.
This also adds a little more debugging output.
Tested by:
- Manually testing the sd-jwt verification flows.

Clean up the SD-JWT inputDescriptor.

---

identity-issuance/src/main/java/com/android/identity/issuance/funke/FunkeProofingState.kt
identity-issuance/src/main/java/com/android/identity/issuance/proofing/defaultGraph.kt
server/src/main/resources/resources/funke/tos.html
wallet/src/main/java/com/android/identity/issuance/remote/LocalDevelopmentEnvironment.kt
wallet/src/main/res/values/strings.xml

Tested manually both in "dev:" server and localhost wallet server.

Added TOS screen and request for notification permissions to Funke proofing workflow.

---

wallet/src/main/java/com/android/identity_credential/wallet/presentation/OpenID4VPPresentationActivity.kt
wallet/src/main/res/values/strings.xml

Previously, the message just said there was an error. Now, it indicates that there are no documents available that match the request.
Tested by:

Show a friendlier error message if no documents match the request.

---

identity-mdoc/src/commonMain/kotlin/com/android/identity/mdoc/response/DeviceResponseGenerator.kt
identity/src/commonMain/kotlin/com/android/identity/cbor/ArrayBuilder.kt
identity/src/commonTest/kotlin/com/android/identity/cbor/ArrayBuilderTests.kt
wallet/src/main/java/com/android/identity_credential/wallet/PresentationActivity.kt

Previously, this just printed an error message. Now it indicates that there are no documents that match the request.
Tested by:
- Manual testing with various doc types, using AppVerifier as the RP.

Improved message for in-person presentation if no documents match the request

---

wallet/src/main/java/com/android/identity_credential/wallet/SettingsModel.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/main/MainScreen.kt

Previously, we added a dialog if the user tries to show a QR code, telling the user that Bluetooth needs to be enabled. This adds a snackbar notification before that, on the main screen when we're displaying a document.
Tested by:
Fixes #698

Add a notification if Bluetooth is disabled.

---

identity-issuance/src/main/java/com/android/identity/issuance/funke/FunkeAccess.kt
identity-issuance/src/main/java/com/android/identity/issuance/funke/FunkeIssuerDocument.kt
identity-issuance/src/main/java/com/android/identity/issuance/funke/FunkeIssuingAuthorityState.kt
identity-issuance/src/main/java/com/android/identity/issuance/funke/FunkeProofingState.kt
identity-issuance/src/main/java/com/android/identity/issuance/funke/FunkeUtil.kt

Manually tested by switching to Option C' end point and setting max use per credential to 1.

Implemented refresh token (only issued in Option C' at this point).

---

server/src/main/java/com/android/identity/wallet/server/VerifierServlet.kt
wallet/src/main/java/com/android/identity_credential/wallet/presentation/OpenID4VPPresentationActivity.kt

Modified OpenID4VPPresentationActivity to format vpToken differently in both mdl and sd-jwt cases, and expect jwks already in a "keys" map. Updated VerifierServlet to parse vpToken after changes, and put jwks in "keys".
Tested wallet against conformance tests at https://demo.certification.openid.net/ for both sd-jwt and mdl credential types. Used response_mode=direct_post.jwt.
Manually tested verifier locally against changes in wallet to ensure verifier successfully receives + displays response from wallet.

Update Verifier and Presentation to Pass Conformance Tests

---

wallet/build.gradle.kts
wallet/src/main/java/com/android/identity_credential/wallet/DocumentModel.kt
wallet/src/main/java/com/android/identity_credential/wallet/EventInfo.kt
wallet/src/main/java/com/android/identity_credential/wallet/PresentationActivity.kt
wallet/src/main/java/com/android/identity_credential/wallet/SettingsModel.kt
wallet/src/main/java/com/android/identity_credential/wallet/WalletApplication.kt
wallet/src/main/java/com/android/identity_credential/wallet/logging/DocumentUpdateCheckEvent.kt
wallet/src/main/java/com/android/identity_credential/wallet/logging/Event.kt
wallet/src/main/java/com/android/identity_credential/wallet/logging/EventLogger.kt
wallet/src/main/java/com/android/identity_credential/wallet/logging/MdocPresentationEvent.kt
wallet/src/main/java/com/android/identity_credential/wallet/navigation/WalletDestination.kt
wallet/src/main/java/com/android/identity_credential/wallet/navigation/WalletNavigation.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/document/DocumentInfoScreen.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/document/EventLogScreen.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/settings/SettingsScreen.kt
wallet/src/main/res/values/strings.xml
wallet/src/test/java/com/android/identity_credential/wallet/logging/EventLoggerTest.kt

ActivityLogger is added and used to capture the credman presentation activity. Once an activity is made on a card, when the user view that card, they can click on the top right corner and see the corresponding activities.
Tested by: local testing for presentment activity and viewing of the event.
Signed-off-by: Hamzeh Zawawy/hamzeh@google.com

Adding logging for presentation activity and corresponding viewer

---

server/src/main/webapp/verifier.js

This is required as per
https://wicg.github.io/digital-credentials/#the-digitalcredential-interface
Chrome adds this by default but this is not true for all browsers.

Add "mediation: 'required'" to navigator.identity.get() calls.

---

server/src/main/java/com/android/identity/wallet/server/VerifierServlet.kt
server/src/main/webapp/verifier.html
server/src/main/webapp/verifier.js

Instead of manually building UI and code, just use the sample requests available in DocumentTypeRepository to build the UI and run the request.
This also gives us support for the PhotoID doctype recently added. In the future when adding new doctypes, we'll also automatically get support in the verifier for free.
Test: Manually tested (OpenID4VP, W3C DC Preview + A.R.F., all requests)

Use sample requests from DocumentTypeRepository in online verifier.

---

identity-issuance/src/main/java/com/android/identity/issuance/funke/FunkeIssuingAuthorityState.kt
server-openid4vci/src/main/java/com/android/identity/server/openid4vci/AuthorizeServlet.kt
server-openid4vci/src/main/java/com/android/identity/server/openid4vci/CredentialRequestServlet.kt
server-openid4vci/src/main/java/com/android/identity/server/openid4vci/CredentialServlet.kt
server-openid4vci/src/main/java/com/android/identity/server/openid4vci/ParServlet.kt
server-openid4vci/src/main/java/com/android/identity/server/openid4vci/messages.kt
server/src/main/resources/resources/common_configuration.json
server/src/main/resources/resources/openid4vci/authorize.html
server/src/main/webapp/WEB-INF/web.xml
server/src/main/webapp/openid4vci/authorize.js

Only mdoc PIDs are supported at this point.
Tested manually with a PID generated by our hardcoded issuer.

Using PID authentication as openid4vci proofing.

---

identity-appsupport/src/commonMain/kotlin/com/android/identity/appsupport/ui/Icon.kt
identity-doctypes/src/commonMain/kotlin/com/android/identity/documenttype/knowntypes/DrivingLicense.kt
identity-doctypes/src/commonMain/kotlin/com/android/identity/documenttype/knowntypes/EUPersonalID.kt
identity-doctypes/src/commonMain/kotlin/com/android/identity/documenttype/knowntypes/PhotoID.kt
identity-doctypes/src/commonTest/kotlin/com/android/identity/documenttype/TestDocumentTypeRepository.kt
identity/src/commonMain/kotlin/com/android/identity/documenttype/DocumentAttribute.kt
identity/src/commonMain/kotlin/com/android/identity/documenttype/DocumentType.kt
identity/src/commonMain/kotlin/com/android/identity/documenttype/Icon.kt
identity/src/commonMain/kotlin/com/android/identity/documenttype/MdocDocumentType.kt
identity/src/commonMain/kotlin/com/android/identity/documenttype/MdocNamespace.kt
identity/src/commonMain/kotlin/com/android/identity/documenttype/VcDocumentType.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/prompt/consent/ConsentPromptEntryField.kt

Also show these icons in the consent prompt, if available. Also use a smaller font in the consent dialog since some of the data element names won't fit.

Add icons to the registered document types.

---

identity-doctypes/src/commonMain/kotlin/com/android/identity/documenttype/knowntypes/PhotoID.kt
identity-issuance/src/main/java/com/android/identity/issuance/hardcoded/IssuingAuthorityState.kt

Most of the data elements are in the ISO/IEC TS 23220-2 namespace (confusingly named `org.iso.23220.1`), not the PhotoID namespace (named `org.iso.23220.photoid.1`). Fix this.

PhotoID: Use correct namespace.

---

identity-issuance/src/main/java/com/android/identity/issuance/hardcoded/IssuingAuthorityState.kt

Add ICAO eMRTD data groups when ICAO doc is used for proofing.
Tested manually with eID card.

Added ICAO eMRTD data groups to PhotoID documents.

---

identity-doctypes/src/commonMain/kotlin/com/android/identity/documenttype/knowntypes/PhotoID.kt
wallet/src/main/java/com/android/identity_credential/wallet/ReaderModel.kt
wallet/src/main/java/com/android/identity_credential/wallet/WalletApplication.kt

Handle not having `displayName` in a Trust Point for the reader. This can happen when importing trust points from a VICAL where there's no display name. Just use the subject X500 principal name instead.
Register the OWF Test IACA _after_ the VICAL so our display name and icon is actually used.
Add missing description for PhotoID data element.

Misc fixes for Austroads Test Event.

---

server/src/main/webapp/verifier.js

The latest spec of the W3C DC API returns an object, not a string. Add workaround to cope with some implementations - such as Chrome - not yet doing this.

Properly handle strings/objects being returned from navigator.identity.get().

---

identity-mdoc/src/commonMain/kotlin/com/android/identity/mdoc/response/DeviceResponseParser.kt
identity/src/commonMain/kotlin/com/android/identity/cbor/Cbor.kt
identity/src/commonTest/kotlin/com/android/identity/cbor/CborTests.kt

Turns out the code for encoding a Bstr, Tstr, and other types doesn't use the fewest possible bytes when encoding. This is allowed behavior but the resulting CBOR is not compliant with the rules for Preferred Serialization according to RFC 8949 4.2.1. Core Deterministic Encoding Requirements.
This behavior triggers a bug in `DeviceResponseParser` because it's written to assume that the encoding `IssuerSignedItemBytes` follows the rules in ISO/IEC 18013-5:2021 which requires this as per clause "8.1 Encoding of data structures and data elements."
Concretely, it means that any `DeviceResponse` CBOR with bstr data elements greater than 64 KiB will be reported as failing to validate by `DeviceResponseParser` when in fact this is not the case. Normally mdoc data elements are smaller than this, …

Use fewest possible bytes for CBOR length encodings.

---

identity-flow/src/main/java/com/android/identity/flow/handler/FlowExceptionMap.kt
identity-flow/src/main/java/com/android/identity/flow/handler/InvalidRequestException.kt
identity-issuance/src/main/java/com/android/identity/issuance/ApplicationSupport.kt
identity-issuance/src/main/java/com/android/identity/issuance/funke/AbstractRequestCredentials.kt
identity-issuance/src/main/java/com/android/identity/issuance/funke/FunkeIssuerDocument.kt
identity-issuance/src/main/java/com/android/identity/issuance/funke/FunkeIssuingAuthorityState.kt
identity-issuance/src/main/java/com/android/identity/issuance/funke/FunkeUtil.kt
identity-issuance/src/main/java/com/android/identity/issuance/funke/KeyAttestationCredentialRequest.kt
identity-issuance/src/main/java/com/android/identity/issuance/funke/ProofOfPossessionCredentialRequest.kt
identity-issuance/src/main/java/com/android/identity/issuance/funke/RequestCredentialsUsingKeyAttestation.kt
identity-issuance/src/main/java/com/android/identity/issuance/funke/RequestCredentialsUsingProofOfPossession.kt
identity-issuance/src/main/java/com/android/identity/issuance/wallet/ApplicationSupportState.kt
identity-issuance/src/main/java/com/android/identity/issuance/wallet/WalletServerState.kt
processor/src/main/kotlin/com/android/identity/processor/CborSymbolProcessor.kt
server-env/src/main/java/com/android/identity/server/BaseFlowHttpServlet.kt
server-env/src/main/java/com/android/identity/server/BaseHttpServlet.kt
server-openid4vci/src/main/java/com/android/identity/server/openid4vci/BaseServlet.kt
server-openid4vci/src/main/java/com/android/identity/server/openid4vci/CredentialRequestServlet.kt
server-openid4vci/src/main/java/com/android/identity/server/openid4vci/CredentialServlet.kt
server-openid4vci/src/main/java/com/android/identity/server/openid4vci/FinishAuthorizationServlet.kt
server-openid4vci/src/main/java/com/android/identity/server/openid4vci/ParServlet.kt
server-openid4vci/src/main/java/com/android/identity/server/openid4vci/TokenServlet.kt
server-openid4vci/src/main/java/com/android/identity/server/openid4vci/messages.kt
server/src/main/java/com/android/identity/wallet/server/LandingServlet.kt

Implemented:
- key attestation in our openid4vci server and client
- refresh token in our openid4vci server (it is already supported on the client).
Some additional fixes:
- allow arbitrary order in constructor parameters for classes marked with CborSerializable
- InvalidRequestException to declutter the most basic error processing
- changed support for "landing URLs" to always work with absolute URLs (tends to be more robust)
- adjusted sd-jwt-vc vci value for the most recent BDR issuance server version
Tested manually using both default Funke issuance server and our own openid4vci server (adjusting parameters that are currently hardcoded).

Implemented key attestation in openid4vci + misc. fixes.

---

identity-android/src/main/java/com/android/identity/android/mdoc/transport/DataTransportBlePeripheralServerMode.kt
wallet/src/main/java/com/android/identity_credential/wallet/NfcEngagementHandler.kt
wallet/src/main/java/com/android/identity_credential/wallet/QrEngagementViewModel.kt
wallet/src/main/java/com/android/identity_credential/wallet/ReaderModel.kt
wallet/src/main/java/com/android/identity_credential/wallet/SettingsModel.kt
wallet/src/main/java/com/android/identity_credential/wallet/WalletApplication.kt
wallet/src/main/java/com/android/identity_credential/wallet/navigation/WalletDestination.kt
wallet/src/main/java/com/android/identity_credential/wallet/navigation/WalletNavigation.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/CommonUI.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/settings/SettingsProximitySharingScreen.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/settings/SettingsScreen.kt
wallet/src/main/res/values/strings.xml

This is a new screen only available if Developer Mode is enabled and it allows configuration of which parts of the ISO/IEC 18013-5:2021 protocol to use. This is useful for interoperability testing with other wallets and readers.
Also fix a bug in our implementation of _BLE mdoc peripheral server_ mode. The problem is that we forgot to start the GATT client, looks like this bug was introduced a long time ago but was never discovered since _BLE mdoc central client_ is the default mode for the vast majority of wallets and readers. The fact that we now have settings to change the default will help avoid mistakes like this in the future.

wallet: add new "Proximity Sharing Settings" screen.

---

wallet/src/main/java/com/android/identity_credential/wallet/presentation/OpenID4VPPresentationActivity.kt

Added a null check so the code ends up displaying a message to the user, "No available documents can fulfill the request," rather than the generic, "An error has occurred."
This hits when running OpenID4VP verification from the verifier server to an empty wallet.
Tested by:
Fixes #763

Fix handling of a deleted doc, so the error message to the user is clearer

---

gradle/libs.versions.toml
identity-appsupport/build.gradle.kts
identity-appsupport/src/commonMain/composeResources/values/strings.xml
identity-appsupport/src/commonMain/kotlin/com/android/identity/appsupport/ui/qrcode/ScanQrCodeDialog.kt
identity-appsupport/src/commonMain/kotlin/com/android/identity/appsupport/ui/qrcode/ShowQrCodeDialog.kt
samples/testapp/iosApp/TestApp/Info.plist
samples/testapp/src/androidMain/AndroidManifest.xml
samples/testapp/src/commonMain/composeResources/values/strings.xml
samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/App.kt
samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/Destinations.kt
samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/ui/QrCodesScreen.kt
samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/ui/StartScreen.kt

This adds Compose Multiplatform support for QR code generation and scanning.
A future change will start using this in the wallet app, currently it's only used in samples/testapp.
This adds dependencies on https://github.com/alexzhirkevich/qrose and https://github.com/kalinjul/EasyQRScan which are under the MIT and Apache 2.0 license, respectively. These depencies are wholly hidden behind the `ScanQrCodeDialog` and `ShowQrCodeDialog` in case we want to swap these out in the future. For example, for the scanning part we likely want to just use MLKit directly.
Test: New screens in samples/testapp for testing. Tested on Android and iOS.

identity-appsupport: Add QR code generation and scanning composables.

---

identity-issuance/src/main/java/com/android/identity/issuance/evidence/EvidenceRequestOpenid4Vp.kt
identity-issuance/src/main/java/com/android/identity/issuance/evidence/EvidenceResponseOpenid4Vp.kt
identity-issuance/src/main/java/com/android/identity/issuance/funke/FunkeIssuingAuthorityState.kt
identity-issuance/src/main/java/com/android/identity/issuance/funke/FunkeProofingState.kt
identity-issuance/src/main/java/com/android/identity/issuance/funke/ProofingInfo.kt
identity-issuance/src/main/java/com/android/identity/issuance/funke/openid4VciIssuerMetadata.kt
server-openid4vci/src/main/java/com/android/identity/server/openid4vci/AuthorizeChallengeServlet.kt
server-openid4vci/src/main/java/com/android/identity/server/openid4vci/AuthorizeServlet.kt
server-openid4vci/src/main/java/com/android/identity/server/openid4vci/BaseServlet.kt
server-openid4vci/src/main/java/com/android/identity/server/openid4vci/Openid4VpResponseServlet.kt
server-openid4vci/src/main/java/com/android/identity/server/openid4vci/ParServlet.kt
server-openid4vci/src/main/java/com/android/identity/server/openid4vci/WellKnownOauthAuthorizationServlet.kt
server-openid4vci/src/main/java/com/android/identity/server/openid4vci/WellKnownOpenidCredentialIssuerServlet.kt
server-openid4vci/src/main/java/com/android/identity/server/openid4vci/createSession.kt
server-openid4vci/src/main/java/com/android/identity/server/openid4vci/messages.kt
server-openid4vci/src/main/java/com/android/identity/server/openid4vci/openid4vp.kt
server/src/main/webapp/WEB-INF/web.xml
wallet/src/main/java/com/android/identity_credential/wallet/ProvisioningViewModel.kt
wallet/src/main/java/com/android/identity_credential/wallet/navigation/WalletNavigation.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/provisioncredential/EvidenceRequest.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/provisioncredential/ProvisionCredentialScreen.kt
wallet/src/main/res/values/strings.xml

Implemented draft spec for presentation during issuance that adds an option for the issuing authority to request openid4vp credential presentation as evidence. This significantly improves user experience as there is no need to switch to the browser and then back to the wallet.
In our implementation we send EvidenceRequests for both openid4vp presentation and web-based evidence collection. Wallet determines if there is actually a valid credential that can be used and only offers user to do presentation during issuance if an appropriate credential is found.
Manually tested the scenarios of having and not having an appropriate PID in the wallet as well as accepting or not accepting in-wallet PID presentation.
Only narrow path for OpenId4VP presentation is implemented: PID in mdoc format. …

Presentation during issuance.

---

wallet/src/main/java/com/android/identity_credential/wallet/presentation/OpenID4VPPresentationActivity.kt
wallet/src/test/java/com/android/identity_credential/wallet/OpenID4VPTest.kt

Updated OpenID4VP flow to determine format from input_descriptors field when the format cannot be determined from the client_metadata.
Tested manually against verifiers which have malformed client_metadata.

Pull Format from Input Descriptors

---

identity/src/commonMain/kotlin/com/android/identity/documenttype/DocumentType.kt
identity/src/commonMain/kotlin/com/android/identity/documenttype/VcRequest.kt
server/src/main/java/com/android/identity/wallet/server/VerifierServlet.kt
wallet/src/main/java/com/android/identity_credential/wallet/presentation/OpenID4VPPresentationActivity.kt

Added vct field as const to the verifier, and updated wallet to send documents which match the defined vct if defined as a const.
Tested manually with verifier changes + with verifiers without defined vct.

Add vct Field to OpenID4VP flows

---

wallet/src/main/java/com/android/identity_credential/wallet/DocumentModel.kt
wallet/src/main/java/com/android/identity_credential/wallet/EventInfo.kt
wallet/src/main/java/com/android/identity_credential/wallet/PresentationActivity.kt
wallet/src/main/java/com/android/identity_credential/wallet/logging/EventLogger.kt
wallet/src/main/java/com/android/identity_credential/wallet/logging/MdocPresentationEvent.kt
wallet/src/main/java/com/android/identity_credential/wallet/navigation/WalletDestination.kt
wallet/src/main/java/com/android/identity_credential/wallet/navigation/WalletNavigation.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/document/EventLogScreen.kt
wallet/src/main/res/values/strings.xml
wallet/src/test/java/com/android/identity_credential/wallet/logging/EventLoggerTest.kt

This change include changes to the activity viewer where a high level list of activities is shown. The user gets to click on each activity and can see the specific requested fields. This change required storing the requester information.
Tested by: local testing for presentment activity and viewing of the logged events.
Signed-off-by: Hamzeh Zawawy <hamzeh@google.com>

Improve activity viewer and log requester information

---

server-openid4vci/src/main/java/com/android/identity/server/openid4vci/BaseServlet.kt

Fix for DPoP authorization failure that happens when tomcat base url and actual base url differ.
Manually tested.

Fix for DPoP authorization failure.

---

server-openid4vci/build.gradle.kts
server-openid4vci/src/main/java/com/android/identity/server/openid4vci/QrServlet.kt
server/src/main/webapp/WEB-INF/web.xml
server/src/main/webapp/openid4vci/display_metadata.js

Bar codes for credential offers on our openid4vci server page.

---

appverifier/src/main/java/com/android/mdl/appreader/fragment/ShowDocumentFragment.kt
wallet/src/main/java/com/android/identity_credential/wallet/AttributeDisplayInfo.kt
wallet/src/main/java/com/android/identity_credential/wallet/DocumentDetails.kt
wallet/src/main/java/com/android/identity_credential/wallet/DocumentInfo.kt
wallet/src/main/java/com/android/identity_credential/wallet/DocumentModel.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/CommonUI.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/document/DocumentDetailsScreen.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/reader/ReaderScreen.kt

This required refactoring the way we store the display data for mdoc attributes. Now, instead of mapping from human-readable name to a value string, we map from attribute name to a AttributeDisplayInfo object that includes the attribute's human-readable name and information about how to display the value.
Tested by:
- Manual testing of both the wallet and appverifier.

Display Driving Privileges in a human-friendly format.

---

server-openid4vci/src/main/java/com/android/identity/server/openid4vci/AuthorizeServlet.kt
server/src/main/resources/resources/openid4vci/authorize.html
wallet/src/main/java/com/android/identity_credential/wallet/MainActivity.kt
wallet/src/main/java/com/android/identity_credential/wallet/ProvisioningViewModel.kt
wallet/src/main/java/com/android/identity_credential/wallet/navigation/WalletNavigation.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/addtowallet/AddToWalletScreen.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/provisioncredential/EvidenceRequest.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/provisioncredential/ProvisionCredentialScreen.kt

Hardened code for handling of custom url schema for credential offers. This seemed to eliminate flakiness in my testing. Also cleaned up some singleton objects being passed around as parameters.
Tested using our own openid4vci and funke issuance servers.

Making credential offer url handling more robust.

---

wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/settings/SettingsScreen.kt
wallet/src/main/res/values/strings.xml

When Developer Options are enabled, this adds a new button to the Settings screen to trigger our periodic sync that refreshes all documents/credentials.
Tested by:

Add a developer option to trigger syncing all documents.

---

wallet/src/main/java/com/android/identity_credential/wallet/presentation/OpenID4VPPresentationActivity.kt

This fixes a bug where the new naturalization_date field wasn't showing its display name correctly because we weren't detecting the credential type correctly.
Tested by:
- Manual testing.

Fix the detected vct when parsing the input detector for claim descriptions

---

server/src/main/webapp/verifier.html
server/src/main/webapp/verifier.js

Previously, we'd allow the user to select those protocols, but we'd display an error when they tried to use them. Now, if they're selected, we switch to a supported protocol and disable the incompatible ones.
Tested by:
- Manual testing.

Disable verifier protocols that aren't compatible with the selected document

---

wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/provisioncredential/EvidenceRequest.kt

Previously, it was a cramped list of text. Now, there are icons, and they're spaced better. Looks much cleaner.
Updated screen:
Tested by:
- Manual testing.

Clean up the screen that requests eID attributes.

---

wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/provisioncredential/AusweisModel.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/provisioncredential/EvidenceRequest.kt
wallet/src/main/res/values/strings.xml

Fixes the crash that happens due to unexpected Ausweis SDK response. In particular, handle locked card case (e.g. incorrect PIN entered too many times) by instructing the user to utilize Ausweis App to unlock it.

Fix for unexpected Ausweis SDK responses.

---

identity-issuance/src/main/java/com/android/identity/issuance/evidence/EvidenceRequestOpenid4Vp.kt
identity-issuance/src/main/java/com/android/identity/issuance/funke/FunkeProofingState.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/provisioncredential/EvidenceRequest.kt
wallet/src/main/res/values/strings.xml

Fixes button text and credential request origin text.

Presentation during issuance fixes.

---

wallet/src/main/java/com/android/identity_credential/wallet/ui/CommonUI.kt

The app looks much cleaner if the top bar blends in with the background (same color) and if we omit the title.
Tested by:
- Manual testing of several screens.

Hide the top bar, for a cleaner look.

---

identity-issuance/src/main/java/com/android/identity/issuance/funke/FunkeProofingState.kt

We accidentally had //: instead of ://.
Tested by:

Fixes a typo in the server URL.

---

wallet/src/main/java/com/android/identity_credential/wallet/navigation/WalletNavigation.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/document/EventLogScreen.kt

Some document IDs are URLs, so they have slashes in them. That messes with our route strings, which use slashes to separate parameters. Encoding the docId fixes a crash when trying to navigate to the Activity Log for a single event, when using the German or EU PIDs.
Tested by:
- Manual testing of Utopia, German, and EU PIDs.

B64-encode documentId in routes for the Activity Log Event details page

---

README.md

Mostly to update the number of commits, so we're pushing a new version.

Update some line wraps in the readme

---

server/src/main/java/com/android/identity/wallet/server/VerifierServlet.kt
server/src/main/webapp/WEB-INF/web.xml

Update the verifier to pass "client_id_scheme" parameter as x509_san_dns, and adjust client_id param to be prefixed with "x509_san_dns:" as recommended by OpenID for Verifiable Presentations section 5.10.1. Syntax.
Tested manually against wallet app, using OpenID4VP to retrieve both mdoc and sd-jwt credentials.

Use x509_san_dns Client Id Scheme

---

settings.gradle.kts

Fix #817 by adding opensource toolcahins resolver plugin to help simplify the local project configuration set up.
Fixes #817
- Tested on a clean build with the fresh installation of Android Studio Ladybug | 2024.2.1 Patch 3. The issue is not manifesting.

Add toolchains resolver plugin.

---

identity-issuance-api/src/commonMain/kotlin/com/android/identity/issuance/evidence/EvidenceRequestCredentialOffer.kt
identity-issuance-api/src/commonMain/kotlin/com/android/identity/issuance/evidence/EvidenceResponseCredentialOffer.kt
identity-issuance-api/src/commonMain/kotlin/com/android/identity/issuance/evidence/EvidenceResponsePreauthorizedCode.kt
identity-issuance-api/src/commonMain/kotlin/com/android/identity/issuance/evidence/Openid4VciCredentialOffer.kt
identity-issuance/src/main/java/com/android/identity/issuance/funke/FunkeAccess.kt
identity-issuance/src/main/java/com/android/identity/issuance/funke/FunkeIssuingAuthorityState.kt
identity-issuance/src/main/java/com/android/identity/issuance/funke/FunkeProofingState.kt
identity-issuance/src/main/java/com/android/identity/issuance/funke/FunkeUtil.kt
identity-issuance/src/main/java/com/android/identity/issuance/funke/openid4VciIssuerMetadata.kt
identity/src/commonMain/kotlin/com/android/identity/util/HtmlUtil.kt
server/src/main/java/com/android/identity/wallet/server/AdminServlet.kt
wallet/src/main/java/com/android/identity_credential/wallet/ProvisioningViewModel.kt
wallet/src/main/java/com/android/identity_credential/wallet/credentialoffer/CredentialOfferIssuance.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/provisioncredential/ProvisionCredentialScreen.kt

Reworked how and when we deliver credential offer to the wallet server for openid4vci provisioning. Moved to the model where the credential offer always comes as the first evidence request/response for openid4vci. This also moves more responsibility to proofing flow handler (`FunkeProofingState` in our code, in particular `performPushedAuthorizationRequest` method has been moved). This makes proofing more self-contained.
Manually tested with our openid4vci server and external servers. Also tested with our hardcoded issuer.

OpenId4VCI interoperability fixes.

---

identity-issuance-api/src/commonMain/kotlin/com/android/identity/issuance/CredentialConfiguration.kt
identity-issuance-api/src/commonMain/kotlin/com/android/identity/issuance/RequestCredentialsFlow.kt
identity-issuance/src/main/java/com/android/identity/issuance/funke/FunkeIssuingAuthorityState.kt
identity-issuance/src/main/java/com/android/identity/issuance/funke/FunkeProofingState.kt
identity-issuance/src/main/java/com/android/identity/issuance/funke/RequestCredentialsUsingKeyAttestation.kt
identity-issuance/src/main/java/com/android/identity/issuance/funke/RequestCredentialsUsingProofOfPossession.kt
identity-issuance/src/main/java/com/android/identity/issuance/hardcoded/IssuingAuthorityState.kt
identity-issuance/src/main/java/com/android/identity/issuance/hardcoded/RequestCredentialsState.kt
identity-issuance/src/main/java/com/android/identity/issuance/proofing/defaultGraph.kt
identity/src/commonMain/kotlin/com/android/identity/device/DeviceAssertionMaker.kt
wallet/src/main/java/com/android/identity/issuance/remote/WalletServerProvider.kt
wallet/src/main/java/com/android/identity_credential/wallet/DocumentModel.kt
wallet/src/test/java/com/android/identity/issuance/simple/SimpleIssuingAuthorityRequestCredentialsFlow.kt
wallet/src/test/java/com/android/identity_credential/wallet/TestIssuingAuthority.kt

Since DeviceAssertion validation only makes sense on the server, do not require it when creating credentials using hardcoded issuing authority (which we want to continue working without any servers). Key attestation is still required. In future we can start detecting server environment and require DeviceAssertion only when running on the server, but not in-app.
Tested manually with and without server.

Made key assertion optional for hardcoded issuing authority to avoid the need for minimal wallet server.

---

samples/testapp/iosApp/TestApp.xcodeproj/project.pbxproj
samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/TestAppUtils.kt

The keys used in the testapp doesn't work with iOS CryptoKit's ASN1 parser (which is a bit finicky) so update them with keys that do work. The long-term fix for this is to write our own PEM parser (easily done now that we have a ASN1 library) but for now this fix will do it.
Also remove references to personal build details.
Test: Manually tested testapp on iOS

testapp: Fix key material, remove personal build details.

---

samples/testapp/build.gradle.kts

Remove the redundant project dependency, triggering the "Duplicate content roots" automatic deletion action for the generated commonMain/resources folder.
Fixes #829 
- Tested rebuilding project clean, cofirmed no warning.
- Ran the testapp to confirm no visible issues.
- Unit tests passing OK locally.

Fix the duplicated root issue.

---

identity/src/commonMain/kotlin/com/android/identity/asn1/ASN1Time.kt
identity/src/commonTest/kotlin/com/android/identity/asn1/ASN1Tests.kt
identity/src/jvmTest/kotlin/com/android/identity/crypto/X509CertTestsJvm.kt

According to this RFC, time before year 2050 must use two-digit year in X.509 certificates:
https://datatracker.ietf.org/doc/html/rfc5280#section-4.1.2.5
Use this rule as a default, which makes our certificates more compliant; otherwise openssl rejects them.
Added a smoke-test unit test, but also tested manually with openssl and looked at the der encoding bytes.

Use two digits year for times before 2050 in ASN.1 as the spec mandates.

---

appverifier/src/main/java/com/android/mdl/appreader/fragment/RequestOptionsFragment.kt
samples/simple-verifier/src/main/java/com/android/identity/simple_verifier/MdocReaderPrompt.kt
wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/reader/ReaderScreen.kt

This change addresses an NFC engagement issue that could occur on the first run of AppVerifier after installation. The root cause was an incorrect handling of the Android activity lifecycle events that occur when the permission-requesting activity returns to the main application activity or fragment. The fix ensures that the VerificationHelper instance is initialized during the ON_RESUME lifecycle event, rather than ON_START, to avoid race conditions and ensure proper setup.
Tested manually. Tap each with the phone running Wallet.

Appverifier: Fix NFC engagement problem on first run after install.

---

identity-appsupport/src/commonMain/composeResources/values/strings.xml
identity-appsupport/src/commonMain/kotlin/com/android/identity/appsupport/ui/certificateviewer/CertificateViewData.kt
identity-appsupport/src/commonMain/kotlin/com/android/identity/appsupport/ui/certificateviewer/CertificateViewer.kt
identity/src/commonMain/kotlin/com/android/identity/util/AndroidAttestationExtensionParser.kt

This adds support for pretty-printing the attestation extension from Android Keystore which is helpful as we may elect to provide a way to show these in the wallet app when the user elects to view detailed information about a document and its underlying ISO mdoc or IETF SD-JWT VC credentials.
Also address a couple of small things in CertificateViewer:
- Use "Issued On", "Expires On" instead of "Issued", "Expired"
- Use "X.509 Certificate" for the type, not just "X.509"
- Only sho Named Curve for EC keys
- Under Public Key Information the signature data in hex was shown instead of the actual key data. Show the ASN.1 bytes of SubjectPublicKeyInfo instead.
- Trim extension data fields to avoid spurious newlines
- Simplify DisplayIndentedText()

CertificateViewer: Pretty-print Android Keystore attestation extension.

---

identity-sdjwt/src/commonTest/kotlin/com/android/identity/sdjwt/DisclosureTest.kt
identity-sdjwt/src/commonTest/kotlin/com/android/identity/sdjwt/SdJwtVcTest.kt
identity-sdjwt/src/commonTest/kotlin/com/android/identity/sdjwt/util/JsonWebKeyTest.kt

The previous commit to port identity-sdjwt to KMP didn't port the unit tests. This went under the radar because both the author and the CI wasn't using a Mac. This commit makes the unit test compile and pass on KMP.
Test: ./gradlew identity-sdjwt:check

identity-sdjwt: Fix unit tests.

---

samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/ui/CloudSecureAreaScreen.kt

Make sure that we run in the scope that has `PromptModel`.

Minor fix for coroutine scopes in CloudSecureArea screen in test app.

---

multipaz/src/commonMain/kotlin/org/multipaz/securearea/BatchCreateKeyResult.kt
multipaz/src/commonMain/kotlin/org/multipaz/securearea/SecureArea.kt
multipaz/src/commonMain/kotlin/org/multipaz/securearea/cloud/CloudSecureArea.kt
multipaz/src/commonTest/kotlin/org/multipaz/securearea/SoftwareSecureAreaTest.kt

This adds a new batchCreateKey() method to create many keys with the same algorithm in one shot. The default implementation simply calls createKey() in sequence but implementations may override this. For example, a Cloud Secure Area implementation can use this to minimize the amount of network roundtrips. This also adds the possibility to return an OpenID4VCI key attestation JWT.
Fixes Issue #851 and fixes Issue #852.
Test: New unit test and all unit tests pass.

SecureArea: Add new batchCreateKey() method.

---

appverifier/build.gradle.kts
build.gradle.kts
gradle/libs.versions.toml
jpeg2k/build.gradle.kts
multipaz-mrtd-reader-android/build.gradle.kts
multipaz/SwiftBridge/build.gradle.kts
multipaz/src/javaSharedMain/kotlin/org/multipaz/crypto/CryptoJvm.kt
samples/age-verifier-mdl/build.gradle.kts
samples/age-verifier-mdl/src/main/java/com/android/identity/age_verifier_mdl/TransferHelper.kt
samples/preconsent-mdl/build.gradle.kts
samples/preconsent-mdl/src/main/java/com/android/identity/preconsent_mdl/TransferHelper.kt
samples/simple-verifier/build.gradle.kts
samples/testapp/build.gradle.kts
server/build.gradle.kts
wallet/build.gradle.kts
wallet/src/androidMain/kotlin/org/multipaz/wallet/WalletApplication.kt

+ Updated all Android configurations and the server to use the allWarningsAsErrors = true at compile time.
+ Fixed deprecation errors where needed.
+ removed the KAPT dependency (deprecated in K2).
Tests are passing.

Treat Warnings as Errors.

---

multipaz-android-legacy/src/androidTest/java/com/android/identity/android/mdoc/deviceretrieval/DeviceRetrievalHelperTest.kt
multipaz-android-legacy/src/main/java/com/android/identity/android/legacy/Util.kt
multipaz-android-legacy/src/test/java/com/android/identity/android/legacy/UtilTest.java
multipaz-provisioning/src/main/java/org/multipaz/issuance/hardcoded/IssuingAuthorityState.kt
multipaz/src/commonMain/kotlin/org/multipaz/mdoc/mso/MobileSecurityObjectGenerator.kt
multipaz/src/commonMain/kotlin/org/multipaz/mdoc/mso/MobileSecurityObjectParser.kt
multipaz/src/commonMain/kotlin/org/multipaz/mdoc/response/DeviceResponseParser.kt
multipaz/src/commonTest/kotlin/org/multipaz/mdoc/mso/MobileSecurityObjectGeneratorTest.kt
multipaz/src/commonTest/kotlin/org/multipaz/mdoc/mso/MobileSecurityObjectParserTest.kt
multipaz/src/commonTest/kotlin/org/multipaz/mdoc/response/DeviceResponseGeneratorTest.kt
samples/preconsent-mdl/src/main/java/com/android/identity/preconsent_mdl/MainActivity.kt
samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/TestAppUtils.kt
server/src/main/java/com/android/identity/server/openid4vci/CredentialFactoryMdl.kt
server/src/main/java/com/android/identity/server/openid4vci/CredentialServlet.kt
wallet/src/androidMain/kotlin/org/multipaz/wallet/DocumentModel.kt

Refactor String for Algorithm enum use.
Test: Unit tests amended too and are passing.

Port MobileSecurityObjectGenerator to take Algorithm instead of string.

---

multipaz-android-legacy/src/androidTest/java/com/android/identity/android/legacy/MigrateFromKeystoreICStoreTest.kt
multipaz-csa/src/main/java/org/multipaz/securearea/cloud/CloudSecureAreaServer.kt
multipaz/src/androidInstrumentedTest/kotlin/org/multipaz/securearea/AndroidKeystoreSecureAreaTest.kt
multipaz/src/androidInstrumentedTest/kotlin/org/multipaz/securearea/cloud/CloudSecureAreaTest.kt
multipaz/src/commonMain/kotlin/org/multipaz/cose/Cose.kt
multipaz/src/commonMain/kotlin/org/multipaz/crypto/Crypto.kt
multipaz/src/commonMain/kotlin/org/multipaz/crypto/SecurityException.kt
multipaz/src/commonMain/kotlin/org/multipaz/crypto/SignatureVerificationException.kt
multipaz/src/commonMain/kotlin/org/multipaz/crypto/X509Cert.kt
multipaz/src/commonMain/kotlin/org/multipaz/device/DeviceAttestationAndroid.kt
multipaz/src/commonMain/kotlin/org/multipaz/device/DeviceAttestationIos.kt
multipaz/src/commonMain/kotlin/org/multipaz/mdoc/request/DeviceRequestParser.kt
multipaz/src/commonMain/kotlin/org/multipaz/mdoc/response/DeviceResponseParser.kt
multipaz/src/commonMain/kotlin/org/multipaz/mdoc/vical/SignedVical.kt
multipaz/src/commonMain/kotlin/org/multipaz/sdjwt/SdJwtVerifiableCredential.kt
multipaz/src/commonMain/kotlin/org/multipaz/sdjwt/presentation/SdJwtVerifiablePresentation.kt
multipaz/src/commonMain/kotlin/org/multipaz/securearea/cloud/CloudSecureArea.kt
multipaz/src/commonTest/kotlin/org/multipaz/cose/CoseTests.kt
multipaz/src/commonTest/kotlin/org/multipaz/crypto/EcPrivateKeyTests.kt
multipaz/src/commonTest/kotlin/org/multipaz/crypto/X509CertTests.kt
multipaz/src/commonTest/kotlin/org/multipaz/securearea/SoftwareSecureAreaTest.kt
multipaz/src/iosMain/kotlin/org/multipaz/crypto/CryptoIos.kt
multipaz/src/javaSharedMain/kotlin/org/multipaz/crypto/CryptoJvm.kt
server/src/main/java/com/android/identity/server/openid4vci/jwt.kt

This is the industry-standard and much safer than relying on having the caller check a boolean. Introduce SignatureVerificationException to convey this and derive this from SecurityException to form sealed hierarchy. This is helpful if want to add other security-related exceptions in the future.
Also add a negative test to check that checkSignature() indeed throws the expected exception when trying to verify a signature made with another key.

Crypto: change checkSignature() to throw if signature verification fails.

---

multipaz/src/androidMain/kotlin/org/multipaz/securearea/AndroidKeystoreSecureArea.kt
multipaz/src/commonMain/kotlin/org/multipaz/cbor/DataItem.kt
multipaz/src/commonMain/kotlin/org/multipaz/securearea/AndroidSecureAreaKeyMetadata.kt
multipaz/src/commonMain/kotlin/org/multipaz/securearea/SecureEnclaveAreaKeyMetadata.kt
multipaz/src/commonMain/kotlin/org/multipaz/securearea/cloud/CloudSecureArea.kt
multipaz/src/commonMain/kotlin/org/multipaz/securearea/software/SoftwareSecureArea.kt
multipaz/src/iosMain/kotlin/org/multipaz/securearea/SecureEnclaveSecureArea.kt

Change various SecureArea implementations so that data structures that we put in Storage are serialized using `@CborSerializable` data classes with schemaHash specified. This will help us to be conscious about compatibility going forward.
Actual serialized data in the storage should still be the same (although this was not extensively tested) with the exception of keys in `SoftwareSecureArea` that did not have passphrase (removed duplication storing both `publicKey` and `encodedPublicKey`).
Testing: unit tests and testing using TestApp

Move SecureArea implementations to use @CborSerializable

---

multipaz-compose/build.gradle.kts
multipaz-compose/src/androidMain/kotlin/org/multipaz/compose/camera/Camera.android.kt
multipaz-compose/src/androidMain/kotlin/org/multipaz/compose/permissions/rememberCameraPermissionState.android.kt
multipaz-compose/src/commonMain/kotlin/org/multipaz/compose/camera/Camera.kt
multipaz-compose/src/commonMain/kotlin/org/multipaz/compose/camera/CameraSelector.kt
multipaz-compose/src/commonMain/kotlin/org/multipaz/compose/permissions/rememberCameraPermissionState.kt
multipaz-compose/src/iosMain/kotlin/org/multipaz/compose/camera/Camera.ios.kt
multipaz-compose/src/iosMain/kotlin/org/multipaz/compose/camera/CameraViewController.kt
multipaz-compose/src/iosMain/kotlin/org/multipaz/compose/camera/OrientationListener.kt
multipaz-compose/src/iosMain/kotlin/org/multipaz/compose/permissions/rememberCameraPermissionState.ios.kt
samples/testapp/build.gradle.kts
samples/testapp/src/commonMain/composeResources/values/strings.xml
samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/App.kt
samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/Destinations.kt
samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/ui/CameraScreen.kt
samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/ui/StartScreen.kt

- Implement iOS camera Composable with KMP
- Preliminary frame data processing code placeholders.

Multiplatform camera

---

multipaz/build.gradle.kts
multipaz/consumer-rules.pro

Due to the nature of how BouncyCastle is being used as a Java security provider, R8 strips the BC provider and EC algorithm in the release build because it looks like they're not being used in the project.
Add the necessary ProGuard consumer rules to Multipaz to keep them from being removed.
Test: Release builds of both `:wallet` and `:samples:testapp` now run properly.
Fixes #942.

Prevent R8 from removing BouncyCastle components

---

multipaz/build.gradle.kts
multipaz/src/androidInstrumentedTest/kotlin/org/multipaz/securearea/cloud/CloudSecureAreaTest.kt
multipaz/src/commonMain/kotlin/org/multipaz/securearea/cloud/CloudSecureArea.kt
samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/App.kt
samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/ui/CloudSecureAreaScreen.kt
samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/ui/DocumentStoreScreen.kt
wallet/src/main/java/org/multipaz/wallet/WalletApplication.kt

Instead of using explicit CIO engine in `:multipaz`, inject the `HttpClientEngineFactory` into `CloudSecureArea` and remove the `io.ktor:ktor-client-cio` dependency from the module. This prevents interop issues with projects that already have another engine configured.
In `:samples:testapp`, provide `CIO` as the `HttpClientEngineFactory`, and in `:wallet`, use `Android` engine (as it's already used there).
"Use" `MockEngine` in `CloudSecureAreaTest`; The engine is provided by the factory, as the `HttpClient` object is created, but as it's not being used, it will throw an error should it receive a request.
Test: Manually smoke tested the build, but haven't tested the parts that use the `HttpClient`!
Fixes #941

Inject Ktor engine to Multipaz library

---

multipaz-android-legacy/src/main/java/com/android/identity/android/legacy/HardwareIdentityCredentialStore.java

When this library is imported into google3, it performs more stringent lint checks. This suppresses some false positives.
Test: Build the multipaz-android-legacy module.

Added fixes for warnings found by ErrorProne.

---

multipaz-cbor-rpc/build.gradle.kts

Test: tried `@CborSerializable` in `MpzSecureAreaSample` app and it does generate serialization code.

Publishing rules for multipaz-cbor-rpc.

---

multipaz/build.gradle.kts

With PromptModel we no longer have any compose code in the core library so remove dependencies for that. Also move the temporary dependency on libs.nimbus.oauth2.oidc.sdk from commonMain to javaSharedMain. Delete the dependency on libs.ktor.client.darwin.
Test: Manually ran samples/testpp

multipaz: simplify dependencies

---

multipaz/src/commonMain/kotlin/org/multipaz/mdoc/transport/BleTransportCentralMdoc.kt
multipaz/src/commonMain/kotlin/org/multipaz/mdoc/transport/BleTransportCentralMdocReader.kt
multipaz/src/commonMain/kotlin/org/multipaz/mdoc/transport/BleTransportPeripheralMdoc.kt
multipaz/src/commonMain/kotlin/org/multipaz/mdoc/transport/BleTransportPeripheralMdocReader.kt
multipaz/src/commonMain/kotlin/org/multipaz/mdoc/transport/NfcTransportMdocReader.kt

Allow `CancellationException` to pass through instead of treating it as an error while `MdocTransport.waitForMessage()` execution is being suspended, waiting for the incoming message channel to send new values. This prevents the transport from being erroneously marked as failed, as the cancellation doesn't have any side effects in the presentation session itself.
Test: Manually tested testapp proximity sharing
Fixes #949

Allow MdocTransport.waitForMessage() cancellation

---

samples/testapp/src/androidMain/kotlin/com/android/identity/testapp/PlatformAndroid.kt
samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/App.kt
samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/Platform.kt
samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/ui/CloudSecureAreaScreen.kt
samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/ui/DocumentStoreScreen.kt
samples/testapp/src/iosMain/kotlin/com/android/identity/testapp/PlatformIos.kt

CIO doesn't support TLS for native so use Darwin on iOS.
Test: Manually tested, CloudSecureArea works on iOS again.

testapp: Use platform-specific HttpClientEngineFactory.

---

multipaz/src/commonMain/kotlin/org/multipaz/mdoc/transport/BleTransportCentralMdoc.kt
multipaz/src/commonMain/kotlin/org/multipaz/mdoc/transport/BleTransportCentralMdocReader.kt
multipaz/src/commonMain/kotlin/org/multipaz/mdoc/transport/BleTransportPeripheralMdoc.kt
multipaz/src/commonMain/kotlin/org/multipaz/mdoc/transport/BleTransportPeripheralMdocReader.kt
multipaz/src/commonMain/kotlin/org/multipaz/mdoc/transport/MdocTransport.kt
multipaz/src/commonMain/kotlin/org/multipaz/mdoc/transport/NfcTransportMdocReader.kt

Add new protected `Throwable.wrapUnlessCancellationException()` extension method to `MdocTransport` that can be used to map exceptions to `MdocTransportExceptions` with a supplied message, unless it's a `CancellationException`, and replace the existing `MdocTransport` logic to use it instead of blindly mapping every exception.
But, to avoid swallowing the BLE stack errors reported by the `onError()` callback, use the Ktor `unwrapCancellationException()` helper to find them (and wrap them).
Replace `CoroutineScope(currentCoroutineContext())` with `coroutineScope` to avoid the `onJoin()` dance and remove the coroutines-internal `getCancellationException()` call. The cancellation exception will be thrown anyway because `coroutineScope` is suspended while the launched job is running.
Test: …

Avoid mapping CancellationException in MdocTransports

---

TESTING.md
server/src/main/webapp/verifier.js

Hit a runtime error during local doc verification and traced it to a missing Chrome flag. Added a note in the README and a runtime check in dcRequestCredential to guide devs to enable chrome://flags#web-identity-digital-credentials.
Didn’t open an issue first — let me know if that’s needed. Thanks!

Add guidance and runtime check for Digital Credentials API flag

---

multipaz/src/commonMain/kotlin/org/multipaz/asn1/OID.kt
samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/App.kt
server/src/main/java/com/android/identity/wallet/server/VerifierServlet.kt
server/src/main/webapp/verifier.js

Identified during OpenID test event.
- Switch to x509_san_dns for W3C DC API with OpenID and include dNSName in subjectAltName X.509 extension in reader cert as required
- Use a serial number in IACA certificate with sufficient entropy
- Add expected_origins for OpenID4VP signed requests, as required
Test: Manually tested and tested in OpenID interop event

Interop fixes.

---

multipaz-android-legacy/src/main/java/com/android/identity/android/legacy/CredentialData.java
multipaz/src/commonMain/kotlin/org/multipaz/asn1/ASN1BitString.kt
multipaz/src/commonMain/kotlin/org/multipaz/asn1/ASN1OctetString.kt
multipaz/src/commonMain/kotlin/org/multipaz/asn1/ASN1RawObject.kt
multipaz/src/commonMain/kotlin/org/multipaz/prompt/SinglePromptModel.kt

This ports some fixes upstream so we don't need to reapply them whenever we mirror this to an environment that uses ErrorProne.
There are 3 different warnings this fixes:
- Unused return values.
- Hashing an array object instead of the contents of the array (fixed this by using contentHashCode() instead).
- Calling a suspend function in a finally block (fixed this by wrapping in a withContext(NonCancellable) block).
Test: testapp, creating documents
Test: testapp, mdoc sharing an mdl using NFC
Test: testapp, mdoc sharing an mdl a QR code

Fix some more ErrorProne lint warnings.

---

.gitignore
DEVELOPER-ENVIRONMENT.md
README.md
samples/testapp/iosApp/DeveloperConfig.xcconfig.template
samples/testapp/iosApp/TestApp.xcodeproj/project.pbxproj

This new configuration file is in .gitignore so with this change developers will need to set it only once and won't need to unset it before committing.
Also add DEVELOPER-ENVIRONMENT.md file to help explain what needs to be done to set up a developer environment.

Move DEVELOPMENT_TEAM into separate configuration file.

---

gradle/libs.versions.toml
multipaz-android-legacy/build.gradle.kts
multipaz-android-legacy/src/main/java/com/android/identity/android/legacy/AccessControlProfile.java
multipaz-android-legacy/src/main/java/com/android/identity/android/legacy/CredentialData.java
multipaz-android-legacy/src/main/java/com/android/identity/android/legacy/KeystoreWritableIdentityCredential.java
multipaz-android-legacy/src/main/java/com/android/identity/android/legacy/PersonalizationData.java
multipaz-android-legacy/src/main/java/com/android/identity/android/legacy/SimpleResultData.java
multipaz-android-legacy/src/main/java/com/android/identity/android/legacy/Util.kt
multipaz-cbor-rpc/src/main/kotlin/org/multipaz/graphhash/EdgeKind.kt
multipaz/src/androidMain/AndroidManifest.xml
multipaz/src/androidMain/kotlin/org/multipaz/device/DeviceCheck.android.kt
multipaz/src/commonMain/kotlin/org/multipaz/device/DeviceCheck.kt

The main change is integrating errorprone annotations (in particular, CanIgnoreReturnValue). These fix some of the last remaining errorprone warnings, though we still don't have errorprone set up to check this repository (there are some challenges setting it up for Gradle + Android, but maybe an upcoming PR can address these).
In addition, the other build system needs a (minimal) AndroidManifest.xml for the multipaz library, and there are a few other minor warnings this addresses.
Test: Android Studio: Make Project
Test: ./gradlew connecedCheck

More changes to clean up lint warnings and prep for other build systems.

---

.github/workflows/unit-test.yml

Upload the logcat from the device after connectedCheck test to allow debugging.
- _none needed_

Uploading logcat logs after unit tests

---

README.md
multipaz/src/commonMain/kotlin/org/multipaz/asn1/ASN1Integer.kt
multipaz/src/commonMain/kotlin/org/multipaz/trustmanagement/TrustManagerUtil.kt
multipaz/src/commonMain/kotlin/org/multipaz/trustmanagement/TrustPoint.kt
multipaz/src/commonTest/kotlin/org/multipaz/trustmanagement/TrustManagerTest.kt
samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/App.kt
samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/TestAppPresentmentSource.kt
samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/ui/DocumentStoreScreen.kt

- Introduce ASN1Integer.fromRandom() and use this for serial numbers instead of hard-coding a serial number (!).
- Add helpful debug information in TrustManager errors.
- Log the TrustManager error if set.
- Add more helpful toString() method for TrustPoint.
- Change the displayName for our built-in TrustPoints for own certificates.
- Update DS subject name.
- Mention https://apps.multipaz.org in README.md.

More fixes for issues found during interop testing.

---

multipaz-models/src/commonMain/kotlin/org/multipaz/models/presentment/digitalCredentialsPresentment.kt
samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/App.kt
samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/ui/ProvisioningTestScreen.kt
server/src/main/java/org/multipaz/server/openid4vci/Openid4VpResponseServlet.kt
server/src/main/java/org/multipaz/server/openid4vci/openid4vp.kt
server/src/main/java/org/multipaz/wallet/server/VerifierServlet.kt

Minimal PR that brings presentation-during-issuance implementation to the current spec, in particular with DCQL. (More work will follow up to integrate PresentmentModel with the ProvisioningModel, in particular to select potentially matching credential(s) more intellegently).
Testing: tested openid4vci issuance workflow with our own openid4vci server implementation.

Fixes for presentation during issuance workflow.

---

multipaz-android-legacy/src/main/java/com/android/identity/android/legacy/AccessControlProfile.java
multipaz-android-legacy/src/main/java/com/android/identity/android/legacy/AccessControlProfileId.java
multipaz-android-legacy/src/main/java/com/android/identity/android/legacy/IdentityCredential.java
multipaz-android-legacy/src/main/java/com/android/identity/android/legacy/KeystoreIdentityCredential.java
multipaz-android-legacy/src/main/java/com/android/identity/android/legacy/PersonalizationData.java
multipaz-android-legacy/src/main/java/com/android/identity/android/mdoc/deviceretrieval/DeviceRetrievalHelper.kt
multipaz-android-legacy/src/main/java/com/android/identity/android/mdoc/transport/GattClient.kt
multipaz/src/commonMain/kotlin/org/multipaz/mdoc/request/DeviceRequestParser.kt
multipaz/src/commonMain/kotlin/org/multipaz/mdoc/response/DeviceResponseGenerator.kt
multipaz/src/commonTest/kotlin/org/multipaz/mdoc/request/DeviceRequestGeneratorTest.kt

The last import into g3 was commit ce6cec763e015a34439af9fd5d641600a9fa5014, from 2023-04-08. This PR takes all the g3 changes that have been done since that import and ports them to the latest upstream version.
There were many conflicts, mostly from renamed files or files that had been converted from Java to Kotlin. The g3 versions had changed the package namespace, which resulted in a number of unnecessary merge changes. This PR ignores the g3 package name changes.
The coseSign1CheckNoDuplicateHeaderParams function that had been added to multipaz-android-legacy/.../Util.kt needed to be moved to where it was used in DeviceRequestParser.kt, because that's in the core library, multipaz. It was also converted to be more Kotlin-esque and use standard functions that exist in DataItem. It …

Upstreamed differences in g3 between the imported version and the latest.

---

multipaz-cbor-rpc/src/main/kotlin/org/multipaz/processor/CborSymbolProcessor.kt
multipaz/src/commonMain/kotlin/org/multipaz/securearea/AndroidSecureAreaKeyMetadata.kt
multipaz/src/commonMain/kotlin/org/multipaz/securearea/SecureEnclaveAreaKeyMetadata.kt
multipaz/src/commonMain/kotlin/org/multipaz/securearea/cloud/CloudSecureArea.kt
multipaz/src/commonMain/kotlin/org/multipaz/securearea/software/SoftwareSecureArea.kt
multipaz/src/jvmTest/kotlin/org/multipaz/rpc/CborSerializationTest.kt

Calculation for enums schema hash now only uses enum entry names. This required adjusting some existing schema hashes (in this case hash update does not mean serialization incompatibility!) 
Testing: added a set of single-field data classes to test schema hash calculation.

Tightened schema hash calculation for enums.

---

multipaz-models/src/commonMain/kotlin/org/multipaz/models/presentment/digitalCredentialsPresentment.kt
samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/provisioning/model/ProvisioningModel.kt
server/src/main/java/org/multipaz/models/verifier/Openid4VpVerifierModel.kt
server/src/main/java/org/multipaz/server/openid4vci/AuthorizeServlet.kt
server/src/main/java/org/multipaz/server/openid4vci/CredentialRequestServlet.kt
server/src/main/java/org/multipaz/server/openid4vci/Openid4VpResponseServlet.kt
server/src/main/java/org/multipaz/server/openid4vci/messages.kt
server/src/main/webapp/openid4vci/authorize.js

Created VerifierModel and migrated Openid4VCI code to use it for both browser-based and presenation-during-issuance workflows.
Testing: openid4vci provisioning using both workflows.

First cut of VerifierModel.

---

multipaz/src/androidMain/kotlin/org/multipaz/util/Logger.android.kt
multipaz/src/commonMain/kotlin/org/multipaz/util/Logger.kt
multipaz/src/iosMain/kotlin/org/multipaz/util/Logger.ios.kt
multipaz/src/jvmMain/kotlin/org/multipaz/util/Logger.jvm.kt

Restore the old `LogPrinter` interface to `Logger` and allow overriding the default printer with a new `logPrinter` property. The default printer is provided by slightly changed `getPlatformLogPrinter()` expect function, which now returns an platform-specific implementation of the interface.
Test: ./gradlew multipaz:check multipaz:connectedCheck
Test: Manually tested that testapp outputs logs & our implementation is able to override logger
Fixes #978

Restore custom LogPrinter functionality

---

multipaz-backend-server/src/main/resources/resources/android_trusted_app_signatures.txt
multipaz-backend-server/src/main/resources/resources/android_trusted_package_names.txt
multipaz/src/androidMain/kotlin/org/multipaz/applinks/AppLinksCheck.kt
scripts/generate-assetlinks-json.sh

We should be able to use the same lists for Android attestation validation in our wallet back-end.
Testing: tested with my own server.

Android signing key digests for app links.

---

multipaz-openid4vci-server/src/main/java/org/multipaz/openid4vci/credential/CredentialFactory.kt
multipaz-openid4vci-server/src/main/java/org/multipaz/openid4vci/request/credential.kt
multipaz/src/commonMain/kotlin/org/multipaz/sdjwt/SdJwtVerifiableCredential.kt
multipaz/src/commonMain/kotlin/org/multipaz/sdjwt/vc/JwtHeader.kt
samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/provisioning/model/ProvisioningModel.kt
samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/provisioning/openid4vci/Openid4VciIssuingAuthorityState.kt
samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/provisioning/openid4vci/Openid4VciProofingState.kt
samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/provisioning/openid4vci/OpenidUtil.kt
samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/provisioning/openid4vci/RequestCredentialsUsingProofOfPossession.kt
samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/provisioning/openid4vci/openid4VciIssuerMetadata.kt

Tweaks for openid4vci server and client code to fix discrepancies with the current spec.
Test: issuance for all credential types with our own server and with bundesdruckerei sample server.

Tweaks for openid4vci server and client code

---

multipaz/src/androidMain/kotlin/org/multipaz/mdoc/transport/BleCentralManagerAndroid.kt
multipaz/src/androidMain/kotlin/org/multipaz/mdoc/transport/BlePeripheralManagerAndroid.kt
multipaz/src/jvmTest/kotlin/org/multipaz/crypto/JsonWebEncryptionTests.kt
multipaz/src/jvmTest/kotlin/org/multipaz/crypto/JsonWebSignatureTests.kt

Set the wait condition before actually writing the value in the characteristic, as the callback that reads the value might be called before the value is actually set.
Test: ./gradlew multipaz:check multipaz:connectedCheck
Test: Manually tested local build with our wallet implementation
Fixes #1019

Fix data race in BLE GATT implementation

---

multipaz-models/src/commonMain/kotlin/org/multipaz/models/presentment/digitalCredentialsPresentment.kt
multipaz-openid4vci-server/src/main/java/org/multipaz/models/verifier/Openid4VpVerifierModel.kt
multipaz/SwiftBridge/SwiftBridge/SwiftBridge.swift
multipaz/build.gradle.kts
multipaz/src/commonMain/kotlin/org/multipaz/crypto/Crypto.kt
multipaz/src/commonMain/kotlin/org/multipaz/crypto/JsonWebEncryption.kt
multipaz/src/commonMain/kotlin/org/multipaz/crypto/JsonWebSignature.kt
multipaz/src/commonMain/kotlin/org/multipaz/sdjwt/SdJwt.kt
multipaz/src/commonMain/kotlin/org/multipaz/sdjwt/SdJwtKb.kt
multipaz/src/commonMain/kotlin/org/multipaz/util/Compression.kt
multipaz/src/commonTest/kotlin/org/multipaz/crypto/CryptoTests.kt
multipaz/src/commonTest/kotlin/org/multipaz/crypto/JsonWebEncryptionTests.kt
multipaz/src/commonTest/kotlin/org/multipaz/crypto/JsonWebSignatureTests.kt
multipaz/src/commonTest/kotlin/org/multipaz/util/CompressionTests.kt
multipaz/src/iosMain/kotlin/org/multipaz/crypto/CryptoIos.kt
multipaz/src/iosMain/kotlin/org/multipaz/util/Compression.ios.kt
multipaz/src/javaSharedMain/kotlin/org/multipaz/crypto/CryptoJvm.kt
multipaz/src/javaSharedMain/kotlin/org/multipaz/util/Compression.jvm.kt
multipaz/src/jvmTest/kotlin/org/multipaz/crypto/JsonWebEncryptionTestsNimbus.kt
multipaz/src/jvmTest/kotlin/org/multipaz/crypto/JsonWebSignatureTestsNimbus.kt
server/src/main/java/org/multipaz/wallet/server/VerifierServlet.kt

This means we no longer have to depend on the Nimbus library for the core Multipaz library on JVM. Do keep this library around and use it in the JVM-specific tests to check that our implementation interoperates.
Other changes:
- Use `String` instead of `JsonElement` in both JsonWebEncryption and JsonWebSignature APIs - it's cleaner this way since we're always using compact serialization and have no plans to support anything else.
- Add support for AAD in `Crypto.encrypt()` and `Crypto.decrypt()` APIs along with new unit tests using NIST test vectors.
- Add new `inflate()` and `deflate()` with JVM and iOS implementations and unit tests.

Port JsonWebEncryption to Kotlin Multiplatform.

---

multipaz/src/commonMain/kotlin/org/multipaz/crypto/EcPrivateKey.kt
multipaz/src/commonMain/kotlin/org/multipaz/crypto/EcPrivateKeyDoubleCoordinate.kt
multipaz/src/commonMain/kotlin/org/multipaz/crypto/EcPrivateKeyOkp.kt
multipaz/src/commonMain/kotlin/org/multipaz/crypto/EcPublicKeyDoubleCoordinate.kt
multipaz/src/commonMain/kotlin/org/multipaz/crypto/EcPublicKeyOkp.kt
multipaz/src/commonTest/kotlin/org/multipaz/crypto/CryptoTests.kt

We recently this on EcPublicKey, for symmetry also add it to EcPrivateKey. Also add tests to check roundtrips for all curves.
Test: New unit tests.

Add toJwk() and fromJwk() to EcPrivateKey.

---

multipaz-compose/src/androidMain/kotlin/org/multipaz/compose/Util.android.kt
multipaz-compose/src/androidMain/kotlin/org/multipaz/compose/camera/Camera.android.kt
multipaz-compose/src/commonMain/kotlin/org/multipaz/compose/Util.kt
multipaz-compose/src/commonMain/kotlin/org/multipaz/compose/camera/CameraFrame.kt
multipaz-compose/src/iosMain/kotlin/org/multipaz/compose/Util.ios.kt
multipaz-compose/src/iosMain/kotlin/org/multipaz/compose/camera/Camera.ios.kt
multipaz-compose/src/iosMain/kotlin/org/multipaz/compose/camera/CameraImage.ios.kt
multipaz-mlkit/src/androidMain/kotlin/org/multipaz/facedetection/FaceDetector.android.kt
multipaz-mlkit/src/commonMain/composeResources/values/strings.xml
multipaz-mlkit/src/commonMain/kotlin/org/multipaz/selfiecheck/HeadRotationDirection.kt
multipaz-mlkit/src/commonMain/kotlin/org/multipaz/selfiecheck/SelfieCheck.kt
multipaz-mlkit/src/commonMain/kotlin/org/multipaz/selfiecheck/SelfieCheckStep.kt
multipaz-mlkit/src/commonMain/kotlin/org/multipaz/selfiecheck/SelfieCheckViewModel.kt
multipaz-mlkit/src/iosMain/kotlin/org/multipaz/facedetection/FaceDetector.ios.kt
samples/testapp/src/commonMain/composeResources/values/strings.xml
samples/testapp/src/commonMain/kotlin/org/multipaz/testapp/App.kt
samples/testapp/src/commonMain/kotlin/org/multipaz/testapp/Destinations.kt
samples/testapp/src/commonMain/kotlin/org/multipaz/testapp/ui/FaceDetectionScreen.kt
samples/testapp/src/commonMain/kotlin/org/multipaz/testapp/ui/SelfieCheckScreen.kt
samples/testapp/src/commonMain/kotlin/org/multipaz/testapp/ui/StartScreen.kt

Implement Selfie Check and capture flow.
- Use directions to navigate the user through several selfie liveness checks. 
- Confirm checks passing using MLKit.
- Capture selfie bitmap if checks passed.
Tests: manually verify happy and unhappy paths using TestApp on Android and iOS.
Ticket: #1071

Selfie Check and Capture Use case

---

samples/testapp/src/commonMain/kotlin/org/multipaz/testapp/provisioning/model/ProvisioningModel.kt

Also some minor/cosmetic fixes to `ProvisioningModel`.
Test: manually tested with testapp

Mark document as provisioned when credentials are issued

---

multipaz/src/androidMain/kotlin/org/multipaz/mdoc/transport/BleCentralManagerAndroid.kt

Older Android implementations below API 33 may still call the deprecated `onCharacteristicRead()` and `onCharacteristicChanged()` methods, ignoring the new memory-safe callbacks. Fix the issue by routing the deprecated function calls to the new callbacks.
Test: ./gradlew test connectedCheck
Test: Manually tested with Finnish EUDI Demo implementation on a previously non-functioning Android 9 device

Fix BLE GATT on older Android devices

---

multipaz-openid4vci-server/src/main/java/org/multipaz/openid4vci/request/finishAuthorization.kt

Updated the HTML: originally, there was a "Continue" button that users had to click to trigger a redirect. Now, an automatic redirect is implemented. If the auto-redirect fails, users can still manually click the button to proceed.
Depends on Peter's [feedback](https://discord.com/channels/1022962884864643214/1179828955717574707/1389853010682974279), merge the improvement

feat(openid4vci-server): improve HTML to auto-redirect without continue button click

---

multipaz-doctypes/src/commonMain/kotlin/org/multipaz/documenttype/knowntypes/DrivingLicense.kt
multipaz-doctypes/src/commonMain/kotlin/org/multipaz/documenttype/knowntypes/EUPersonalID.kt
multipaz-doctypes/src/commonMain/kotlin/org/multipaz/documenttype/knowntypes/PhotoID.kt
multipaz/src/androidMain/kotlin/org/multipaz/mdoc/transport/BleCentralManagerAndroid.kt
multipaz/src/androidMain/kotlin/org/multipaz/mdoc/transport/BlePeripheralManagerAndroid.kt
multipaz/src/commonMain/kotlin/org/multipaz/documenttype/DocumentType.kt
multipaz/src/commonMain/kotlin/org/multipaz/documenttype/MdocCannedRequest.kt
multipaz/src/iosMain/kotlin/org/multipaz/mdoc/transport/BleCentralManagerIos.kt
multipaz/src/iosMain/kotlin/org/multipaz/mdoc/transport/BlePeripheralManagerIos.kt
samples/testapp/src/commonMain/kotlin/org/multipaz/testapp/App.kt
samples/testapp/src/commonMain/kotlin/org/multipaz/testapp/TestAppUtils.kt
samples/testapp/src/commonMain/kotlin/org/multipaz/testapp/ui/IsoMdocProximityReadingScreen.kt

- Add support for ZKP in DocumentType.addSampleRequest() and define ZKP requests for mDL, PhotoID, and EU PID. Remove the custom "Use Zero Knowledge" checkbox in the testapp reader screen since this is no longer needed.
- Use ZkDocumentData.msoX5chain to validate the issuer.
- Fix IsoMdocProximityReadingScreen to actually show the issuer trust-point validation, both for normal and ZKP responses.
- Fix registration of testapp reader root so reader auth using testapp to testapp works again.

ZKP: Minor fixes.

---

README.md
multipazctl/build.gradle.kts
multipazctl/src/main/java/org/multipaz/multipazctl/MultipazCtl.kt

Also change build rules to make it possible to create a fat jar and provide instructions in README.md for how to set up a `multipazctl` wrapper.

multipazctl: add generateReaderCert and printJwk verbs.

---

multipaz/src/commonMain/kotlin/org/multipaz/trustmanagement/TrustEntry.kt
multipaz/src/commonMain/kotlin/org/multipaz/trustmanagement/TrustManagerLocal.kt
multipaz/src/commonMain/kotlin/org/multipaz/trustmanagement/TrustMetadata.kt
multipaz/src/commonTest/kotlin/org/multipaz/trustmanagement/TrustManagerTest.kt

For `TrustEntry`, move `id` and `timeAdded` fields out of the public interface and mark it as `CborSerializable`. This allows for applications to nicely reuse these types for e.g. sending a list of trusted IACA certs and VICALs from the server-side to an app.
Test: New unit test and all unit test pass.

TrustManagerLocal: Add deleteAll() and make TrustEntry reusable.

---

samples/testapp/src/androidMain/kotlin/org/multipaz/testapp/PlatformAndroid.kt

On some Android devices using both face / fingerprint and where face isn't available (if e.g. not enough light) authenticating with fingerprint will cause the biometric prompt for face to appear again which is counterintuitive.
Notably this only happens when using ECDH for DeviceKey (e.g. only in-person, not via Credman since that's always ECDSA) and the root cause is that the timeout for the ECDH keys are only 1 second. This should be enough but the problem is that either Keymint or the Biometric subsystem (likely the latter) sets the timestamp to when the authentication event _began_, not when it ended.
This bug only manifests itself on my Pixel 9 Pro Fold it doesn't happen on the Pixel 8 Pro so it looks like this is a problem in the biometric stack for the former.
Of course the root …

Work around bug in Android Keystore ECDH / BiometricPrompt.

---

multipaz/src/iosMain/kotlin/org/multipaz/nfc/scanNfcTag.ios.kt

On iOS when the user dismisses the NFC scanning dialog we end up dereferencing a null pointer which causes PromptDismissedException not to be propagated to the application.
Test: Manually tested on iOS.

NFC: Propagate PromptDismissedException on iOS.

---

multipaz-models/src/commonMain/kotlin/org/multipaz/models/openid/OpenID4VP.kt
multipaz-verifier-server/src/main/java/org/multipaz/verifier/request/verifier.kt

We were using `OpenID4VPDCAPIHandover` but for URI schemes it's supposed to just be "OpenID4VPHandover". Fixes #1174.

OpenID4VP: Fix handover for URI schemes.

---

multipaz-doctypes/src/commonMain/kotlin/org/multipaz/documenttype/knowntypes/PhotoID.kt

The age_over_18 attribute in namespace ISO_23220_2 appears to be defined twice. It also appears at line 159 (after this delete). I've removed the first copy.

Remove duplicate attribute in PhotoID.kt

---

multipaz-doctypes/src/commonMain/kotlin/org/multipaz/documenttype/knowntypes/IDPass.kt
multipaz-verifier-server/src/main/java/org/multipaz/verifier/request/verifier.kt
multipaz-verifier-server/src/main/resources/resources/www/index.html
multipaz/src/commonMain/kotlin/org/multipaz/documenttype/DocumentType.kt
multipaz/src/commonMain/kotlin/org/multipaz/documenttype/MdocDocumentType.kt
samples/testapp/src/commonMain/kotlin/org/multipaz/testapp/App.kt

Additionally, include the two ID pass IACA certificates available on [Google's website](https://developers.google.com/wallet/identity/verify/supported-issuers-iaca-certs) in our issuer trust manager.
Also update the language on the verifier front page including calling out that it's a test website and no data is collected. Modify verifier.kt so no responses are logged on the server-side.

Add Google Wallet ID pass doctype.

---

multipaz-cbor-rpc/src/main/kotlin/org/multipaz/processor/CborSymbolProcessor.kt
multipaz/src/commonMain/kotlin/org/multipaz/cbor/annotation/CborSerializable.kt
multipaz/src/commonMain/kotlin/org/multipaz/securearea/PassphraseConstraints.kt

KSP sometimes does not return us all annotated classes in a compilation unit. Detect this situation and work around it.
Also allow scoping instead of name prefix/suffix for sealed class hierarchies. This quiets a long-standing annoying warning.
Use schemaHash instead of schemaId for stability check.
Functionally, there should be no changes, as generated code should not change at all.

KSP fixes.

---

samples/testapp/src/androidMain/AndroidManifest.xml

Add comments explaining HTTPS app links, custom URI schemes, and OpenID4VCI schemes with examples and implementation guidance.
Why This Change is Needed
Developers don't know how to implement custom URI schemes because the AndroidManifest.xml shows intent filters but provides no guidance on handling custom intents in MainActivity or testing them.
This adds documentation explaining:
* Purpose of each intent filter type
* Example URLs
* Cross-references to related code
* Changed the order to reflect https (default) and custom scheme
Now developers can understand both HTTPS and custom schemes for their own apps.
- [N/A] Appropriate changes to README are included in PR
CC - @hanluOMH @VishnuSanal

docs: Add developer-friendly deep link comments to `AndroidManifest.xml`

---

multipaz-compose/src/androidMain/kotlin/org/multipaz/compose/permissions/rememberBluetoothEnabledState.android.kt
multipaz-compose/src/commonMain/kotlin/org/multipaz/compose/permissions/rememberBluetoothEnabledState.kt
multipaz-compose/src/iosMain/kotlin/org/multipaz/compose/permissions/rememberBluetoothEnabledState.ios.kt
samples/testapp/src/commonMain/kotlin/org/multipaz/testapp/ui/IsoMdocMultiDeviceTestingScreen.kt
samples/testapp/src/commonMain/kotlin/org/multipaz/testapp/ui/IsoMdocProximityReadingScreen.kt
samples/testapp/src/commonMain/kotlin/org/multipaz/testapp/ui/IsoMdocProximitySharingScreen.kt

one issue I was facing was that the `rememberBluetoothPermissionState` composable doesn’t take into account whether the device has bluetooth turned on or not. I expected the composable to handle all the permission related nuances. I have created a simple implementation in the above branch - it is still buggy (doesn’t auto update the state). can I get a confirmation on whether this approach is right? and we can have this feature in `rememberBluetoothPermissionState`?
cc: @davidz25 @dzuluaga

add `rememberBluetoothEnabledState` composable to keep track of state of bluetooth state on device

---

multipaz-models/src/commonMain/kotlin/org/multipaz/models/presentment/mdocPresentment.kt
multipaz/src/commonMain/kotlin/org/multipaz/mdoc/sessionencryption/EReaderKey.kt
multipaz/src/commonMain/kotlin/org/multipaz/mdoc/sessionencryption/SessionEncryption.kt
samples/testapp/src/commonMain/kotlin/org/multipaz/testapp/multidevicetests/MultiDeviceTestsServer.kt

This PR addresses the issue described in #1133 by modifying `SessionEncryption.getEReaderKey` to return both:
- the decoded `EcPublicKey`
- the original encoded COSE key as a `ByteArray`
The intention is to allow consumers to use the original encoded bytes when constructing the `SessionTranscript`, preserving the exact byte-level encoding and helping avoid interoperability issues.
While this approach appears to resolve the encoding mismatch and we are using it in our Android wallet application right now, it may not be the final or ideal solution.
Feedback and suggestions on improving this design are welcome to ensure it aligns well with the library’s architecture and usage patterns.

Use original eReaderKey bytes for encodedSessionTranscript

---

multipaz-cbor-rpc/src/main/kotlin/org/multipaz/processor/CborSymbolProcessor.kt
multipaz/src/androidInstrumentedTest/kotlin/org/multipaz/securearea/AndroidKeystoreSecureAreaTest.kt
multipaz/src/androidMain/kotlin/org/multipaz/securearea/AndroidKeystoreCreateKeySettings.kt
multipaz/src/androidMain/kotlin/org/multipaz/securearea/AndroidKeystoreSecureArea.kt
multipaz/src/commonMain/kotlin/org/multipaz/crypto/Algorithm.kt
multipaz/src/commonMain/kotlin/org/multipaz/securearea/AndroidSecureAreaKeyMetadata.kt
multipaz/src/commonMain/kotlin/org/multipaz/securearea/SecureEnclaveAreaKeyMetadata.kt
multipaz/src/commonMain/kotlin/org/multipaz/securearea/cloud/CloudSecureArea.kt
multipaz/src/commonMain/kotlin/org/multipaz/securearea/software/SoftwareSecureArea.kt
samples/testapp/src/androidMain/kotlin/org/multipaz/testapp/ui/AndroidKeystoreSecureAreaScreenAndroid.kt

Introduce Algorithm.ANDROID_KEYSTORE_ATTEST_KEY which can be used to create an Android Keystore Attest Key which can be used together with existing AndroidKeystoreCreateKeySettings.setAttestKeyAlias(). This is an improvement as up to now the application would need to use the native Android APIs to create an Attest Key.
Also change KeyInfo.attestation for a key using an attest key. The previous behavior was that the attestation only contained a single certificate and the new behavior is that the attest key's attestation chain is appended at the end. This way the attestation won't have to be special cased and it goes all the way up to the attestation root, like normal keys.
Also add new items in Android Keystore Secure Area screen in testapp for this.
Finally, also change error message in …

AndroidKeystore: Improve support for Attest Keys.

---

multipaz-compose/src/androidMain/kotlin/org/multipaz/compose/mdoc/MdocNdefService.kt
multipaz-compose/src/androidMain/kotlin/org/multipaz/compose/prompt/ScanNfcTagPromptDialog.kt
multipaz-compose/src/commonMain/kotlin/org/multipaz/compose/presentment/MdocProximityQrPresentment.kt
multipaz/src/androidMain/kotlin/org/multipaz/nfc/NfcIsoTagAndroid.kt
multipaz/src/androidMain/kotlin/org/multipaz/nfc/scanNfcTag.android.kt
multipaz/src/androidMain/kotlin/org/multipaz/prompt/AndroidPromptModel.kt
multipaz/src/commonMain/kotlin/org/multipaz/mdoc/nfc/scanNfcMdocReader.kt
multipaz/src/commonMain/kotlin/org/multipaz/mdoc/transport/NfcTransportMdocReader.kt
multipaz/src/commonMain/kotlin/org/multipaz/nfc/NfcIsoTag.kt
multipaz/src/commonMain/kotlin/org/multipaz/nfc/scanNfcTag.kt
multipaz/src/commonTest/kotlin/org/multipaz/mdoc/nfc/MdocNfcEngagementHelperTest.kt
multipaz/src/commonTest/kotlin/org/multipaz/mdoc/transport/NfcTransportTests.kt
multipaz/src/iosMain/kotlin/org/multipaz/nfc/NfcIsoTagIos.kt
multipaz/src/iosMain/kotlin/org/multipaz/nfc/scanNfcTag.ios.kt
multipaz/src/jvmMain/kotlin/org/multipaz/nfc/scanNfcTag.jvm.kt
samples/testapp/src/commonMain/kotlin/org/multipaz/testapp/App.kt
samples/testapp/src/commonMain/kotlin/org/multipaz/testapp/Destinations.kt
samples/testapp/src/commonMain/kotlin/org/multipaz/testapp/ShowResponseMetadata.kt
samples/testapp/src/commonMain/kotlin/org/multipaz/testapp/ui/DcRequestScreen.kt
samples/testapp/src/commonMain/kotlin/org/multipaz/testapp/ui/IsoMdocProximityReadingScreen.kt
samples/testapp/src/commonMain/kotlin/org/multipaz/testapp/ui/NfcScreen.kt
samples/testapp/src/commonMain/kotlin/org/multipaz/testapp/ui/ShowResponse.kt
samples/testapp/src/commonMain/kotlin/org/multipaz/testapp/ui/ShowResponseScreen.kt

Currently `scanNfcMdocReader()` returns the result in a lambda with the semantics that if the created transport was for NFC data transfer, that lambda is called in a separate coroutine and the caller is expected to perform all data transfer in this call.
This is a somewhat unintuitive and even undesirable API as an Identity Reader app will typically want to switch to another screen as soon as data transfer is initiated and the fact that the launched coroutine is canceled with switching to another screen this doesn't work in practice for 18013-5 NFC data transfer.
Thus, change the API of `scanNfcTag()` to return the result in the return value and make the caller responsible for closing the `NfcIsoTag`. This change allows for deferred processing even after `scanNfcTag()` returns. Use this …

NFC: Simplify NFC reading and allow using the tag after the scanning prompt.

---

multipaz-doctypes/src/commonMain/kotlin/org/multipaz/documenttype/knowntypes/PhotoID.kt
multipaz-models/src/androidInstrumentedTest/kotlin/org/multipaz/models/presentment/MatcherTest.kt
multipaz-models/src/commonTest/kotlin/org/multipaz/models/presentment/DocumentStoreTestHarness.kt
multipaz-provisioning/src/main/java/org/multipaz/legacyprovisioning/hardcoded/IssuingAuthorityState.kt
multipaz-verifier-server/src/main/resources/resources/www/verifier.js

Latest draft of ISO 23220-4 changed some of the data elements, in particular family_name_unicode is now family_name and ditto for other data elements. Went through the entire set of data elements and updated them. Also cleaned up PhotoID.kt in general and used a for-loop to produce all age attestations.
Fixes #1145.

PhotoID: Update data elements to match latest draft.
