openwallet-foundation/multipaz

identitycredential/src/androidTest/java/androidx/security/identity/cts/EphemeralKeyTest.java
A small change to the initial counter values to pass the test. Btw, why not start the counters at 0 instead?
=> Fix EphemeralKeyTest

appverifier/src/main/java/com/android/mdl/appreader/document/RequestDocument.kt, appverifier/src/main/java/com/android/mdl/appreader/document/RequestMulti003.kt, appverifier/src/main/java/com/android/mdl/appreader/fragment/RequestOptionsFragment.kt, appverifier/src/main/res/layout/fragment_request_options.xml
Added multi-003 multi-document request with specific data elements
=> Test event

appverifier/src/main/java/com/android/mdl/appreader/fragment/ShowDocumentFragment.kt, appverifier/src/main/res/layout/fragment_request_custom.xml, appverifier/src/main/res/layout/fragment_select_transport.xml, appverifier/src/main/res/layout/fragment_show_document.xml
Fix view to support to dark mode.
=> Fix view to support to dark mode.

appholder/src/main/AndroidManifest.xml, appholder/src/main/java/com/android/mdl/app/MainActivity.kt, appholder/src/main/java/com/android/mdl/app/fragment/SelectDocumentFragment.kt, appverifier/src/main/AndroidManifest.xml, appverifier/src/main/java/com/android/mdl/appreader/MainActivity.kt, appverifier/src/main/java/com/android/mdl/appreader/fragment/DeviceEngagementFragment.kt, identity/src/main/AndroidManifest.xml
Tweak bluetooth permissions a bit to match changes in 12.
Explicitly mark PendingIntents as immutable, as required by 12.
=> Get apps running on Android 12

docs/.gitignore, identity/build.gradle, identity/src/main/java/com/android/identity/Constants.java, identity/src/main/java/com/android/identity/CredentialDataResult.java, identity/src/main/java/com/android/identity/DataTransportBle.java, identity/src/main/java/com/android/identity/DataTransportBleCentralClientMode.java, identity/src/main/java/com/android/identity/DataTransportBlePeripheralServerMode.java, identity/src/main/java/com/android/identity/DataTransportNfc.java, identity/src/main/java/com/android/identity/DataTransportTcp.java, identity/src/main/java/com/android/identity/DataTransportWifiAware.java, identity/src/main/java/com/android/identity/DeviceRequestGenerator.java, identity/src/main/java/com/android/identity/DeviceRequestParser.java, identity/src/main/java/com/android/identity/DeviceResponseParser.java, identity/src/main/java/com/android/identity/IdentityCredential.java, identity/src/main/java/com/android/identity/IdentityCredentialStore.java, identity/src/main/java/com/android/identity/PersonalizationData.java, identity/src/main/java/com/android/identity/PresentationHelper.java, identity/src/main/java/com/android/identity/PresentationSession.java, identity/src/main/java/com/android/identity/ResultData.java, identity/src/main/java/com/android/identity/SessionEncryptionDevice.java, identity/src/main/java/com/android/identity/SessionEncryptionReader.java, identity/src/main/java/com/android/identity/Util.java, identity/src/main/java/com/android/identity/Utility.java, identity/src/main/java/com/android/identity/VerificationHelper.java, identity/src/main/java/com/android/identity/WritableIdentityCredential.java
This generates JavaDoc in the docs/javadoc directory.
Also clean up code to use @hidden instead of @hide (the latter is a
doclava thing, the former is standard as of JDK 9) and remove the use
of RestrictTo annotations.
=> identity: Add generateApiDoc target.

appholder/build.gradle, appholder/src/main/AndroidManifest.xml, appverifier/build.gradle, appverifier/src/main/AndroidManifest.xml, build.gradle, gradle/wrapper/gradle-wrapper.properties, identity/build.gradle, identity/src/androidTest/AndroidManifest.xml, identity/src/main/AndroidManifest.xml
Also update all dependencies to their their latest versions.
This is in preparation for doing releases on Google Maven.
Test: Manually tested holder and verifier.
=> Upgrade Android Gradle plugin to the latest version.

identity/src/main/java/com/android/identity/PresentationHelper.java
This CL is a pure refactoring for greater code clarity / elegance.
- Remove unused import.
- Simplify lambdas as method references.
- catch RuntimeException instead of Exception to document the fact that no checked exception can be thrown
- add static import for StandardCharsets.UTF_8
- replace overly generic static type of a local variable Collection -> List because the runtime type is List, and that makes clearer that add() actually always adds an element.
=> Address various lint warnings in PresentationHelper.

.github/workflows/unit-test.yml, appholder/build.gradle, appholder/lint.xml, appverifier/build.gradle, appverifier/lint.xml, identity/build.gradle, identity/lint.xml, identity/src/main/java/com/android/identity/DataTransportWifiAware.java
Add a github action for building and running unit tests.
Workflow runs every time there's either a pull request or push to master.
=> Implement basic continuous integration

identity/src/main/java/com/android/identity/DataTransportNfc.java
This class plus helper code using it is unused and obsolete.
Also updated the TODO to state what David says the intention here was.
=> Drop unused NfcOptions class.

appholder/src/main/java/com/android/mdl/app/transfer/TransferManager.kt, appverifier/src/main/java/com/android/mdl/appreader/fragment/TransferFragment.kt, identity/src/main/java/com/android/identity/DataTransport.java, identity/src/main/java/com/android/identity/DataTransportBleCentralClientMode.java, identity/src/main/java/com/android/identity/DataTransportBlePeripheralServerMode.java, identity/src/main/java/com/android/identity/DataTransportNfc.java, identity/src/main/java/com/android/identity/DataTransportTcp.java, identity/src/main/java/com/android/identity/DataTransportWifiAware.java, identity/src/main/java/com/android/identity/GattClient.java, identity/src/main/java/com/android/identity/GattServer.java, identity/src/main/java/com/android/identity/PresentationHelper.java, identity/src/main/java/com/android/identity/TransmissionProgressListener.java
=> Add progress listener when device response is sent

identity/src/main/java/com/android/identity/PresentationHelper.java
Use L2CAP option on presentation and use it if available.
=> Set to use L2CAP from holder side.

identity/src/main/java/com/android/identity/GattServer.java
Our GATT server currently assumes that `onConnectionStateChange` will
only be called for the BLE device we're expecting to communicate with
(e.g. the remote mDL app if using mdoc BLE central client mode) but
this is not true since e.g. already connected peripherals may connect
and disconnect all the time, for example a watch already paired with
the device.
Remove this assumptions and instead set `mCurrentConnection` only when
a device writes 0x01 to the State characterstic to indicate that it is
ready to exchanging data, as per 18013-5 section 8.3.3.1.1.
Also make the debug/log messages more useful by including the MAC
address of the remote device.
A fix for this was proposed in PR #90 but had some issues.
Bug: None
Test: Manually tested using both mdoc BLE central client mode and mdoc …
=> GattServer: Remove assumption about devices connecting and disconnecting

identity/src/main/java/com/android/identity/IdentityCredentialStore.java
=> Return null instead of throwing if hardware backed not supported

build.gradle
Fixes [#70](https://github.com/google/identity-credential/issues/70)
=> Removed groovy dependency

appholder/src/main/res/xml/network_security_config.xml, identity/build.gradle, identity/src/androidTest/java/com/android/identity/DataTransportHttpTest.java, identity/src/main/java/com/android/identity/DataTransportHttp.java
This adds support for HTTPS URIs.
=> identity: Use volley library for DataTransportHttp

appholder/build.gradle, appholder/src/main/java/com/android/mdl/app/fragment/SelectDocumentFragment.kt, appholder/src/main/java/com/android/mdl/app/fragment/SelfSignedDetailsFragment.kt, appverifier/build.gradle, appverifier/src/main/java/com/android/mdl/appreader/fragment/DeviceEngagementFragment.kt, appverifier/src/main/java/com/android/mdl/appreader/fragment/ShowDocumentFragment.kt, appverifier/src/main/java/com/android/mdl/appreader/fragment/ShowQrFragment.kt, appverifier/src/main/java/com/android/mdl/appreader/fragment/TransferFragment.kt, build.gradle, gradle/libs.versions.toml, identity/build.gradle, identity/src/test/java/com/android/identity/UtilTest.java, settings.gradle
Introduced version catalog for better dependency management between the projects
More about the advantages over manual management: https://docs.gradle.org/current/userguide/platforms.html
> **Note**
> The version catalog does not interfere with the library project in the repo, because eventually the library will be pulled out/distributed to maven.
=> Introduce version catalog

appholder/src/main/AndroidManifest.xml, appholder/src/main/java/com/android/mdl/app/MainActivity.kt, identity/src/main/java/com/android/identity/PresentationHelper.java
This is used for 18013-7 presentations over the Internet
Test: tested with Chrome on Android
=> Add preliminary support for mdoc:// URIs

appholder/src/main/java/com/android/mdl/app/document/Document.kt, appholder/src/main/java/com/android/mdl/app/document/DocumentDatabase.kt, appholder/src/main/java/com/android/mdl/app/document/MigrationV1ToV2.kt
=> Add database migration from v1 to v2

identity/src/main/java/com/android/identity/DataTransportHttp.java, identity/src/main/java/com/android/identity/OriginInfo.java, identity/src/main/java/com/android/identity/OriginInfoNfc.java, identity/src/main/java/com/android/identity/OriginInfoQr.java, identity/src/main/java/com/android/identity/OriginInfoWebsite.java, identity/src/test/java/com/android/identity/OriginInfoTest.java
Changes from from WD4 to WD5 include
- Content-type is "application/cbor", not "application/CBOR"
- OriginInfo is a map
=> Update to 18013-7 WD5.

appverifier/src/main/res/layout/fragment_request_options.xml
=> reader: default to "mDL for US transportation"

appholder/src/main/java/com/android/mdl/app/transfer/QrCommunicationSetup.kt, appholder/src/main/java/com/android/mdl/app/transfer/TransferManager.kt, appholder/src/main/java/com/android/mdl/app/util/NfcDataTransferHandler.kt, appholder/src/main/java/com/android/mdl/app/util/NfcEngagementHandler.kt, identity/src/main/java/com/android/identity/DataTransportNfc.java, identity/src/main/java/com/android/identity/NfcApduRouter.java, identity/src/main/java/com/android/identity/NfcEngagementHelper.java, identity/src/main/java/com/android/identity/NfcUtil.java, identity/src/main/java/com/android/identity/QrEngagementHelper.java, identity/src/main/java/com/android/identity/VerificationHelper.java
This has been broken for a while, fix it and verify that it works both with NFC static handover and QR.
Also fix a bug where we were leaking NfcEngagementHelper on error paths.
Test: Manually tested all supported engagement and data transfers (except Wifi Aware)
=> Fix NFC data transfer.

appholder/src/main/java/com/android/mdl/app/documentdata/RequestEuPid.kt, appholder/src/main/java/com/android/mdl/app/util/DocumentData.kt, appverifier/src/main/java/com/android/mdl/appreader/document/RequestEuPid.kt, appverifier/src/main/java/com/android/mdl/appreader/fragment/ShowDocumentFragment.kt
Use correct value for EU PID document type
=> Use correct document type value for EU PID

appholder/src/main/java/com/android/mdl/app/authconfirmation/AuthConfirmationFragment.kt, appholder/src/main/res/values/strings.xml
Use correct name for portrait for EU PID document
=> Use 'PID Portrait' name for EU PID portrait

identity/src/main/java/com/android/identity/VerificationHelper.java
This makes it slightly easier to debug certain things.
=> reader: Log the NDEF messages used in negotiated handover.

appholder/build.gradle, appholder/src/main/java/com/android/mdl/app/fragment/SelfSignedDetailsFragment.kt, appverifier/build.gradle, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties, identity/build.gradle
=> Fix crash when replacing portrait

appholder/src/main/java/com/android/mdl/app/transfer/Communication.kt, appholder/src/main/java/com/android/mdl/app/transfer/QrCommunicationSetup.kt, appholder/src/main/java/com/android/mdl/app/transfer/ReverseQrCommunicationSetup.kt, appholder/src/main/java/com/android/mdl/app/transfer/TransferManager.kt, appholder/src/main/java/com/android/mdl/app/util/NfcEngagementHandler.kt, identity/src/androidTest/java/com/android/identity/DeviceRetrievalHelperTest.java, identity/src/androidTest/java/com/android/identity/NfcEnagementHelperTest.java, identity/src/main/java/com/android/identity/DeviceRetrievalHelper.java, identity/src/main/java/com/android/identity/NfcEngagementHelper.java, identity/src/main/java/com/android/identity/NfcUtil.java, identity/src/main/java/com/android/identity/QrEngagementHelper.java, identity/src/main/java/com/android/identity/VerificationHelper.java
(see individual commits for details)
=> Misc fixes

appverifier/src/main/java/com/android/mdl/appreader/readercertgen/ReaderCertificateGenerator.java
=> Update the generated certificate with current dates

appholder/src/main/java/com/android/mdl/app/MainActivity.kt, appverifier/src/main/java/com/android/mdl/appreader/MainActivity.kt, identity/src/main/java/com/android/identity/Util.java, identity/src/test/java/com/android/identity/DeviceRequestParserTest.java
=> Using default provider in Util.coseSign1CheckSignature().

identity/src/main/java/com/android/identity/ConnectionMethodHttp.java, identity/src/main/java/com/android/identity/ConnectionMethodWifiAware.java
=> update log tags to fit within 23 character limit

identity/src/main/java/com/android/identity/DataTransportBleCentralClientMode.java
DataTransportBleCentralClientMode `onScanResult` is called several times before the `stopScan` takes effect.
Therefore, the `gattClient` is trying to connect to the device again. 
The internal implementation of `connectGatt`create a new `BluetoothGatt` instance and later `onConnectionChanged` is called for each instance and then it crashed.
read more: https://stackoverflow.com/a/38276808/4940838
Reproducible:
Samsung S20 - Android version 13
iPhone 13 Pro Max
- Android holder <- -> Android reader - in debug mode while receiving the `deviceRequest` before the scopes shown
- Android holder <- -> iOS reader - while receiving the `deviceRequest` before the scopes shown
=> prevent a ble crash due to several scanResult callbacks

appholder/src/main/java/com/android/mdl/app/documentdata/RequestMicovAtt.kt, appverifier/src/main/java/com/android/mdl/appreader/document/RequestMicovAtt.kt
20211029 mDoc for eHealth, sample data structure v0.4.docx
- 2.4 Data for attestation
- A.1.3.1 Indication of vaccination against Yellow Fever
=> micov: fix document field name

identity/src/main/java/com/android/identity/CredentialData.java
=> Warning message for exhausted key usage

.gitignore, README.md, identity/build.gradle, identity/src/main/java/com/android/identity/CredentialDataRequest.java, identity/src/main/java/com/android/identity/CredentialDataResult.java, identity/src/main/java/com/android/identity/DeviceRequestParser.java, identity/src/main/java/com/android/identity/DeviceResponseGenerator.java, identity/src/main/java/com/android/identity/DeviceRetrievalHelper.java, identity/src/main/java/com/android/identity/IdentityCredentialStore.java, identity/src/main/java/com/android/identity/Timestamp.java, identity/src/main/java/com/android/identity/TransmissionProgressListener.java, identity/src/main/java/com/android/identity/Utility.java, identity/src/main/java/com/android/identity/VerificationHelper.java
Modified existing docstrings to address errors + warnings from build.gradle's generateApiDoc and added the ability to generate artifacts which will be published from identity/build.gradle.
=> Cleanup before release

identity/src/main/java/com/android/identity/VerificationHelper.java
A partner has been reporting problems with our reader when using NFC Negotiated Handover and it looks like the root cause is that we don't honor the waiting time extensions as specified in [TNEP] 4.1.7.
Was able to test this by manually hacking up our holder app to request five extensions after receiving Handover Request.
D/VerificationHelper: ndefTransact: using single UPDATE_BINARY command
D/VerificationHelper: transceive: Sending APDU: 80 bytes of data: 00d600004b004991020a487215d102046163010130005a2015016170706c69636174696f6e2f766e642e626c7565746f6f74682e6c652e6f6f6230021c0011079e0440f488d865a7b248a707a8adcb0e
D/VerificationHelper: transceive: Received APDU: 2 bytes of data: 9000
D/VerificationHelper: ndefTransact: Sleeping 1 ms
D/VerificationHelper: transceive: Sending APDU: 5 bytes …
=> reader: Honor waiting time extensions during NFC Negotiated Handover.

identity-android/src/main/java/com/android/identity/android/mdoc/engagement/NfcEngagementHelper.java
Use 8ms and a maximum of 15 waiting time extensions.
=> Adjust Negotiated Handover waiting time and max number of extensions.

identity-android/src/androidTest/java/com/android/identity/android/mdoc/engagement/NfcEnagementHelperTest.java
These were broken as part of PR #298.
=> Fix identity-android unit tests.

gradle/libs.versions.toml
The dependencies for the `Holder` and the `Reader` apps got up to date
=> Project dependencies up to date

appholder/src/main/java/com/android/identity/wallet/HolderApp.kt, appholder/src/main/java/com/android/identity/wallet/util/PeriodicKeysRefreshWorkRequest.kt, appholder/src/main/java/com/android/identity/wallet/util/RefreshKeysWorker.kt, gradle/libs.versions.toml
=> Refresh Credential's Auth Keys Daily

identity-android/src/androidTest/java/com/android/identity/android/securearea/AndroidKeystoreSecureAreaTest.java
Previous commit broke unit tests in identity-android library. Fix this.
Tests: All unit tests pass.
=> Fix unit tests.

.github/workflows/unit-test.yml
=> Update unit test runner action to use the main branch instead of master.

identity-android/src/main/java/com/android/identity/android/storage/AndroidStorageEngine.java
Minor fix for NullPointerException that happens on the first run of the app.
=> Fix for a NullPointerException on first run.

MAINTAINERS.md
For now just include the active maintainers. In the future we'll add more of the optional information specified in
https://tac.openwallet.foundation/governance/maintainers-file-content/
Fixes #466
=> Add MAINTAINERS.md file.

wallet/src/main/java/com/android/identity_credential/wallet/MainActivity.kt, wallet/src/main/java/com/android/identity_credential/wallet/commonUI.kt
Fixes #471
Factors out code common for all screens into a couple of compose functions. This de-clutters top-level screens and also ensures that any changes we want to make to scaffolding are applied to all the screens we have.
Functionally, there is no change.
=> Factors out code common for all screens.

wallet/src/main/java/com/android/identity_credential/wallet/MainActivity.kt, wallet/src/main/java/com/android/identity_credential/wallet/PermissionTracker.kt, wallet/src/main/java/com/android/identity_credential/wallet/SelfSignedMdlIssuingAuthority.kt, wallet/src/main/java/com/android/identity_credential/wallet/navigation/WalletNavigation.kt, wallet/src/main/java/com/android/identity_credential/wallet/ui/CommonUI.kt, wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/about/AboutScreen.kt, wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/addtowallet/AddToWalletScreen.kt, wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/credential/CredentialDetailsScreen.kt, wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/credential/CredentialInfoScreen.kt, wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/main/MainScreen.kt, wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/provisioncredential/EvidenceRequest.kt, wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/provisioncredential/ProvisionCredentialScreen.kt, wallet/src/main/res/values/strings.xml
First pass of UI cleanup: moved strings to resources, added some styling.
Fixes #471. 
Additionally, moved bluetooth permission check to the presentation screen (will discuss how to make it prettier).
=> First pass of UI cleanup

wallet/src/main/java/com/android/identity_credential/wallet/ui/CommonUI.kt, wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/credential/CredentialDetailsScreen.kt, wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/main/MainScreen.kt, wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/qrengagement/QrEngagementScreen.kt, wallet/src/main/res/values/strings.xml
Fixes #486 
Got scrolling to work (for landscape and some smaller phone screens).
Also moved a few strings for QR into resources.
=> Enabled scrolling.

identity/src/main/java/com/android/identity/util/Logger.kt, mrtd-reader/src/main/java/com/android/identity_credential/mrtd/MrtdMrzScanner.kt, mrtd-reader/src/main/java/com/android/identity_credential/mrtd/MrtdNfcChipAccess.kt, mrtd-reader/src/main/java/com/android/identity_credential/mrtd/MrtdNfcDataDecoder.kt, mrtd-reader/src/main/java/com/android/identity_credential/mrtd/MrtdNfcDataReader.kt, mrtd-reader/src/main/java/com/android/identity_credential/mrtd/mrtdLog.kt, mrtd-reader/src/test/java/com/android/identity_credential/mrtd/MrtdNfcReaderTest.kt, wallet/src/main/AndroidManifest.xml, wallet/src/main/java/com/android/identity/issuance/evidence/EvidenceRequestIcaoNfcTunnel.kt, wallet/src/main/java/com/android/identity/issuance/evidence/EvidenceResponseIcaoNfcTunnel.kt, wallet/src/main/java/com/android/identity_credential/wallet/LogFileProvider.kt, wallet/src/main/java/com/android/identity_credential/wallet/LoggerModel.kt, wallet/src/main/java/com/android/identity_credential/wallet/MainActivity.kt, wallet/src/main/java/com/android/identity_credential/wallet/WalletApplication.kt, wallet/src/main/java/com/android/identity_credential/wallet/navigation/WalletNavigation.kt, wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/about/AboutScreen.kt, wallet/src/main/res/xml/log_file_paths.xml
Added dev tool section on About screen. It is only active for dev builds. It allows saving logging to a file and also sharing/clearing the log file. Also added more logging, specifically to MRTD library.
Fixes #488
=> wallet: ability to save/send logs from the app UI

wallet/src/main/java/com/android/identity/issuance/evidence/EvidenceResponse.kt, wallet/src/main/java/com/android/identity_credential/wallet/SelfSignedMdlIssuingAuthority.kt, wallet/src/main/res/values/strings.xml
Moved strings in self-signing authority to Android resources + minor fix for MRTD evidence decoding.
Fixes #493
=> Moved strings in self-signing authority to resources.

wallet/src/main/java/com/android/identity_credential/wallet/PassportBasedIssuingAuthority.kt, wallet/src/main/java/com/android/identity_credential/wallet/SelfCertificationIssuingAuthority.kt, wallet/src/main/res/values/strings.xml
Additionally, also remove some questions about first/last name and credential artwork. Also fix a couple of bugs where the passport-based authority used the wrong strings.
=> Update issuer authority strings.

wallet/src/main/java/com/android/identity_credential/wallet/PresentationActivity.kt, wallet/src/main/java/com/android/identity_credential/wallet/presentation/PresentationRequestData.kt, wallet/src/main/java/com/android/identity_credential/wallet/presentation/TransferHelper.kt
=> wallet: Use reader authentication to determine trust point.

appholder/src/main/java/com/android/identity/wallet/fragment/TransferDocumentFragment.kt, appholder/src/main/java/com/android/identity/wallet/transfer/Communication.kt, appholder/src/main/java/com/android/identity/wallet/transfer/TransferManager.kt, appholder/src/main/java/com/android/identity/wallet/util/NfcEngagementHandler.kt, identity-mdoc/src/main/java/com/android/identity/mdoc/mso/MobileSecurityObjectGenerator.kt, identity-mdoc/src/main/java/com/android/identity/mdoc/mso/MobileSecurityObjectParser.kt, identity-mdoc/src/main/java/com/android/identity/mdoc/mso/StaticAuthDataGenerator.kt, identity-mdoc/src/main/java/com/android/identity/mdoc/mso/StaticAuthDataParser.kt, identity-mdoc/src/main/java/com/android/identity/mdoc/origininfo/OriginInfo.kt, identity-mdoc/src/main/java/com/android/identity/mdoc/origininfo/OriginInfoDomain.kt, identity-mdoc/src/main/java/com/android/identity/mdoc/request/DeviceRequestGenerator.kt, identity-mdoc/src/main/java/com/android/identity/mdoc/request/DeviceRequestParser.kt, identity-mdoc/src/main/java/com/android/identity/mdoc/response/DeviceResponseGenerator.kt, identity-mdoc/src/main/java/com/android/identity/mdoc/response/DeviceResponseParser.kt, identity-mdoc/src/main/java/com/android/identity/mdoc/response/DocumentGenerator.kt, identity-mdoc/src/main/java/com/android/identity/mdoc/sessionencryption/SessionEncryption.kt, samples/age-verifier-mdl/src/main/java/com/android/identity/age_verifier_mdl/MainActivity.kt
This PR provides updates to PR #500 so it's more Kotlin-DSL-friendly.
---
**Applying patch of changes from original PR** https://github.com/openwallet-foundation-labs/identity-credential/pull/506 however after rebasing with `main` all commits on `main` after the initial commit of the PR #506 were brought in to that PR, polluting the PR's commit history with unrelated commits. 
---
Ran and passed all unit tests (1 @ignored) 
Manually tested wallet app for sanity check
=> kotlin dsl updates to PR #500. Recreated from main.

gradle/libs.versions.toml, wallet/build.gradle, wallet/src/androidTest/java/com/android/identity_credential/wallet/ui/DurationFromNowTextTest.kt, wallet/src/main/java/com/android/identity_credential/wallet/ui/DurationFromNowText.kt, wallet/src/main/res/values/plurals.xml, wallet/src/main/res/values/strings.xml
TimeAgo function that formats time instant in the past in a human-readable way (such as "3 days and 5 hours ago") and autoupdates it as time goes by.
Tested by unit tests and manually.
=> "Time ago" formatting in Compose.

wallet/src/androidTest/java/com/android/identity_credential/wallet/ui/DurationFromNowTextTest.kt, wallet/src/main/java/com/android/identity_credential/wallet/ui/DurationFromNowText.kt, wallet/src/main/res/values/plurals.xml, wallet/src/main/res/values/strings.xml
Fixes #514: have a more "relaxed" output
Tested: updated unit test, manually observing
=> Adjusted text created by durationFromNowText.

wallet/src/main/java/com/android/identity_credential/wallet/PermissionTracker.kt, wallet/src/main/java/com/android/identity_credential/wallet/ui/CommonUI.kt, wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/main/MainScreen.kt, wallet/src/main/res/values/strings.xml
Fixes #533
Mostly just updated the UI, functionality is the same.
=> Move permission request UI into a snackbar.

mrtd-reader/src/main/java/com/android/identity_credential/mrtd/MrtdAccessData.kt, mrtd-reader/src/main/java/com/android/identity_credential/mrtd/MrtdAccessDataCan.kt, mrtd-reader/src/main/java/com/android/identity_credential/mrtd/MrtdAccessDataMrz.kt, mrtd-reader/src/main/java/com/android/identity_credential/mrtd/MrtdAccessDataPin.kt, mrtd-reader/src/main/java/com/android/identity_credential/mrtd/MrtdMrzScanner.kt, mrtd-reader/src/main/java/com/android/identity_credential/mrtd/MrtdNfcChipAccess.kt, mrtd-reader/src/main/java/com/android/identity_credential/mrtd/MrtdNfcDataReader.kt, mrtd-reader/src/main/java/com/android/identity_credential/mrtd/MrtdNfcReader.kt, mrtd-reader/src/main/java/com/android/identity_credential/mrtd/MrtdNfcScanner.kt, mrtd-reader/src/main/java/com/android/identity_credential/mrtd/mrtdMrzExtractor.kt, mrtd-reader/src/test/java/com/android/identity_credential/mrtd/MrtdNfcReaderTest.kt, wallet/src/main/java/com/android/identity/issuance/evidence/EvidenceRequestIcaoNfcTunnel.kt, wallet/src/main/java/com/android/identity/issuance/evidence/EvidenceRequestIcaoNfcTunnelType.kt, wallet/src/main/java/com/android/identity/issuance/simple/SimpleIcaoNfcTunnelDriver.kt, wallet/src/main/java/com/android/identity/issuance/simple/SimpleIssuingAuthority.kt, wallet/src/main/java/com/android/identity/issuance/simple/SimpleIssuingAuthorityProofingFlow.kt, wallet/src/main/java/com/android/identity/issuance/simple/SimpleIssuingAuthorityProofingGraph.kt, wallet/src/main/java/com/android/identity_credential/wallet/NfcTunnelDriver.kt, wallet/src/main/java/com/android/identity_credential/wallet/NfcTunnelScanner.kt, wallet/src/main/java/com/android/identity_credential/wallet/SelfSignedEuPidIssuingAuthority.kt, wallet/src/main/java/com/android/identity_credential/wallet/SelfSignedMdlIssuingAuthority.kt, wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/provisioncredential/EvidenceRequest.kt, wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/provisioncredential/IcaoMrtdCommunicationModel.kt, wallet/src/main/res/values/strings.xml, wallet/src/test/java/com/android/identity/issuance/evidence/EvidenceRequestTest.kt, wallet/src/test/java/com/android/identity_credential/wallet/TestIssuingAuthority.kt
- support for CAN/PIN-based workflow (no camera scanning needed)
- split pure UI code from the scanning logic
Fixes #557
=> Improvements for MRTD-based evidence collection

wallet/src/main/java/com/android/identity_credential/wallet/ui/HtmlSnippet.kt, wallet/src/main/java/com/android/identity_credential/wallet/ui/Markdown.kt, wallet/src/main/java/com/android/identity_credential/wallet/ui/RichTextSnippet.kt, wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/provisioncredential/EvidenceRequest.kt, wallet/src/main/res/values/strings.xml
Support for width, height, and style attributes in Markdown. Support for HTML rich text in addition to Markdown. Converted one of TOS messages to HTML and added logo images to both of TOS messages.
Fixes #537
=> Rich text improvements

.github/workflows/unit-test.yml, appholder/build.gradle, appverifier/build.gradle, cbor-processor/build.gradle, gradle.properties, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties, identity-android-legacy/build.gradle, identity-android/build.gradle, identity-doctypes/build.gradle, identity-mdoc/build.gradle, identity/build.gradle, identityctl/build.gradle, jpeg2k/build.gradle, mrtd-reader/build.gradle, samples/age-verifier-mdl/build.gradle, samples/preconsent-mdl/build.gradle, samples/simple-verifier/build.gradle, secure-area-test-app/build.gradle, wallet/build.gradle, wwwverifier/build.gradle
Also update to Java 17 as part of this.
Test All unit tests pass.
=> Update AGP, Gradle, Kotlin, dependencies to latest versions.

cbor-processor/build.gradle, identity-mdoc/build.gradle, identity/build.gradle, identityctl/build.gradle, jpeg2k/build.gradle, mrtd-reader/build.gradle, samples/age-verifier-mdl/build.gradle, samples/preconsent-mdl/build.gradle, samples/simple-verifier/build.gradle, secure-area-test-app/build.gradle, settings.gradle, wallet/build.gradle
This is recommended and helps fix a unit test failure.
Test: Manually tested with 'wallet' module
=> Use jvmToolchain.

appholder/src/main/java/com/android/identity/wallet/adapter/BindingAdapters.kt, appholder/src/main/java/com/android/identity/wallet/document/KeysAndCertificates.kt, appholder/src/main/java/com/android/identity/wallet/fragment/SelfSignedDetailsFragment.kt, appholder/src/main/java/com/android/identity/wallet/transfer/TransferManager.kt, appverifier/src/main/java/com/android/mdl/appreader/transfer/TransferManager.kt, appverifier/src/main/java/com/android/mdl/appreader/util/KeysAndCertificates.kt, jpeg2k/src/test/java/com/android/identity/jpeg2k/Jpeg2kConverterTest.kt, samples/age-verifier-mdl/src/androidTest/java/com/android/identity/age_verifier_mdl/ExampleInstrumentedTest.kt, samples/age-verifier-mdl/src/test/java/com/android/identity/age_verifier_mdl/ExampleUnitTest.kt, samples/preconsent-mdl/src/androidTest/java/com/android/identity/preconsent_mdl/ExampleInstrumentedTest.kt, samples/preconsent-mdl/src/test/java/com/android/identity/preconsent_mdl/ExampleUnitTest.kt, samples/simple-verifier/src/androidTest/java/com/example/simple_verifier/ExampleInstrumentedTest.kt, samples/simple-verifier/src/test/java/com/example/simple_verifier/ExampleUnitTest.kt, secure-area-test-app/src/test/java/com/android/identity/secure_area_test_app/ExampleUnitTest.kt, wallet/src/androidTest/java/com/android/identity_credential/wallet/ExampleInstrumentedTest.kt, wallet/src/test/java/com/android/identity_credential/wallet/ExampleUnitTest.kt
First of many PR's like this one to address KTLint violations that could not be auto-corrected. 
Tests pass and ran appholder + appverifier manually.
Progress on KTLint violations
https://docs.google.com/document/d/15sudT38S_EMyEANG2td4uDj1i5AlPsWh89JEci9ztgU/edit?usp=sharing&resourcekey=0-FYwTd3Tp8f-RZnyEvUdfHQ
=> KTLint Violation Fix - no wildcard imports

cbor-processor/src/main/kotlin/com/android/identity/flow/annotation/FlowGetter.kt, cbor-processor/src/main/kotlin/com/android/identity/flow/annotation/FlowInterface.kt, cbor-processor/src/main/kotlin/com/android/identity/flow/annotation/FlowJoin.kt, cbor-processor/src/main/kotlin/com/android/identity/flow/annotation/FlowMethod.kt, cbor-processor/src/main/kotlin/com/android/identity/flow/annotation/FlowState.kt, cbor-processor/src/main/kotlin/com/android/identity/processor/CborSymbolProcessor.kt, cbor-processor/src/main/kotlin/com/android/identity/processor/CodeBuilder.kt, cbor-processor/src/main/kotlin/com/android/identity/processor/FlowSymbolProcessor.kt, cbor-processor/src/main/kotlin/com/android/identity/processor/MainProcessor.kt, cbor-processor/src/main/kotlin/com/android/identity/processor/MainProcessorProvider.kt, cbor-processor/src/main/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessorProvider, identity/src/main/java/com/android/identity/flow/FlowBaseInterface.kt, identity/src/main/java/com/android/identity/flow/handler/FlowEnvironment.kt, identity/src/main/java/com/android/identity/flow/handler/FlowHandler.kt, identity/src/main/java/com/android/identity/flow/handler/FlowHandlerLocal.kt, identity/src/main/java/com/android/identity/flow/handler/FlowHandlerRemote.kt, identity/src/test/java/com/android/identity/processor/CborProcessorTest.kt, identity/src/test/java/com/android/identity/processor/FlowProcessorTest.kt
First cut of flow annotation processor to generate code for flow-based networking (Resolves #600).
Fixes #600
Added a simple unit test and verified that changes in cbor-processor do not break unit tests or wallet app.
=> First cut of flow annotation processor.

wallet/src/main/java/com/android/identity/issuance/remote/WalletServerProvider.kt, wallet/src/main/java/com/android/identity_credential/wallet/SettingsModel.kt, wallet/src/main/java/com/android/identity_credential/wallet/WalletApplication.kt, wallet/src/main/java/com/android/identity_credential/wallet/navigation/WalletNavigation.kt, wallet/src/main/java/com/android/identity_credential/wallet/ui/CommonUI.kt, wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/settings/SettingsScreen.kt, wallet/src/main/res/values/strings.xml
=> wallet: Add UI to set the Wallet Server URL in Settings

wallet-issuance/src/main/java/com/android/identity/issuance/hardcoded/IssuingAuthorityState.kt, wallet-issuance/src/main/java/com/android/identity/issuance/hardcoded/WalletServerState.kt, wallet/src/main/java/com/android/identity/issuance/remote/WalletServerProvider.kt
- Ensure we do RPCs in background when running server-side code locally.
- Cache issuing authority configurations. 
- Don't carry issuing authority configuration in issuing authority state.
Fixes #621.
Tested manually for both server and local environment.
=> Performance improvements and cleanup for server-client interactions.

wallet/src/main/java/com/android/identity/issuance/remote/WalletServerProvider.kt
=> Reset delay when reconnecting for notifications.

gradle/libs.versions.toml, identity-issuance/build.gradle.kts, identity-issuance/src/main/java/com/android/identity/issuance/evidence/EvidenceRequestGermanEid.kt, identity-issuance/src/main/java/com/android/identity/issuance/evidence/EvidenceResponseGermanEid.kt, identity-issuance/src/main/java/com/android/identity/issuance/evidence/EvidenceResponseGermanEidResolved.kt, identity-issuance/src/main/java/com/android/identity/issuance/hardcoded/IssuingAuthorityState.kt, identity-issuance/src/main/java/com/android/identity/issuance/hardcoded/ProofingState.kt, identity-issuance/src/main/java/com/android/identity/issuance/proofing/ProofingGraphBuilder.kt, identity-issuance/src/main/java/com/android/identity/issuance/proofing/defaultGraph.kt, server/build.gradle.kts, server/src/main/java/com/android/identity/wallet/server/ServerEnvironment.kt, wallet/build.gradle.kts, wallet/src/main/AndroidManifest.xml, wallet/src/main/java/com/android/identity/issuance/remote/LocalDevelopmentEnvironment.kt, wallet/src/main/java/com/android/identity_credential/wallet/WalletApplication.kt, wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/provisioncredential/AusweisModel.kt, wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/provisioncredential/EvidenceRequest.kt, wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/provisioncredential/ProvisionCredentialScreen.kt, wallet/src/main/res/values/strings.xml
Added new evidence type (eID) which is implemented using AusweisSDK (although we could probably just do it directly in the future).
=> Integrated AusweisSDK to read German eID card.

.github/workflows/unit-test.yml, identity/SwiftBridge/build.gradle.kts, identity/build.gradle.kts
Test: Tested on Android Studio on Linux.
Test: Tested on Android Studio on Mac.
=> Make using Android Studio work on Linux.

wallet/src/main/java/com/android/identity/issuance/remote/WalletServerProvider.kt
=> Wait for the server connection to establish notifications.

wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/provisioncredential/AusweisModel.kt, wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/provisioncredential/EvidenceRequest.kt, wallet/src/main/res/values/strings.xml
=> Handling errors from Ausweis SD (Fixes #657).

identity-flow/src/test/java/com/android/identity/flow/FlowProcessorTest.kt, identity-issuance/src/main/java/com/android/identity/issuance/RequestCredentialsFlow.kt, identity-issuance/src/main/java/com/android/identity/issuance/WalletServer.kt, identity-issuance/src/main/java/com/android/identity/issuance/hardcoded/RequestCredentialsState.kt, processor/src/main/kotlin/com/android/identity/processor/FlowSymbolProcessor.kt, wallet/src/main/java/com/android/identity/issuance/simple/SimpleIssuingAuthorityRequestCredentialsFlow.kt, wallet/src/main/java/com/android/identity_credential/wallet/DocumentModel.kt, wallet/src/test/java/com/android/identity_credential/wallet/SelfSignedMdlTest.kt
Also removed unused (and unneeded) functionality that could generate interfaces based on the flow state definitions.
Tested by virtue of finding the actual errors + some manual testing.
=> Added more error-checking in the flow processor and fixed the errors found.

identity-android/src/main/java/com/android/identity/android/mdoc/transport/GattClient.kt, identity-android/src/main/java/com/android/identity/android/mdoc/transport/GattServer.kt
With recent changes to the code, we're terminating the BLE connection on the mdoc side just a bit earlier which causes the mdoc reader to sometimes receive an incomplete `SessionData` message which it fails to decode as proper CBOR. Incomplete because it's about 500 bytes shorter than what was sent from the mdoc. This would happen about 1 in 10 times on a setup with a Pixel 8 Pro as the mdoc and Pixel 7a as the mdoc reader.
After digging a while it turns out this is caused by one of the GATT writes strangely going missing. The reason for this is that sendMessage() causes drainWritingQueue() to be called and the guarding logic - writeIsOutstanding - didn't work. So we ended up doing two writes to a characteristic without waiting for the other end to report that they read for it.
Simplify …
=> BLE: Fix race condition when terminating connection immediately.

identity-issuance/build.gradle.kts, identity-issuance/src/main/java/com/android/identity/issuance/hardcoded/IssuingAuthorityState.kt, identity-issuance/src/main/java/com/android/identity/issuance/hardcoded/RequestCredentialsState.kt
=> Add SD-JWT credentials for EU PID document type.

identity/src/commonMain/kotlin/com/android/identity/crypto/EcPrivateKey.kt, server/build.gradle.kts, server/src/main/java/com/android/identity/wallet/server/VerifierServlet.kt, server/src/main/webapp/WEB-INF/web.xml, server/src/main/webapp/verifier.html, server/src/main/webapp/verifier.js, server/src/main/webapp/verifier_redirect.html, wallet/src/main/java/com/android/identity_credential/wallet/presentation/OpenID4VPPresentationActivity.kt
This currently only supports OpenID4VP w/ URI schemes and mdoc credential format. We'll extend this with other formats (SD-JWT) and protocols (W3C Digital Identities API) in the near future.
=> server: Add new verifier component.

identity-issuance/src/main/java/com/android/identity/issuance/WalletServerSettings.kt, identity-issuance/src/main/java/com/android/identity/issuance/evidence/EvidenceResponseSetupCloudSecureArea.kt, identity-issuance/src/main/java/com/android/identity/issuance/funke/FunkeProofingState.kt, identity-issuance/src/main/java/com/android/identity/issuance/hardcoded/ProofingState.kt, identity-issuance/src/main/java/com/android/identity/issuance/proofing/defaultGraph.kt, server/src/main/java/com/android/identity/wallet/server/FlowServlet.kt, server/src/main/webapp/WEB-INF/web.xml, wallet/src/customized/java/com/android/identity_credential/wallet/WalletApplicationConfiguration.kt, wallet/src/main/java/com/android/identity/issuance/remote/LocalDevelopmentEnvironment.kt, wallet/src/main/java/com/android/identity/issuance/remote/WalletHttpTransport.kt, wallet/src/main/java/com/android/identity/issuance/remote/WalletServerProvider.kt, wallet/src/main/java/com/android/identity_credential/wallet/SettingsModel.kt, wallet/src/main/java/com/android/identity_credential/wallet/WalletApplication.kt, wallet/src/main/java/com/android/identity_credential/wallet/ui/CommonUI.kt, wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/provisioncredential/ProvisionCredentialScreen.kt, wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/settings/SettingsScreen.kt, wallet/src/main/res/values/strings.xml, wallet/src/upstream/java/com/android/identity_credential/wallet/WalletApplicationConfiguration.kt
This also fixes the problem with Wallet-Server-based issuance.
=> Setting for Cloud Secure Area url.

wallet/src/main/java/com/android/identity_credential/wallet/DocumentModel.kt, wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/document/DocumentInfoScreen.kt, wallet/src/main/res/drawable/certificate_icon.xml
Also fix up some of the displayed data so it's more human readable.
=> wallet: Show Credentials menu item even if not in Developer Mode.

wallet/src/main/java/com/android/identity_credential/wallet/ReaderModel.kt, wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/provisioncredential/AusweisModel.kt
Test: Manually tested on emulator.
=> wallet: Fix crash on emulator when going to the reader page.

identity-android-legacy/src/main/java/com/android/identity/android/legacy/CredentialDataResult.java, identity-android/src/androidTest/java/com/android/identity/android/mdoc/transport/DataTransportHttpTest.kt, identity-android/src/androidTest/java/com/android/identity/android/mdoc/transport/DataTransportTcpTest.kt, identity-mdoc/src/commonTest/kotlin/com/android/identity/mdoc/response/DeviceResponseParserTest.kt, wallet/src/main/java/com/android/identity_credential/wallet/ui/destination/document/DocumentInfoScreen.kt
Click the document artwork five times and we request a document update from the wallet server.
Also update some copyright notices.
=> Wallet: add hidden feature to cause a document update.

server/src/main/java/com/android/identity/wallet/server/VerifierServlet.kt, server/src/main/webapp/verifier.html, server/src/main/webapp/verifier.js, wallet/src/main/AndroidManifest.xml
Also fix a bug in the verifier in the protocol dropdown.
=> Support plain openid4vp scheme (openid4vp://).

identity-issuance/src/main/java/com/android/identity/issuance/hardcoded/IssuingAuthorityState.kt, identity-issuance/src/main/java/com/android/identity/issuance/hardcoded/ProofingState.kt, identity-issuance/src/main/java/com/android/identity/issuance/proofing/defaultGraph.kt
At issuance time, we need to know whether StrongBox is available on the device.
=> issuance: Propogate WalletApplicationCapabilities.

identity-issuance/src/main/java/com/android/identity/issuance/funke/FunkeIssuingAuthorityState.kt, identity-issuance/src/main/java/com/android/identity/issuance/funke/FunkeProofingState.kt
=> Require StrongBox or Cloud Secure Area for Funke-issued credentials.

MAINTAINERS.md
=> Add new team members to maintainers file.

identity-doctypes/src/commonMain/kotlin/com/android/identity/documenttype/knowntypes/GermanPersonalID.kt, identity-doctypes/src/commonMain/kotlin/com/android/identity/documenttype/knowntypes/SampleData.kt, identity-issuance/src/main/java/com/android/identity/issuance/funke/FunkeIssuingAuthorityState.kt, identity-issuance/src/main/java/com/android/identity/issuance/hardcoded/IssuingAuthorityState.kt, server/src/main/java/com/android/identity/wallet/server/VerifierServlet.kt, wallet/src/main/java/com/android/identity_credential/wallet/WalletApplication.kt
Added VCT to match what BDR server issues right now.
=> Added German PID VCT.

MAINTAINERS.md
Add Alex Koukarine to the MAINTAINERS.md table in alphabetical order.
=> Add new maintainer to the list.

MAINTAINERS.md
Replace @halxinate to @koukarine in the MAINTAINERS.md
=> Fix the github name for Koukarine.

identity/SwiftBridge/SwiftBridge/SwiftBridge.swift, identity/src/commonMain/kotlin/com/android/identity/crypto/X509Cert.kt, identity/src/iosMain/kotlin/com/android/identity/crypto/CryptoIos.kt
Lack of iOS implementation was causing some multiplatform unit test failures for iOS.
Failing unit tests now pass.
=> Added iOS implementation for certificate chain validation.

identity-appsupport/src/commonMain/composeResources/values/strings.xml, identity-appsupport/src/commonMain/kotlin/com/android/identity/appsupport/ui/certificateviewer/CertificateViewData.kt, identity-appsupport/src/commonMain/kotlin/com/android/identity/appsupport/ui/certificateviewer/CertificateViewer.kt, identity/src/commonMain/kotlin/com/android/identity/asn1/OID.kt, identity/src/commonMain/kotlin/com/android/identity/crypto/Algorithm.kt, identity/src/commonMain/kotlin/com/android/identity/crypto/X500Name.kt, identity/src/commonMain/kotlin/com/android/identity/crypto/X509Cert.kt, samples/testapp/src/commonMain/composeResources/values/strings.xml
+ Algorithm descriptions.
+ RFC-1123 Time format.
+ Minor fixes.
Ticket: 1
Tested manually with multiple certificates chain (previously defined in tests), as well as with local tests.
=> Add RSA algorithm support to CertificateViewer.

identity-appsupport/src/commonMain/composeResources/values/strings.xml, identity-appsupport/src/commonMain/kotlin/com/android/identity/appsupport/ui/certificateviewer/CertificateViewData.kt, identity-appsupport/src/commonMain/kotlin/com/android/identity/appsupport/ui/certificateviewer/CertificateViewer.kt, identity/src/commonMain/kotlin/com/android/identity/asn1/OID.kt, identity/src/commonMain/kotlin/com/android/identity/crypto/X509Cert.kt, identity/src/commonMain/kotlin/com/android/identity/crypto/X509Extension.kt, identity/src/commonMain/kotlin/com/android/identity/crypto/X509KeyUsage.kt
Tested manually to match the suggested presentation of known certificate extensions.
=> CertificateViewer:  known extensions data display.

identity-android/src/main/java/com/android/identity/android/direct_access/DirectAccess.kt, identity-android/src/main/java/com/android/identity/android/direct_access/DirectAccessCredential.kt, identity-android/src/main/java/com/android/identity/android/direct_access/DirectAccessOmapiTransport.kt, identity-android/src/main/java/com/android/identity/android/mdoc/transport/DataTransportNfc.kt, identity-android/src/main/java/com/android/identity/android/util/NfcUtil.kt, identity/src/commonMain/kotlin/com/android/identity/credential/Credential.kt
Library changes needed to support and test Direct Access Credentials.
This PR is a preliminary PR to get feedback on library changes. At the moment, some functionality in the applet is not yet implemented, so there are TODOs in DirectAccess.kt and DirectAccessTest.kt to indicate that.
=> Introducing Direct Access Credentials

identity-android/src/main/java/com/android/identity/android/direct_access/DirectAccessDocumentMetadata.kt, identity/src/androidMain/kotlin/com/android/identity/ui/UiModelAndroid.kt, wallet/src/main/java/com/android/identity_credential/wallet/MainActivity.kt, wallet/src/main/java/com/android/identity_credential/wallet/PresentationActivity.kt
Get biometric prompt to work in the wallet app.
Also a minor fix for the error when deleting a document in the wallet.
=> Register MainActivity and PresentationActivity for biometric prompt.

samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/ui/CloudSecureAreaScreen.kt
Tested-by:
- Manually testing the screen in testapp.
=> Adds a dropdown to the CSA connection screen to select common URLs.

CODING-STYLE.md
This is just to get started, we can add more to this later.
=> Add a CODING-STYLE.md file.

multipaz-compose/src/androidMain/kotlin/org/multipaz/compose/prompt/BiometricPromptDialog.kt, samples/testapp/src/androidMain/kotlin/com/android/identity/testapp/CredmanPresentmentActivity.kt, samples/testapp/src/androidMain/kotlin/com/android/identity/testapp/NfcPresentmentActivity.kt, samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/App.kt, wallet/src/main/java/com/android/identity_credential/wallet/MainActivity.kt, wallet/src/main/java/com/android/identity_credential/wallet/PresentationActivity.kt, wallet/src/main/java/com/android/identity_credential/wallet/WalletApplication.kt, wallet/src/main/java/com/android/identity_credential/wallet/credman/CredmanPresentationActivity.kt, wallet/src/main/java/com/android/identity_credential/wallet/presentation/OpenID4VPPresentationActivity.kt
Display prompt dialogs in all activities. Make sure that we attempt to show biometric prompt only in the currently-running activity.
Tested in the test app and the wallet.
=> Display prompt dialogs in all activities.

identity/src/commonMain/kotlin/com/android/identity/credential/Credential.kt, identity/src/commonMain/kotlin/com/android/identity/document/Document.kt, identity/src/commonTest/kotlin/com/android/identity/document/DocumentStoreTest.kt
Testing: added a unit test to reproduce the bug. Passing other unit tests.
=> Fixed a race condition in the DocumentStore.

TESTING.md
=> Add TESTING.md with testing instructions and how to record this.

identity/src/commonMain/kotlin/com/android/identity/nfc/CommandApdu.kt, identity/src/commonMain/kotlin/com/android/identity/nfc/HandoverRequestRecord.kt, identity/src/commonMain/kotlin/com/android/identity/nfc/HandoverSelectRecord.kt, identity/src/commonMain/kotlin/com/android/identity/nfc/NdefMessage.kt, identity/src/commonMain/kotlin/com/android/identity/nfc/NdefRecord.kt, identity/src/commonMain/kotlin/com/android/identity/nfc/NfcIsoTag.kt, identity/src/commonMain/kotlin/com/android/identity/nfc/ResponseApdu.kt, identity/src/commonMain/kotlin/com/android/identity/nfc/ServiceParameterRecord.kt, identity/src/commonMain/kotlin/com/android/identity/nfc/ServiceSelectRecord.kt, identity/src/commonMain/kotlin/com/android/identity/nfc/TnepStatusRecord.kt, identity/src/commonMain/kotlin/com/android/identity/util/ByteArrayUtil.kt, identity/src/commonMain/kotlin/com/android/identity/util/ByteDataReader.kt, identity/src/commonMain/kotlin/com/android/identity/util/ByteStringUtil.kt, identity/src/commonTest/kotlin/com/android/identity/util/ByteArrayUtilTest.kt, identity/src/commonTest/kotlin/com/android/identity/util/ByteStringUtilTest.kt
Phase 1. ByteArray, ByteStringBuffer, Buffer extension method collection with unit tests.
=> Helper utilities for multi-byte data reading and writing.

multipaz/src/commonMain/kotlin/org/multipaz/util/ByteStringUtil.kt, multipaz/src/commonTest/kotlin/org/multipaz/util/ByteStringUtilTest.kt
=> Remove emptyByteString() method..

multipaz/src/commonMain/kotlin/org/multipaz/mdoc/connectionmethod/ConnectionMethodBle.kt, multipaz/src/commonMain/kotlin/org/multipaz/mdoc/connectionmethod/ConnectionMethodNfc.kt, multipaz/src/commonMain/kotlin/org/multipaz/mdoc/transport/NfcTransportMdocReader.kt, multipaz/src/commonMain/kotlin/org/multipaz/securearea/cloud/CloudSecureArea.kt, multipaz/src/commonMain/kotlin/org/multipaz/util/ByteArrayUtil.kt, multipaz/src/commonTest/kotlin/org/multipaz/util/ByteArrayUtilTest.kt, wallet/src/androidMain/kotlin/org/multipaz/wallet/credman/IdentityCredentialRegistry.kt
- Code using Buffer() for Byte reading/writing refactored.
- DataTransport classes refactored.
- Several other places overlooked before refactored.
Test: All Unit tests are passing.
=> Refactor for new Byte utilities use II.

multipaz/src/androidMain/kotlin/org/multipaz/storage/android/AndroidStorageTable.kt, multipaz/src/commonMain/kotlin/org/multipaz/storage/StorageTable.kt, multipaz/src/commonMain/kotlin/org/multipaz/storage/base/SqlStatementMaker.kt, multipaz/src/commonMain/kotlin/org/multipaz/storage/ephemeral/EphemeralStorageTable.kt, multipaz/src/commonTest/kotlin/org/multipaz/storage/StorageTest.kt, multipaz/src/iosMain/kotlin/org/multipaz/storage/sqlite/SqliteStorageTable.kt, multipaz/src/jvmMain/kotlin/org/multipaz/storage/jdbc/JdbcStorageTable.kt
Added a new `deletePartition` method to `StorageTable` method to delete all records in a given partition.
Testing: existing and new unit tests.
=> Ability to delete data per table partition.

wallet/src/main/java/org/multipaz/android/direct_access/DirectAccess.kt
Test: Manually tested direct access
=> Implemented maxCredentialSize from Applet

multipaz-provisioning-api/src/commonMain/kotlin/org/multipaz/provisioning/CredentialFormat.kt, multipaz-provisioning/src/main/java/org/multipaz/provisioning/hardcoded/IssuingAuthorityState.kt, wallet/src/main/java/org/multipaz/android/direct_access/DirectAccess.kt, wallet/src/main/java/org/multipaz/android/direct_access/DirectAccessCredential.kt, wallet/src/main/java/org/multipaz/provisioning/WalletDocumentMetadata.kt, wallet/src/main/java/org/multipaz/wallet/DocumentModel.kt
Test: Manually tested direct access
=> Remove doctype from credentialData for direct access credential

samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/App.kt, samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/ui/StartScreen.kt
That part in the test app is not ready yet and could only confuse users.
=> Remove 'Test Provisioning' item in test app.

multipaz-compose/src/androidMain/kotlin/org/multipaz/compose/webview/WebViewRender.android.kt, multipaz-compose/src/iosMain/kotlin/org/multipaz/compose/webview/WebViewRender.ios.kt, multipaz/src/androidMain/kotlin/org/multipaz/storage/android/AndroidStorage.kt, multipaz/src/commonMain/kotlin/org/multipaz/flow/handler/FlowDispatcherLocal.kt, multipaz/src/iosMain/kotlin/org/multipaz/prompt/IosPromptModel.kt, multipaz/src/iosMain/kotlin/org/multipaz/storage/sqlite/SqliteStorage.kt, samples/testapp/src/androidMain/kotlin/com/android/identity/testapp/MainActivity.kt
Fixed some of the more obvious problems: incorrect use of coroutine APIs, consuming `CancellationException`, launching in scopes that are not cancelled at appropriate time.
No functional changes.
Testing: unit test passed, no problems found doing manual smoke check with test and wallet app.
=> Coroutine usage cleanup.

TESTING.md
This should provide a clear walkthrough for each of the pieces we want to test prior to a release. It's useful as a guide for individual PR's also, though we probably wouldn't walk through every single one for every PR.
Please double check that the expected test results are accurate.
Tested by:
- Walking through the test matrix and creating bugs for any failing tests.
=> Added a test matrix to TESTING.md

wallet/src/main/java/org/multipaz/android/direct_access/DirectAccess.kt
Test: Manually tested direct_access
=> Added support for getUsageCount and clearUsageCount

wallet/src/main/java/org/multipaz/android/direct_access/DirectAccess.kt, wallet/src/main/java/org/multipaz/wallet/WalletApplication.kt
=> Support for enumerateSlots

multipaz/src/androidMain/kotlin/org/multipaz/securearea/cloud/CloudSecureArea.android.kt, multipaz/src/iosMain/kotlin/org/multipaz/securearea/cloud/CloudSecureArea.ios.kt, samples/testapp/src/androidMain/kotlin/com/android/identity/testapp/PlatformAndroid.kt
Testing: Manually tested provisioning and presentation of documents in cloud secure area. Verified that documents don't reappear after reinstall. Ran unit tests.
=> Moved android storage in test app to non-backed-up area.

samples/testapp/iosApp/TestApp.xcodeproj/project.pbxproj, samples/testapp/iosApp/TestApp/Info.plist
=> Undo unintended XCode changes in last commit.

multipaz-compose/src/iosMain/kotlin/org/multipaz/compose/camera/Camera.ios.kt, samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/ui/BarcodeScanningScreen.kt
- Implemented coordinates transformation matrix for iOS preview drawing.
- Fix the rotated Rect params mapping in BarcodeScanning.
- Minor comments cleanup.
Test: All Unit tests are passing (bar ZKP).
Test: Manually tested via samples/testapp on Android an iOS.
=> Fix iOS Camera rotation Matrix, do minor fixes and cleanup.

build.gradle.kts, samples/testapp/src/commonMain/kotlin/com/android/identity/testapp/ui/AppUpdateCard.kt
According to Semantic Versioning 2.0 prereleases should use the next version number which is contrary to what we're doing today. So fix this up. Also gracefully handle the case where it's not possible to reach apps.multipaz.org - for example if there is no Internet connectivity - instead of crashing.
With this change version numbers will change from
e.g. 0.90-48.g57b479c to e.g. 0.91.0-pre.48.574b479c.
This introduces an additional post-release version bump step as part of making a release.
=> Fix use of Semantic Versioning.

appverifier/src/main/java/com/android/mdl/appreader/VerifierApp.kt, multipaz/src/commonMain/kotlin/org/multipaz/trustmanagement/TrustManager.kt
Fixes #1012
Path has been changed so that file writes work as intended. Also small fix in TrustManager to allow file deletion to work as intended.
Test: manual testing
=> Fix certificate import

CHANGELOG.md, build.gradle.kts
Test: Manually tested artifacts with MpzSecureAreaSample on Android and iOS.
Test: Manually tested artifacts with SimpleVerifierStandalone on Android.
=> Update for 0.91.0 release.

server/src/main/java/org/multipaz/wallet/server/VerifierServlet.kt, server/src/main/webapp/verifier.html, server/src/main/webapp/verifier.js
Also add a meta tag to disable caching - this should resolve a long-standing issue where changes to verifier.js aren't loaded because the browser is using an old version.
=> Verifier: Add "Raw DCQL" tab with a text-box for free-form DCQL queries.

appverifier/src/main/java/com/android/mdl/appreader/fragment/DeviceEngagementFragment.kt
=> fix: crash on the verifier app upon scanning the QR code

multipaz/src/androidMain/kotlin/org/multipaz/storage/android/AndroidStorageTable.kt, multipaz/src/commonMain/kotlin/org/multipaz/storage/StorageTable.kt, multipaz/src/commonMain/kotlin/org/multipaz/storage/base/SqlStatementMaker.kt, multipaz/src/commonMain/kotlin/org/multipaz/storage/ephemeral/EphemeralStorageTable.kt, multipaz/src/iosMain/kotlin/org/multipaz/storage/sqlite/SqliteStorageTable.kt, multipaz/src/iosTest/kotlin/org/multipaz/storage/IosStorageTest.kt, multipaz/src/jvmMain/kotlin/org/multipaz/storage/jdbc/JdbcStorageTable.kt, multipaz/src/jvmTest/kotlin/org/multipaz/storage/JdbcStorageTest.kt
New API to enumerate with data retrieval. Added to all implementations and tweaked unit tests. Also added a copy of our existing unit tests for JVM/Jdbc.
Test: unit tests (old and new).
=> Aded enumerateWithData API to StorageTable interface.

CHANGELOG.md, Package.swift, build.gradle.kts
Test: Manually tested samples/testapp on Android and iOS.
Test: Manually tested artifacts with MpzCmpWallet on Android and iOS.
Test: Manually tested artifacts with MpzSwiftWallet on iOS.
Test: Manually tested artifacts with SimpleVerifierStandalone on Android.
=> Update for 0.92.0 release.

multipaz-compose/src/androidMain/kotlin/org/multipaz/compose/Util.android.kt, multipaz-openid4vci-server/src/main/java/org/multipaz/openid4vci/request/nonce.kt, samples/testapp/src/commonMain/kotlin/org/multipaz/testapp/provisioning/openid4vci/Openid4VciIssuingAuthorityState.kt, samples/testapp/src/commonMain/kotlin/org/multipaz/testapp/provisioning/openid4vci/RequestCredentialsUsingProofOfPossession.kt, samples/testapp/src/commonMain/kotlin/org/multipaz/testapp/provisioning/openid4vci/openid4VciIssuerMetadata.kt
Test: manual testing with other wallets and issuers.
=> Minor OpenId4Vci fixes from interop event.

multipaz-longfellow/consumer-rules.pro
Test: ZKP works in release builds.
=> multipaz-longfellow: Add proguard stanzas for release build

Podfile, Podfile.lock, gradle/libs.versions.toml, multipaz-compose/src/commonMain/kotlin/org/multipaz/compose/camera/CameraSelection.kt, multipaz-compose/src/iosMain/kotlin/org/multipaz/compose/Util.ios.kt, multipaz-compose/src/iosMain/kotlin/org/multipaz/compose/camera/Camera.ios.kt, multipaz-compose/src/iosMain/kotlin/org/multipaz/compose/camera/CameraImage.ios.kt, multipaz-mlkit/build.gradle.kts, multipaz-mlkit/src/androidMain/kotlin/org/multipaz/facematch/FaceMatchLiteRtModel.android.kt, multipaz-mlkit/src/androidMain/kotlin/org/multipaz/facematch/FaceNet.android.kt, multipaz-mlkit/src/commonMain/kotlin/org/multipaz/facematch/FaceEmbedding.kt, multipaz-mlkit/src/commonMain/kotlin/org/multipaz/facematch/FaceMatchLiteRtModel.kt, multipaz-mlkit/src/commonMain/kotlin/org/multipaz/facematch/FaceNet.kt, multipaz-mlkit/src/commonMain/kotlin/org/multipaz/selfiecheck/SelfieCheckViewModel.kt, multipaz-mlkit/src/iosMain/kotlin/org/multipaz/facematch/FaceMatchLiteRtModel.ios.kt, multipaz-mlkit/src/iosMain/kotlin/org/multipaz/facematch/FaceNet.ios.kt, multipaz-mlkit/src/iosMain/kotlin/org/multipaz/facematch/Utils.kt, samples/testapp/src/commonMain/composeResources/values/strings.xml, samples/testapp/src/commonMain/kotlin/org/multipaz/testapp/App.kt, samples/testapp/src/commonMain/kotlin/org/multipaz/testapp/Destinations.kt, samples/testapp/src/commonMain/kotlin/org/multipaz/testapp/ui/FaceDetectionScreen.kt, samples/testapp/src/commonMain/kotlin/org/multipaz/testapp/ui/FaceMatchScreen.kt, samples/testapp/src/commonMain/kotlin/org/multipaz/testapp/ui/StartScreen.kt
- Two steps screen menu: enroll, match.
- Match shows the similarity percentage and allows to retry the check.
- The match is considered anything above 40%
- To completely reset enroll a face again.
- The iOS impl. is in progress
Test: All Unit tests are passing (bar KI).
Test: Manually tested via samples/testapp on Android.
=> Implement KMP Face Matching screen.

CHANGELOG.md, Package.swift, build.gradle.kts
=> Update for 0.93.0 release.

CHANGELOG.md, build.gradle.kts
=> Post-release version bump to 0.94.0.

gradle/libs.versions.toml, multipaz-openid4vci-server/build.gradle.kts, multipaz-openid4vci-server/src/main/java/org/multipaz/openid4vci/server/ApplicationExt.kt, multipaz-openid4vci-server/src/test/java/org/multipaz/openid4vci/server/ProvisioningClientTest.kt, multipaz/src/commonMain/kotlin/org/multipaz/provision/AuthorizationChallenge.kt, multipaz/src/commonMain/kotlin/org/multipaz/provision/AuthorizationResponse.kt, multipaz/src/commonMain/kotlin/org/multipaz/provision/CredentialFormat.kt, multipaz/src/commonMain/kotlin/org/multipaz/provision/CredentialMetadata.kt, multipaz/src/commonMain/kotlin/org/multipaz/provision/Display.kt, multipaz/src/commonMain/kotlin/org/multipaz/provision/KeyBindingInfo.kt, multipaz/src/commonMain/kotlin/org/multipaz/provision/KeyBindingType.kt, multipaz/src/commonMain/kotlin/org/multipaz/provision/ProvisioningClient.kt, multipaz/src/commonMain/kotlin/org/multipaz/provision/ProvisioningMetadata.kt, multipaz/src/commonMain/kotlin/org/multipaz/provision/openid4vci/AuthorizationConfiguration.kt, multipaz/src/commonMain/kotlin/org/multipaz/provision/openid4vci/CredentialConfiguration.kt, multipaz/src/commonMain/kotlin/org/multipaz/provision/openid4vci/CredentialOffer.kt, multipaz/src/commonMain/kotlin/org/multipaz/provision/openid4vci/IssuerConfiguration.kt, multipaz/src/commonMain/kotlin/org/multipaz/provision/openid4vci/JsonParsing.kt, multipaz/src/commonMain/kotlin/org/multipaz/provision/openid4vci/OpenID4VCI.kt, multipaz/src/commonMain/kotlin/org/multipaz/provision/openid4vci/OpenID4VCIBackend.kt, multipaz/src/commonMain/kotlin/org/multipaz/provision/openid4vci/OpenID4VCIClientPreferences.kt, multipaz/src/commonMain/kotlin/org/multipaz/provision/openid4vci/OpenID4VCIProvisioningClient.kt, multipaz/src/commonMain/kotlin/org/multipaz/provision/openid4vci/OpenIDUtil.kt, multipaz/src/jvmMain/kotlin/org/multipaz/server/ServerEnvironment.kt
Test: added client/server integration test.
=> First cut of ProvisioningClient and its implementation for openid4vci.

multipaz-openid4vci-server/src/main/java/org/multipaz/openid4vci/request/authorize.kt, multipaz-openid4vci-server/src/main/java/org/multipaz/openid4vci/request/authorizeChallenge.kt, multipaz-openid4vci-server/src/main/java/org/multipaz/openid4vci/request/credential.kt, multipaz-openid4vci-server/src/main/java/org/multipaz/openid4vci/request/finishAuthorization.kt, multipaz-openid4vci-server/src/main/java/org/multipaz/openid4vci/request/token.kt, multipaz-openid4vci-server/src/main/java/org/multipaz/openid4vci/server/ApplicationExt.kt, multipaz-openid4vci-server/src/main/java/org/multipaz/openid4vci/util/IssuanceState.kt, multipaz-openid4vci-server/src/main/java/org/multipaz/openid4vci/util/OpenID4VCIRequestError.kt, multipaz-openid4vci-server/src/main/java/org/multipaz/openid4vci/util/auth.kt, multipaz-openid4vci-server/src/main/resources/resources/authorize.html, multipaz-openid4vci-server/src/main/resources/resources/pre-authorized.html, multipaz-openid4vci-server/src/main/resources/resources/www/display_metadata.js, multipaz/src/commonMain/kotlin/org/multipaz/provisioning/AuthorizationChallenge.kt, multipaz/src/commonMain/kotlin/org/multipaz/provisioning/AuthorizationResponse.kt, multipaz/src/commonMain/kotlin/org/multipaz/provisioning/SecretCodeRequest.kt, multipaz/src/commonMain/kotlin/org/multipaz/provisioning/openid4vci/CredentialOffer.kt, multipaz/src/commonMain/kotlin/org/multipaz/provisioning/openid4vci/OpenID4VCIProvisioningClient.kt, samples/testapp/src/commonMain/kotlin/org/multipaz/testapp/ui/ProvisioningTestScreen.kt
Implemented pre-suthorized code workflow on both the server and the client.
Test: manual testing with and without system-of-record server.
=> Pre-authorized code workflow for OpenID4VCI.

.github/workflows/trigger-docusaurus-update.yml
updates the `trigger-docusaurus-update.yml` workflow file to `openwallet-foundation/multipaz-developer-website` to reflect the repo transfer
=> updates the `trigger-docusaurus-update.yml` workflow file to reflect the repo transfer

multipaz-openid4vci-server/src/main/java/org/multipaz/openid4vci/credential/CredentialFactoryMdocPid.kt, multipaz-openid4vci-server/src/main/java/org/multipaz/openid4vci/request/authorize.kt, multipaz-openid4vci-server/src/main/java/org/multipaz/openid4vci/request/finishAuthorization.kt, multipaz-openid4vci-server/src/main/java/org/multipaz/openid4vci/request/preauthorizedOffer.kt, multipaz-openid4vci-server/src/main/java/org/multipaz/openid4vci/request/wellKnownOpenidCredentialIssuer.kt, multipaz-openid4vci-server/src/main/java/org/multipaz/openid4vci/server/ApplicationExt.kt, multipaz-openid4vci-server/src/main/java/org/multipaz/openid4vci/util/preauthorized.kt, multipaz-openid4vci-server/src/main/resources/resources/www/display_metadata.js, multipaz-records-server/src/main/java/org/multipaz/records/data/AuthorizationData.kt, multipaz-records-server/src/main/java/org/multipaz/records/data/jsonConv.kt, multipaz-records-server/src/main/java/org/multipaz/records/request/authorize.kt, multipaz-records-server/src/main/java/org/multipaz/records/request/data.kt, multipaz-records-server/src/main/java/org/multipaz/records/request/identityOffer.kt, multipaz-records-server/src/main/java/org/multipaz/records/request/identitySchema.kt, multipaz-records-server/src/main/java/org/multipaz/records/request/token.kt, multipaz-records-server/src/main/java/org/multipaz/records/server/ApplicationExt.kt, multipaz-records-server/src/main/resources/resources/authorize.html, multipaz-records-server/src/main/resources/resources/www/index.html, multipaz-records-server/src/main/resources/resources/www/list.js, multipaz-records-server/src/main/resources/resources/www/login.js, multipaz-records-server/src/main/resources/resources/www/offer.html, multipaz-records-server/src/main/resources/resources/www/offer.js, multipaz-records-server/src/main/resources/resources/www/person.html, multipaz-records-server/src/main/resources/resources/www/person.js, multipaz-records-server/src/main/resources/resources/www/style.css
- Pre-authorized offers can now be initiated from the System of Records main page
- Support for multiple records of the same type (for both pre-authorized and regular offers).
Testing: manually tested
=> Improvements to OpenID4VCI provisioning workflows.

multipaz-compose/src/commonMain/composeResources/values/strings.xml, multipaz-compose/src/commonMain/kotlin/org/multipaz/compose/provisioning/Provisioning.kt, multipaz-models/src/commonMain/kotlin/org/multipaz/models/provisioning/ProvisioningModel.kt, samples/testapp/src/commonMain/kotlin/org/multipaz/testapp/App.kt
Moved UI code for provisioning to `multipaz-compose`, modified testapp to use that code.
=> Compose UI component to help with provisioning.
